%% Generated by the Erlang ASN.1 compiler. Version: 5.0.17
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module REAL-TYPE.

-ifndef(_REAL_TYPE_HRL_).
-define(_REAL_TYPE_HRL_, true).

-record('RealType', {
  mantissa,
  base,
  exponent
}).

-endif. %% _REAL_TYPE_HRL_
