%% Generated by the Erlang ASN.1 PER (aligned) compiler. Version: 5.0.17
%% Purpose: Encoding and decoding of the types in TIME-DIFFERENCE.

-module('TIME-DIFFERENCE').
-compile(nowarn_unused_vars).
-dialyzer(no_improper_lists).
-dialyzer(no_match).
-include("TIME-DIFFERENCE.hrl").
-asn1_info([{vsn,'5.0.17'},
            {module,'TIME-DIFFERENCE'},
            {options,[{i,"/home/sandeep/workspace/asn1c-go/lib/builtin/testing/erlang/aper"},
 {outdir,"/home/sandeep/workspace/asn1c-go/lib/builtin/testing/erlang/aper"},
 per,
 {i,"."},
 {i,".."}]}]).

-export([encoding_rule/0,maps/0,bit_string_format/0,
         legacy_erlang_types/0]).
-export(['dialyzer-suppressions'/1]).
-export([
'enc_TIME-DIFFERENCE'/1,
'enc_HOURS-ENCODING'/1,
'enc_HOURS-UTC-ENCODING'/1,
'enc_HOURS-AND-DIFF-ENCODING'/1,
'enc_MINUTES-ENCODING'/1,
'enc_MINUTES-UTC-ENCODING'/1,
'enc_MINUTES-AND-DIFF-ENCODING'/1,
'enc_TIME-OF-DAY-ENCODING'/1,
'enc_TIME-OF-DAY-UTC-ENCODING'/1,
'enc_TIME-OF-DAY-AND-DIFF-ENCODING'/1,
'enc_HOURS-AND-FRACTION-ENCODING'/1,
'enc_HOURS-UTC-AND-FRACTION-ENCODING'/1,
'enc_HOURS-AND-DIFF-AND-FRACTION-ENCODING'/1,
'enc_MINUTES-AND-FRACTION-ENCODING'/1,
'enc_MINUTES-UTC-AND-FRACTION-ENCODING'/1,
'enc_MINUTES-AND-DIFF-AND-FRACTION-ENCODING'/1,
'enc_TIME-OF-DAY-AND-FRACTION-ENCODING'/1,
'enc_TIME-OF-DAY-UTC-AND-FRACTION-ENCODING'/1,
'enc_TIME-OF-DAY-AND-DIFF-AND-FRACTION-ENCODING'/1,
'enc_DURATION-INTERVAL-ENCODING'/1,
'enc_DURATION-EQUIVALENT'/1
]).

-export([
'dec_TIME-DIFFERENCE'/1,
'dec_HOURS-ENCODING'/1,
'dec_HOURS-UTC-ENCODING'/1,
'dec_HOURS-AND-DIFF-ENCODING'/1,
'dec_MINUTES-ENCODING'/1,
'dec_MINUTES-UTC-ENCODING'/1,
'dec_MINUTES-AND-DIFF-ENCODING'/1,
'dec_TIME-OF-DAY-ENCODING'/1,
'dec_TIME-OF-DAY-UTC-ENCODING'/1,
'dec_TIME-OF-DAY-AND-DIFF-ENCODING'/1,
'dec_HOURS-AND-FRACTION-ENCODING'/1,
'dec_HOURS-UTC-AND-FRACTION-ENCODING'/1,
'dec_HOURS-AND-DIFF-AND-FRACTION-ENCODING'/1,
'dec_MINUTES-AND-FRACTION-ENCODING'/1,
'dec_MINUTES-UTC-AND-FRACTION-ENCODING'/1,
'dec_MINUTES-AND-DIFF-AND-FRACTION-ENCODING'/1,
'dec_TIME-OF-DAY-AND-FRACTION-ENCODING'/1,
'dec_TIME-OF-DAY-UTC-AND-FRACTION-ENCODING'/1,
'dec_TIME-OF-DAY-AND-DIFF-AND-FRACTION-ENCODING'/1,
'dec_DURATION-INTERVAL-ENCODING'/1,
'dec_DURATION-EQUIVALENT'/1
]).

-export([info/0]).

-export([encode/2,decode/2]).

encoding_rule() -> per.

maps() -> false.

bit_string_format() -> bitstring.

legacy_erlang_types() -> false.

encode(Type, Data) ->
try complete(encode_disp(Type, Data)) of
  Bytes ->
    {ok,Bytes}
  catch
    Class:Exception:Stk when Class =:= error; Class =:= exit ->
      case Exception of
        {error,{asn1,Reason}} ->
          {error,{asn1,{Reason,Stk}}};
        Reason ->
         {error,{asn1,{Reason,Stk}}}
      end
end.

decode(Type, Data) ->
try
   {Result,_Rest} = decode_disp(Type, Data),
   {ok,Result}
  catch
    Class:Exception:Stk when Class =:= error; Class =:= exit ->
      case Exception of
        {error,{asn1,Reason}} ->
          {error,{asn1,{Reason,Stk}}};
        Reason ->
         {error,{asn1,{Reason,Stk}}}
      end
end.

encode_disp('TIME-DIFFERENCE', Data) -> 'enc_TIME-DIFFERENCE'(Data);
encode_disp('HOURS-ENCODING', Data) -> 'enc_HOURS-ENCODING'(Data);
encode_disp('HOURS-UTC-ENCODING', Data) -> 'enc_HOURS-UTC-ENCODING'(Data);
encode_disp('HOURS-AND-DIFF-ENCODING', Data) -> 'enc_HOURS-AND-DIFF-ENCODING'(Data);
encode_disp('MINUTES-ENCODING', Data) -> 'enc_MINUTES-ENCODING'(Data);
encode_disp('MINUTES-UTC-ENCODING', Data) -> 'enc_MINUTES-UTC-ENCODING'(Data);
encode_disp('MINUTES-AND-DIFF-ENCODING', Data) -> 'enc_MINUTES-AND-DIFF-ENCODING'(Data);
encode_disp('TIME-OF-DAY-ENCODING', Data) -> 'enc_TIME-OF-DAY-ENCODING'(Data);
encode_disp('TIME-OF-DAY-UTC-ENCODING', Data) -> 'enc_TIME-OF-DAY-UTC-ENCODING'(Data);
encode_disp('TIME-OF-DAY-AND-DIFF-ENCODING', Data) -> 'enc_TIME-OF-DAY-AND-DIFF-ENCODING'(Data);
encode_disp('HOURS-AND-FRACTION-ENCODING', Data) -> 'enc_HOURS-AND-FRACTION-ENCODING'(Data);
encode_disp('HOURS-UTC-AND-FRACTION-ENCODING', Data) -> 'enc_HOURS-UTC-AND-FRACTION-ENCODING'(Data);
encode_disp('HOURS-AND-DIFF-AND-FRACTION-ENCODING', Data) -> 'enc_HOURS-AND-DIFF-AND-FRACTION-ENCODING'(Data);
encode_disp('MINUTES-AND-FRACTION-ENCODING', Data) -> 'enc_MINUTES-AND-FRACTION-ENCODING'(Data);
encode_disp('MINUTES-UTC-AND-FRACTION-ENCODING', Data) -> 'enc_MINUTES-UTC-AND-FRACTION-ENCODING'(Data);
encode_disp('MINUTES-AND-DIFF-AND-FRACTION-ENCODING', Data) -> 'enc_MINUTES-AND-DIFF-AND-FRACTION-ENCODING'(Data);
encode_disp('TIME-OF-DAY-AND-FRACTION-ENCODING', Data) -> 'enc_TIME-OF-DAY-AND-FRACTION-ENCODING'(Data);
encode_disp('TIME-OF-DAY-UTC-AND-FRACTION-ENCODING', Data) -> 'enc_TIME-OF-DAY-UTC-AND-FRACTION-ENCODING'(Data);
encode_disp('TIME-OF-DAY-AND-DIFF-AND-FRACTION-ENCODING', Data) -> 'enc_TIME-OF-DAY-AND-DIFF-AND-FRACTION-ENCODING'(Data);
encode_disp('DURATION-INTERVAL-ENCODING', Data) -> 'enc_DURATION-INTERVAL-ENCODING'(Data);
encode_disp('DURATION-EQUIVALENT', Data) -> 'enc_DURATION-EQUIVALENT'(Data);
encode_disp(Type, _Data) -> exit({error,{asn1,{undefined_type,Type}}}).

decode_disp('TIME-DIFFERENCE', Data) -> 'dec_TIME-DIFFERENCE'(Data);
decode_disp('HOURS-ENCODING', Data) -> 'dec_HOURS-ENCODING'(Data);
decode_disp('HOURS-UTC-ENCODING', Data) -> 'dec_HOURS-UTC-ENCODING'(Data);
decode_disp('HOURS-AND-DIFF-ENCODING', Data) -> 'dec_HOURS-AND-DIFF-ENCODING'(Data);
decode_disp('MINUTES-ENCODING', Data) -> 'dec_MINUTES-ENCODING'(Data);
decode_disp('MINUTES-UTC-ENCODING', Data) -> 'dec_MINUTES-UTC-ENCODING'(Data);
decode_disp('MINUTES-AND-DIFF-ENCODING', Data) -> 'dec_MINUTES-AND-DIFF-ENCODING'(Data);
decode_disp('TIME-OF-DAY-ENCODING', Data) -> 'dec_TIME-OF-DAY-ENCODING'(Data);
decode_disp('TIME-OF-DAY-UTC-ENCODING', Data) -> 'dec_TIME-OF-DAY-UTC-ENCODING'(Data);
decode_disp('TIME-OF-DAY-AND-DIFF-ENCODING', Data) -> 'dec_TIME-OF-DAY-AND-DIFF-ENCODING'(Data);
decode_disp('HOURS-AND-FRACTION-ENCODING', Data) -> 'dec_HOURS-AND-FRACTION-ENCODING'(Data);
decode_disp('HOURS-UTC-AND-FRACTION-ENCODING', Data) -> 'dec_HOURS-UTC-AND-FRACTION-ENCODING'(Data);
decode_disp('HOURS-AND-DIFF-AND-FRACTION-ENCODING', Data) -> 'dec_HOURS-AND-DIFF-AND-FRACTION-ENCODING'(Data);
decode_disp('MINUTES-AND-FRACTION-ENCODING', Data) -> 'dec_MINUTES-AND-FRACTION-ENCODING'(Data);
decode_disp('MINUTES-UTC-AND-FRACTION-ENCODING', Data) -> 'dec_MINUTES-UTC-AND-FRACTION-ENCODING'(Data);
decode_disp('MINUTES-AND-DIFF-AND-FRACTION-ENCODING', Data) -> 'dec_MINUTES-AND-DIFF-AND-FRACTION-ENCODING'(Data);
decode_disp('TIME-OF-DAY-AND-FRACTION-ENCODING', Data) -> 'dec_TIME-OF-DAY-AND-FRACTION-ENCODING'(Data);
decode_disp('TIME-OF-DAY-UTC-AND-FRACTION-ENCODING', Data) -> 'dec_TIME-OF-DAY-UTC-AND-FRACTION-ENCODING'(Data);
decode_disp('TIME-OF-DAY-AND-DIFF-AND-FRACTION-ENCODING', Data) -> 'dec_TIME-OF-DAY-AND-DIFF-AND-FRACTION-ENCODING'(Data);
decode_disp('DURATION-INTERVAL-ENCODING', Data) -> 'dec_DURATION-INTERVAL-ENCODING'(Data);
decode_disp('DURATION-EQUIVALENT', Data) -> 'dec_DURATION-EQUIVALENT'(Data);
decode_disp(Type, _Data) -> exit({error,{asn1,{undefined_type,Type}}}).

info() ->
   case ?MODULE:module_info(attributes) of
     Attributes when is_list(Attributes) ->
       case lists:keyfind(asn1_info, 1, Attributes) of
         {_,Info} when is_list(Info) ->
           Info;
         _ ->
           []
       end;
     _ ->
       []
   end.
'enc_TIME-DIFFERENCE'(Val) ->
[begin
Enc1@element = element(4, Val),
%% attribute sign(1) with type ENUMERATED
Enc2@element = element(2, Val),
if Enc1@element =:= asn1_NOVALUE ->
if Enc2@element =:= positive ->
<<0:1,0:1>>;
Enc2@element =:= negative ->
<<0:1,1:1>>;
true ->
exit({error,{asn1,{illegal_enumerated,Enc2@element}}})
end;
true ->
if Enc2@element =:= positive ->
<<1:1,0:1>>;
Enc2@element =:= negative ->
<<1:1,1:1>>;
true ->
exit({error,{asn1,{illegal_enumerated,Enc2@element}}})
end
end
end,
begin
%% attribute hours(2) with type INTEGER
Enc4@element = element(3, Val),
if Enc4@element bsr 4 =:= 0 ->
<<Enc4@element:4>>;
true ->
exit({error,{asn1,{illegal_integer,Enc4@element}}})
end
end|begin
%% attribute minutes(3) with type INTEGER
Enc6@element = element(4, Val),
if Enc6@element =:= asn1_NOVALUE ->
[];
true ->
begin
Enc6@element@sub = Enc6@element - 1,
if 0 =< Enc6@element@sub, Enc6@element@sub < 59 ->
<<Enc6@element@sub:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc6@element}}})
end
end
end
end].


'dec_TIME-DIFFERENCE'(Bytes) ->
{Opt,Bytes1} = begin
<<V1@V0:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute sign(1) with type ENUMERATED
{Term1,Bytes2} = begin
<<V2@V0:1/unsigned-unit:1,V2@Buf1/bitstring>> = Bytes1,
V2@Int2 = case V2@V0 of
0 -> positive;
1 -> negative
end,
{V2@Int2,V2@Buf1}
end,

%% attribute hours(2) with type INTEGER
{Term2,Bytes3} = begin
<<V3@V0:4/unsigned-unit:1,V3@Buf1/bitstring>> = Bytes2,
{V3@V0,V3@Buf1}
end,

%% attribute minutes(3) with type INTEGER
{Term3,Bytes4} = case Opt band 1 of
1 ->
begin
<<V4@V0:6/unsigned-unit:1,V4@Buf1/bitstring>> = Bytes3,
V4@Add2 = V4@V0 + 1,
{V4@Add2,V4@Buf1}
end;
0 ->
{asn1_NOVALUE,Bytes3}
end,
Res1 = {'TIME-DIFFERENCE',Term1,Term2,Term3},
{Res1,Bytes4}.

'enc_HOURS-ENCODING'(Val) ->
if 0 =< Val, Val < 25 ->
<<Val:5>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_HOURS-ENCODING'(Bytes) ->
begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_HOURS-UTC-ENCODING'(Val) ->
if 0 =< Val, Val < 25 ->
<<Val:5>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_HOURS-UTC-ENCODING'(Bytes) ->
begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_HOURS-AND-DIFF-ENCODING'(Val) ->
[begin
%% attribute local-hours(1) with type INTEGER
Enc1@element = element(2, Val),
if 0 =< Enc1@element, Enc1@element < 25 ->
<<Enc1@element:5>>;
true ->
exit({error,{asn1,{illegal_integer,Enc1@element}}})
end
end|begin
%% attribute time-difference(2) with type TIME-DIFFERENCE
Enc3@element = element(3, Val),
'enc_TIME-DIFFERENCE'(Enc3@element)
end].


'dec_HOURS-AND-DIFF-ENCODING'(Bytes) ->

%% attribute local-hours(1) with type INTEGER
{Term1,Bytes1} = begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute time-difference(2) with type TIME-DIFFERENCE
{Term2,Bytes2} = 'dec_TIME-DIFFERENCE'(Bytes1),
Res1 = {'HOURS-AND-DIFF-ENCODING',Term1,Term2},
{Res1,Bytes2}.

'enc_MINUTES-ENCODING'(Val) ->
[begin
%% attribute hours(1) with type INTEGER
Enc1@element = element(2, Val),
if 0 =< Enc1@element, Enc1@element < 25 ->
<<Enc1@element:5>>;
true ->
exit({error,{asn1,{illegal_integer,Enc1@element}}})
end
end|begin
%% attribute minutes(2) with type INTEGER
Enc3@element = element(3, Val),
if 0 =< Enc3@element, Enc3@element < 60 ->
<<Enc3@element:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc3@element}}})
end
end].


'dec_MINUTES-ENCODING'(Bytes) ->

%% attribute hours(1) with type INTEGER
{Term1,Bytes1} = begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute minutes(2) with type INTEGER
{Term2,Bytes2} = begin
<<V2@V0:6/unsigned-unit:1,V2@Buf1/bitstring>> = Bytes1,
{V2@V0,V2@Buf1}
end,
Res1 = {'MINUTES-ENCODING',Term1,Term2},
{Res1,Bytes2}.

'enc_MINUTES-UTC-ENCODING'(Val) ->
[begin
%% attribute hours(1) with type INTEGER
Enc1@element = element(2, Val),
if 0 =< Enc1@element, Enc1@element < 25 ->
<<Enc1@element:5>>;
true ->
exit({error,{asn1,{illegal_integer,Enc1@element}}})
end
end|begin
%% attribute minutes(2) with type INTEGER
Enc3@element = element(3, Val),
if 0 =< Enc3@element, Enc3@element < 60 ->
<<Enc3@element:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc3@element}}})
end
end].


'dec_MINUTES-UTC-ENCODING'(Bytes) ->

%% attribute hours(1) with type INTEGER
{Term1,Bytes1} = begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute minutes(2) with type INTEGER
{Term2,Bytes2} = begin
<<V2@V0:6/unsigned-unit:1,V2@Buf1/bitstring>> = Bytes1,
{V2@V0,V2@Buf1}
end,
Res1 = {'MINUTES-UTC-ENCODING',Term1,Term2},
{Res1,Bytes2}.

'enc_MINUTES-AND-DIFF-ENCODING'(Val) ->
[begin
%% attribute local-time(1) with type SEQUENCE
Enc1@element = element(2, Val),
'enc_MINUTES-AND-DIFF-ENCODING_local-time'(Enc1@element)
end|begin
%% attribute time-difference(2) with type TIME-DIFFERENCE
Enc2@element = element(3, Val),
'enc_TIME-DIFFERENCE'(Enc2@element)
end].
'enc_MINUTES-AND-DIFF-ENCODING_local-time'(Val) ->
[begin
%% attribute hours(1) with type INTEGER
Enc1@element = element(2, Val),
if 0 =< Enc1@element, Enc1@element < 25 ->
<<Enc1@element:5>>;
true ->
exit({error,{asn1,{illegal_integer,Enc1@element}}})
end
end|begin
%% attribute minutes(2) with type INTEGER
Enc3@element = element(3, Val),
if 0 =< Enc3@element, Enc3@element < 60 ->
<<Enc3@element:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc3@element}}})
end
end].


'dec_MINUTES-AND-DIFF-ENCODING'(Bytes) ->

%% attribute local-time(1) with type SEQUENCE
{Term1,Bytes1} = 'dec_MINUTES-AND-DIFF-ENCODING_local-time'(Bytes),

%% attribute time-difference(2) with type TIME-DIFFERENCE
{Term2,Bytes2} = 'dec_TIME-DIFFERENCE'(Bytes1),
Res1 = {'MINUTES-AND-DIFF-ENCODING',Term1,Term2},
{Res1,Bytes2}.


'dec_MINUTES-AND-DIFF-ENCODING_local-time'(Bytes) ->

%% attribute hours(1) with type INTEGER
{Term1,Bytes1} = begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute minutes(2) with type INTEGER
{Term2,Bytes2} = begin
<<V2@V0:6/unsigned-unit:1,V2@Buf1/bitstring>> = Bytes1,
{V2@V0,V2@Buf1}
end,
Res1 = {'MINUTES-AND-DIFF-ENCODING_local-time',Term1,Term2},
{Res1,Bytes2}.

'enc_TIME-OF-DAY-ENCODING'(Val) ->
[begin
%% attribute hours(1) with type INTEGER
Enc1@element = element(2, Val),
if 0 =< Enc1@element, Enc1@element < 25 ->
<<Enc1@element:5>>;
true ->
exit({error,{asn1,{illegal_integer,Enc1@element}}})
end
end,
begin
%% attribute minutes(2) with type INTEGER
Enc3@element = element(3, Val),
if 0 =< Enc3@element, Enc3@element < 60 ->
<<Enc3@element:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc3@element}}})
end
end|begin
%% attribute seconds(3) with type INTEGER
Enc5@element = element(4, Val),
if 0 =< Enc5@element, Enc5@element < 61 ->
<<Enc5@element:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc5@element}}})
end
end].


'dec_TIME-OF-DAY-ENCODING'(Bytes) ->

%% attribute hours(1) with type INTEGER
{Term1,Bytes1} = begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute minutes(2) with type INTEGER
{Term2,Bytes2} = begin
<<V2@V0:6/unsigned-unit:1,V2@Buf1/bitstring>> = Bytes1,
{V2@V0,V2@Buf1}
end,

%% attribute seconds(3) with type INTEGER
{Term3,Bytes3} = begin
<<V3@V0:6/unsigned-unit:1,V3@Buf1/bitstring>> = Bytes2,
{V3@V0,V3@Buf1}
end,
Res1 = {'TIME-OF-DAY-ENCODING',Term1,Term2,Term3},
{Res1,Bytes3}.

'enc_TIME-OF-DAY-UTC-ENCODING'(Val) ->
[begin
%% attribute hours(1) with type INTEGER
Enc1@element = element(2, Val),
if 0 =< Enc1@element, Enc1@element < 25 ->
<<Enc1@element:5>>;
true ->
exit({error,{asn1,{illegal_integer,Enc1@element}}})
end
end,
begin
%% attribute minutes(2) with type INTEGER
Enc3@element = element(3, Val),
if 0 =< Enc3@element, Enc3@element < 60 ->
<<Enc3@element:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc3@element}}})
end
end|begin
%% attribute seconds(3) with type INTEGER
Enc5@element = element(4, Val),
if 0 =< Enc5@element, Enc5@element < 61 ->
<<Enc5@element:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc5@element}}})
end
end].


'dec_TIME-OF-DAY-UTC-ENCODING'(Bytes) ->

%% attribute hours(1) with type INTEGER
{Term1,Bytes1} = begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute minutes(2) with type INTEGER
{Term2,Bytes2} = begin
<<V2@V0:6/unsigned-unit:1,V2@Buf1/bitstring>> = Bytes1,
{V2@V0,V2@Buf1}
end,

%% attribute seconds(3) with type INTEGER
{Term3,Bytes3} = begin
<<V3@V0:6/unsigned-unit:1,V3@Buf1/bitstring>> = Bytes2,
{V3@V0,V3@Buf1}
end,
Res1 = {'TIME-OF-DAY-UTC-ENCODING',Term1,Term2,Term3},
{Res1,Bytes3}.

'enc_TIME-OF-DAY-AND-DIFF-ENCODING'(Val) ->
[begin
%% attribute local-time(1) with type SEQUENCE
Enc1@element = element(2, Val),
'enc_TIME-OF-DAY-AND-DIFF-ENCODING_local-time'(Enc1@element)
end|begin
%% attribute time-difference(2) with type TIME-DIFFERENCE
Enc2@element = element(3, Val),
'enc_TIME-DIFFERENCE'(Enc2@element)
end].
'enc_TIME-OF-DAY-AND-DIFF-ENCODING_local-time'(Val) ->
[begin
%% attribute hours(1) with type INTEGER
Enc1@element = element(2, Val),
if 0 =< Enc1@element, Enc1@element < 25 ->
<<Enc1@element:5>>;
true ->
exit({error,{asn1,{illegal_integer,Enc1@element}}})
end
end,
begin
%% attribute minutes(2) with type INTEGER
Enc3@element = element(3, Val),
if 0 =< Enc3@element, Enc3@element < 60 ->
<<Enc3@element:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc3@element}}})
end
end|begin
%% attribute seconds(3) with type INTEGER
Enc5@element = element(4, Val),
if 0 =< Enc5@element, Enc5@element < 61 ->
<<Enc5@element:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc5@element}}})
end
end].


'dec_TIME-OF-DAY-AND-DIFF-ENCODING'(Bytes) ->

%% attribute local-time(1) with type SEQUENCE
{Term1,Bytes1} = 'dec_TIME-OF-DAY-AND-DIFF-ENCODING_local-time'(Bytes),

%% attribute time-difference(2) with type TIME-DIFFERENCE
{Term2,Bytes2} = 'dec_TIME-DIFFERENCE'(Bytes1),
Res1 = {'TIME-OF-DAY-AND-DIFF-ENCODING',Term1,Term2},
{Res1,Bytes2}.


'dec_TIME-OF-DAY-AND-DIFF-ENCODING_local-time'(Bytes) ->

%% attribute hours(1) with type INTEGER
{Term1,Bytes1} = begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute minutes(2) with type INTEGER
{Term2,Bytes2} = begin
<<V2@V0:6/unsigned-unit:1,V2@Buf1/bitstring>> = Bytes1,
{V2@V0,V2@Buf1}
end,

%% attribute seconds(3) with type INTEGER
{Term3,Bytes3} = begin
<<V3@V0:6/unsigned-unit:1,V3@Buf1/bitstring>> = Bytes2,
{V3@V0,V3@Buf1}
end,
Res1 = {'TIME-OF-DAY-AND-DIFF-ENCODING_local-time',Term1,Term2,Term3},
{Res1,Bytes3}.

'enc_HOURS-AND-FRACTION-ENCODING'(Val) ->
[begin
%% attribute hours(1) with type INTEGER
Enc1@element = element(2, Val),
if 0 =< Enc1@element, Enc1@element < 25 ->
<<Enc1@element:5>>;
true ->
exit({error,{asn1,{illegal_integer,Enc1@element}}})
end
end|begin
%% attribute fraction(2) with type INTEGER
Enc3@element = element(3, Val),
if 0 =< Enc3@element, Enc3@element < 1000 ->
[<<0:1>>,
align|<<Enc3@element:16>>];
true ->
[<<1:1>>,
align|encode_unconstrained_number(Enc3@element)]
end
end].


'dec_HOURS-AND-FRACTION-ENCODING'(Bytes) ->

%% attribute hours(1) with type INTEGER
{Term1,Bytes1} = begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute fraction(2) with type INTEGER
{Term2,Bytes2} = begin
{V2@V0,V2@Buf1} = case Bytes1 of
<<0:1,V2@Buf2/bitstring>> ->
V2@Pad5 = bit_size(V2@Buf2) band 7,
<<_:V2@Pad5,V2@V3:2/unsigned-unit:8,V2@Buf4/bitstring>> = V2@Buf2,
{V2@V3,V2@Buf4};
<<1:1,V2@Buf2/bitstring>> ->
V2@Pad6 = bit_size(V2@Buf2) band 7,
{V2@V3,V2@Buf4} = case V2@Buf2 of
<<_:V2@Pad6,0:1,V2@V8:7,V2@Buf9/bitstring>> when V2@V8 =/= 0 ->
{V2@V8,V2@Buf9};
<<_:V2@Pad6,1:1,0:1,V2@V9:14,V2@Buf10/bitstring>> when V2@V9 =/= 0 ->
{V2@V9,V2@Buf10}
end,
<<V2@V11:V2@V3/signed-unit:8,V2@Buf12/bitstring>> = V2@Buf4,
{V2@V11,V2@Buf12}
end,
{V2@V0,V2@Buf1}
end,
Res1 = {'HOURS-AND-FRACTION-ENCODING',Term1,Term2},
{Res1,Bytes2}.

'enc_HOURS-UTC-AND-FRACTION-ENCODING'(Val) ->
[begin
%% attribute hours(1) with type INTEGER
Enc1@element = element(2, Val),
if 0 =< Enc1@element, Enc1@element < 25 ->
<<Enc1@element:5>>;
true ->
exit({error,{asn1,{illegal_integer,Enc1@element}}})
end
end|begin
%% attribute fraction(2) with type INTEGER
Enc3@element = element(3, Val),
if 0 =< Enc3@element, Enc3@element < 1000 ->
[<<0:1>>,
align|<<Enc3@element:16>>];
true ->
[<<1:1>>,
align|encode_unconstrained_number(Enc3@element)]
end
end].


'dec_HOURS-UTC-AND-FRACTION-ENCODING'(Bytes) ->

%% attribute hours(1) with type INTEGER
{Term1,Bytes1} = begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute fraction(2) with type INTEGER
{Term2,Bytes2} = begin
{V2@V0,V2@Buf1} = case Bytes1 of
<<0:1,V2@Buf2/bitstring>> ->
V2@Pad5 = bit_size(V2@Buf2) band 7,
<<_:V2@Pad5,V2@V3:2/unsigned-unit:8,V2@Buf4/bitstring>> = V2@Buf2,
{V2@V3,V2@Buf4};
<<1:1,V2@Buf2/bitstring>> ->
V2@Pad6 = bit_size(V2@Buf2) band 7,
{V2@V3,V2@Buf4} = case V2@Buf2 of
<<_:V2@Pad6,0:1,V2@V8:7,V2@Buf9/bitstring>> when V2@V8 =/= 0 ->
{V2@V8,V2@Buf9};
<<_:V2@Pad6,1:1,0:1,V2@V9:14,V2@Buf10/bitstring>> when V2@V9 =/= 0 ->
{V2@V9,V2@Buf10}
end,
<<V2@V11:V2@V3/signed-unit:8,V2@Buf12/bitstring>> = V2@Buf4,
{V2@V11,V2@Buf12}
end,
{V2@V0,V2@Buf1}
end,
Res1 = {'HOURS-UTC-AND-FRACTION-ENCODING',Term1,Term2},
{Res1,Bytes2}.

'enc_HOURS-AND-DIFF-AND-FRACTION-ENCODING'(Val) ->
[begin
%% attribute local-hours(1) with type INTEGER
Enc1@element = element(2, Val),
if 0 =< Enc1@element, Enc1@element < 25 ->
<<Enc1@element:5>>;
true ->
exit({error,{asn1,{illegal_integer,Enc1@element}}})
end
end,
begin
%% attribute fraction(2) with type INTEGER
Enc3@element = element(3, Val),
if 0 =< Enc3@element, Enc3@element < 1000 ->
[<<0:1>>,
align|<<Enc3@element:16>>];
true ->
[<<1:1>>,
align|encode_unconstrained_number(Enc3@element)]
end
end|begin
%% attribute time-difference(3) with type TIME-DIFFERENCE
Enc5@element = element(4, Val),
'enc_TIME-DIFFERENCE'(Enc5@element)
end].


'dec_HOURS-AND-DIFF-AND-FRACTION-ENCODING'(Bytes) ->

%% attribute local-hours(1) with type INTEGER
{Term1,Bytes1} = begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute fraction(2) with type INTEGER
{Term2,Bytes2} = begin
{V2@V0,V2@Buf1} = case Bytes1 of
<<0:1,V2@Buf2/bitstring>> ->
V2@Pad5 = bit_size(V2@Buf2) band 7,
<<_:V2@Pad5,V2@V3:2/unsigned-unit:8,V2@Buf4/bitstring>> = V2@Buf2,
{V2@V3,V2@Buf4};
<<1:1,V2@Buf2/bitstring>> ->
V2@Pad6 = bit_size(V2@Buf2) band 7,
{V2@V3,V2@Buf4} = case V2@Buf2 of
<<_:V2@Pad6,0:1,V2@V8:7,V2@Buf9/bitstring>> when V2@V8 =/= 0 ->
{V2@V8,V2@Buf9};
<<_:V2@Pad6,1:1,0:1,V2@V9:14,V2@Buf10/bitstring>> when V2@V9 =/= 0 ->
{V2@V9,V2@Buf10}
end,
<<V2@V11:V2@V3/signed-unit:8,V2@Buf12/bitstring>> = V2@Buf4,
{V2@V11,V2@Buf12}
end,
{V2@V0,V2@Buf1}
end,

%% attribute time-difference(3) with type TIME-DIFFERENCE
{Term3,Bytes3} = 'dec_TIME-DIFFERENCE'(Bytes2),
Res1 = {'HOURS-AND-DIFF-AND-FRACTION-ENCODING',Term1,Term2,Term3},
{Res1,Bytes3}.

'enc_MINUTES-AND-FRACTION-ENCODING'(Val) ->
[begin
%% attribute hours(1) with type INTEGER
Enc1@element = element(2, Val),
if 0 =< Enc1@element, Enc1@element < 25 ->
<<Enc1@element:5>>;
true ->
exit({error,{asn1,{illegal_integer,Enc1@element}}})
end
end,
begin
%% attribute minutes(2) with type INTEGER
Enc3@element = element(3, Val),
if 0 =< Enc3@element, Enc3@element < 60 ->
<<Enc3@element:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc3@element}}})
end
end|begin
%% attribute fraction(3) with type INTEGER
Enc5@element = element(4, Val),
if 0 =< Enc5@element, Enc5@element < 1000 ->
[<<0:1>>,
align|<<Enc5@element:16>>];
true ->
[<<1:1>>,
align|encode_unconstrained_number(Enc5@element)]
end
end].


'dec_MINUTES-AND-FRACTION-ENCODING'(Bytes) ->

%% attribute hours(1) with type INTEGER
{Term1,Bytes1} = begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute minutes(2) with type INTEGER
{Term2,Bytes2} = begin
<<V2@V0:6/unsigned-unit:1,V2@Buf1/bitstring>> = Bytes1,
{V2@V0,V2@Buf1}
end,

%% attribute fraction(3) with type INTEGER
{Term3,Bytes3} = begin
{V3@V0,V3@Buf1} = case Bytes2 of
<<0:1,V3@Buf2/bitstring>> ->
V3@Pad5 = bit_size(V3@Buf2) band 7,
<<_:V3@Pad5,V3@V3:2/unsigned-unit:8,V3@Buf4/bitstring>> = V3@Buf2,
{V3@V3,V3@Buf4};
<<1:1,V3@Buf2/bitstring>> ->
V3@Pad6 = bit_size(V3@Buf2) band 7,
{V3@V3,V3@Buf4} = case V3@Buf2 of
<<_:V3@Pad6,0:1,V3@V8:7,V3@Buf9/bitstring>> when V3@V8 =/= 0 ->
{V3@V8,V3@Buf9};
<<_:V3@Pad6,1:1,0:1,V3@V9:14,V3@Buf10/bitstring>> when V3@V9 =/= 0 ->
{V3@V9,V3@Buf10}
end,
<<V3@V11:V3@V3/signed-unit:8,V3@Buf12/bitstring>> = V3@Buf4,
{V3@V11,V3@Buf12}
end,
{V3@V0,V3@Buf1}
end,
Res1 = {'MINUTES-AND-FRACTION-ENCODING',Term1,Term2,Term3},
{Res1,Bytes3}.

'enc_MINUTES-UTC-AND-FRACTION-ENCODING'(Val) ->
[begin
%% attribute hours(1) with type INTEGER
Enc1@element = element(2, Val),
if 0 =< Enc1@element, Enc1@element < 25 ->
<<Enc1@element:5>>;
true ->
exit({error,{asn1,{illegal_integer,Enc1@element}}})
end
end,
begin
%% attribute minutes(2) with type INTEGER
Enc3@element = element(3, Val),
if 0 =< Enc3@element, Enc3@element < 60 ->
<<Enc3@element:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc3@element}}})
end
end|begin
%% attribute fraction(3) with type INTEGER
Enc5@element = element(4, Val),
if 0 =< Enc5@element, Enc5@element < 1000 ->
[<<0:1>>,
align|<<Enc5@element:16>>];
true ->
[<<1:1>>,
align|encode_unconstrained_number(Enc5@element)]
end
end].


'dec_MINUTES-UTC-AND-FRACTION-ENCODING'(Bytes) ->

%% attribute hours(1) with type INTEGER
{Term1,Bytes1} = begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute minutes(2) with type INTEGER
{Term2,Bytes2} = begin
<<V2@V0:6/unsigned-unit:1,V2@Buf1/bitstring>> = Bytes1,
{V2@V0,V2@Buf1}
end,

%% attribute fraction(3) with type INTEGER
{Term3,Bytes3} = begin
{V3@V0,V3@Buf1} = case Bytes2 of
<<0:1,V3@Buf2/bitstring>> ->
V3@Pad5 = bit_size(V3@Buf2) band 7,
<<_:V3@Pad5,V3@V3:2/unsigned-unit:8,V3@Buf4/bitstring>> = V3@Buf2,
{V3@V3,V3@Buf4};
<<1:1,V3@Buf2/bitstring>> ->
V3@Pad6 = bit_size(V3@Buf2) band 7,
{V3@V3,V3@Buf4} = case V3@Buf2 of
<<_:V3@Pad6,0:1,V3@V8:7,V3@Buf9/bitstring>> when V3@V8 =/= 0 ->
{V3@V8,V3@Buf9};
<<_:V3@Pad6,1:1,0:1,V3@V9:14,V3@Buf10/bitstring>> when V3@V9 =/= 0 ->
{V3@V9,V3@Buf10}
end,
<<V3@V11:V3@V3/signed-unit:8,V3@Buf12/bitstring>> = V3@Buf4,
{V3@V11,V3@Buf12}
end,
{V3@V0,V3@Buf1}
end,
Res1 = {'MINUTES-UTC-AND-FRACTION-ENCODING',Term1,Term2,Term3},
{Res1,Bytes3}.

'enc_MINUTES-AND-DIFF-AND-FRACTION-ENCODING'(Val) ->
[begin
%% attribute local-time(1) with type SEQUENCE
Enc1@element = element(2, Val),
'enc_MINUTES-AND-DIFF-AND-FRACTION-ENCODING_local-time'(Enc1@element)
end|begin
%% attribute time-difference(2) with type TIME-DIFFERENCE
Enc2@element = element(3, Val),
'enc_TIME-DIFFERENCE'(Enc2@element)
end].
'enc_MINUTES-AND-DIFF-AND-FRACTION-ENCODING_local-time'(Val) ->
[begin
%% attribute hours(1) with type INTEGER
Enc1@element = element(2, Val),
if 0 =< Enc1@element, Enc1@element < 25 ->
<<Enc1@element:5>>;
true ->
exit({error,{asn1,{illegal_integer,Enc1@element}}})
end
end,
begin
%% attribute minutes(2) with type INTEGER
Enc3@element = element(3, Val),
if 0 =< Enc3@element, Enc3@element < 60 ->
<<Enc3@element:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc3@element}}})
end
end|begin
%% attribute fraction(3) with type INTEGER
Enc5@element = element(4, Val),
if 0 =< Enc5@element, Enc5@element < 1000 ->
[<<0:1>>,
align|<<Enc5@element:16>>];
true ->
[<<1:1>>,
align|encode_unconstrained_number(Enc5@element)]
end
end].


'dec_MINUTES-AND-DIFF-AND-FRACTION-ENCODING'(Bytes) ->

%% attribute local-time(1) with type SEQUENCE
{Term1,Bytes1} = 'dec_MINUTES-AND-DIFF-AND-FRACTION-ENCODING_local-time'(Bytes),

%% attribute time-difference(2) with type TIME-DIFFERENCE
{Term2,Bytes2} = 'dec_TIME-DIFFERENCE'(Bytes1),
Res1 = {'MINUTES-AND-DIFF-AND-FRACTION-ENCODING',Term1,Term2},
{Res1,Bytes2}.


'dec_MINUTES-AND-DIFF-AND-FRACTION-ENCODING_local-time'(Bytes) ->

%% attribute hours(1) with type INTEGER
{Term1,Bytes1} = begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute minutes(2) with type INTEGER
{Term2,Bytes2} = begin
<<V2@V0:6/unsigned-unit:1,V2@Buf1/bitstring>> = Bytes1,
{V2@V0,V2@Buf1}
end,

%% attribute fraction(3) with type INTEGER
{Term3,Bytes3} = begin
{V3@V0,V3@Buf1} = case Bytes2 of
<<0:1,V3@Buf2/bitstring>> ->
V3@Pad5 = bit_size(V3@Buf2) band 7,
<<_:V3@Pad5,V3@V3:2/unsigned-unit:8,V3@Buf4/bitstring>> = V3@Buf2,
{V3@V3,V3@Buf4};
<<1:1,V3@Buf2/bitstring>> ->
V3@Pad6 = bit_size(V3@Buf2) band 7,
{V3@V3,V3@Buf4} = case V3@Buf2 of
<<_:V3@Pad6,0:1,V3@V8:7,V3@Buf9/bitstring>> when V3@V8 =/= 0 ->
{V3@V8,V3@Buf9};
<<_:V3@Pad6,1:1,0:1,V3@V9:14,V3@Buf10/bitstring>> when V3@V9 =/= 0 ->
{V3@V9,V3@Buf10}
end,
<<V3@V11:V3@V3/signed-unit:8,V3@Buf12/bitstring>> = V3@Buf4,
{V3@V11,V3@Buf12}
end,
{V3@V0,V3@Buf1}
end,
Res1 = {'MINUTES-AND-DIFF-AND-FRACTION-ENCODING_local-time',Term1,Term2,Term3},
{Res1,Bytes3}.

'enc_TIME-OF-DAY-AND-FRACTION-ENCODING'(Val) ->
[begin
%% attribute hours(1) with type INTEGER
Enc1@element = element(2, Val),
if 0 =< Enc1@element, Enc1@element < 25 ->
<<Enc1@element:5>>;
true ->
exit({error,{asn1,{illegal_integer,Enc1@element}}})
end
end,
begin
%% attribute minutes(2) with type INTEGER
Enc3@element = element(3, Val),
if 0 =< Enc3@element, Enc3@element < 60 ->
<<Enc3@element:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc3@element}}})
end
end,
begin
%% attribute seconds(3) with type INTEGER
Enc5@element = element(4, Val),
if 0 =< Enc5@element, Enc5@element < 61 ->
<<Enc5@element:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc5@element}}})
end
end|begin
%% attribute fraction(4) with type INTEGER
Enc7@element = element(5, Val),
if 0 =< Enc7@element, Enc7@element < 1000 ->
[<<0:1>>,
align|<<Enc7@element:16>>];
true ->
[<<1:1>>,
align|encode_unconstrained_number(Enc7@element)]
end
end].


'dec_TIME-OF-DAY-AND-FRACTION-ENCODING'(Bytes) ->

%% attribute hours(1) with type INTEGER
{Term1,Bytes1} = begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute minutes(2) with type INTEGER
{Term2,Bytes2} = begin
<<V2@V0:6/unsigned-unit:1,V2@Buf1/bitstring>> = Bytes1,
{V2@V0,V2@Buf1}
end,

%% attribute seconds(3) with type INTEGER
{Term3,Bytes3} = begin
<<V3@V0:6/unsigned-unit:1,V3@Buf1/bitstring>> = Bytes2,
{V3@V0,V3@Buf1}
end,

%% attribute fraction(4) with type INTEGER
{Term4,Bytes4} = begin
{V4@V0,V4@Buf1} = case Bytes3 of
<<0:1,V4@Buf2/bitstring>> ->
V4@Pad5 = bit_size(V4@Buf2) band 7,
<<_:V4@Pad5,V4@V3:2/unsigned-unit:8,V4@Buf4/bitstring>> = V4@Buf2,
{V4@V3,V4@Buf4};
<<1:1,V4@Buf2/bitstring>> ->
V4@Pad6 = bit_size(V4@Buf2) band 7,
{V4@V3,V4@Buf4} = case V4@Buf2 of
<<_:V4@Pad6,0:1,V4@V8:7,V4@Buf9/bitstring>> when V4@V8 =/= 0 ->
{V4@V8,V4@Buf9};
<<_:V4@Pad6,1:1,0:1,V4@V9:14,V4@Buf10/bitstring>> when V4@V9 =/= 0 ->
{V4@V9,V4@Buf10}
end,
<<V4@V11:V4@V3/signed-unit:8,V4@Buf12/bitstring>> = V4@Buf4,
{V4@V11,V4@Buf12}
end,
{V4@V0,V4@Buf1}
end,
Res1 = {'TIME-OF-DAY-AND-FRACTION-ENCODING',Term1,Term2,Term3,Term4},
{Res1,Bytes4}.

'enc_TIME-OF-DAY-UTC-AND-FRACTION-ENCODING'(Val) ->
[begin
%% attribute hours(1) with type INTEGER
Enc1@element = element(2, Val),
if 0 =< Enc1@element, Enc1@element < 25 ->
<<Enc1@element:5>>;
true ->
exit({error,{asn1,{illegal_integer,Enc1@element}}})
end
end,
begin
%% attribute minutes(2) with type INTEGER
Enc3@element = element(3, Val),
if 0 =< Enc3@element, Enc3@element < 60 ->
<<Enc3@element:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc3@element}}})
end
end,
begin
%% attribute seconds(3) with type INTEGER
Enc5@element = element(4, Val),
if 0 =< Enc5@element, Enc5@element < 61 ->
<<Enc5@element:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc5@element}}})
end
end|begin
%% attribute fraction(4) with type INTEGER
Enc7@element = element(5, Val),
if 0 =< Enc7@element, Enc7@element < 1000 ->
[<<0:1>>,
align|<<Enc7@element:16>>];
true ->
[<<1:1>>,
align|encode_unconstrained_number(Enc7@element)]
end
end].


'dec_TIME-OF-DAY-UTC-AND-FRACTION-ENCODING'(Bytes) ->

%% attribute hours(1) with type INTEGER
{Term1,Bytes1} = begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute minutes(2) with type INTEGER
{Term2,Bytes2} = begin
<<V2@V0:6/unsigned-unit:1,V2@Buf1/bitstring>> = Bytes1,
{V2@V0,V2@Buf1}
end,

%% attribute seconds(3) with type INTEGER
{Term3,Bytes3} = begin
<<V3@V0:6/unsigned-unit:1,V3@Buf1/bitstring>> = Bytes2,
{V3@V0,V3@Buf1}
end,

%% attribute fraction(4) with type INTEGER
{Term4,Bytes4} = begin
{V4@V0,V4@Buf1} = case Bytes3 of
<<0:1,V4@Buf2/bitstring>> ->
V4@Pad5 = bit_size(V4@Buf2) band 7,
<<_:V4@Pad5,V4@V3:2/unsigned-unit:8,V4@Buf4/bitstring>> = V4@Buf2,
{V4@V3,V4@Buf4};
<<1:1,V4@Buf2/bitstring>> ->
V4@Pad6 = bit_size(V4@Buf2) band 7,
{V4@V3,V4@Buf4} = case V4@Buf2 of
<<_:V4@Pad6,0:1,V4@V8:7,V4@Buf9/bitstring>> when V4@V8 =/= 0 ->
{V4@V8,V4@Buf9};
<<_:V4@Pad6,1:1,0:1,V4@V9:14,V4@Buf10/bitstring>> when V4@V9 =/= 0 ->
{V4@V9,V4@Buf10}
end,
<<V4@V11:V4@V3/signed-unit:8,V4@Buf12/bitstring>> = V4@Buf4,
{V4@V11,V4@Buf12}
end,
{V4@V0,V4@Buf1}
end,
Res1 = {'TIME-OF-DAY-UTC-AND-FRACTION-ENCODING',Term1,Term2,Term3,Term4},
{Res1,Bytes4}.

'enc_TIME-OF-DAY-AND-DIFF-AND-FRACTION-ENCODING'(Val) ->
[begin
%% attribute local-time(1) with type SEQUENCE
Enc1@element = element(2, Val),
'enc_TIME-OF-DAY-AND-DIFF-AND-FRACTION-ENCODING_local-time'(Enc1@element)
end|begin
%% attribute time-difference(2) with type TIME-DIFFERENCE
Enc2@element = element(3, Val),
'enc_TIME-DIFFERENCE'(Enc2@element)
end].
'enc_TIME-OF-DAY-AND-DIFF-AND-FRACTION-ENCODING_local-time'(Val) ->
[begin
%% attribute hours(1) with type INTEGER
Enc1@element = element(2, Val),
if 0 =< Enc1@element, Enc1@element < 25 ->
<<Enc1@element:5>>;
true ->
exit({error,{asn1,{illegal_integer,Enc1@element}}})
end
end,
begin
%% attribute minutes(2) with type INTEGER
Enc3@element = element(3, Val),
if 0 =< Enc3@element, Enc3@element < 60 ->
<<Enc3@element:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc3@element}}})
end
end,
begin
%% attribute seconds(3) with type INTEGER
Enc5@element = element(4, Val),
if 0 =< Enc5@element, Enc5@element < 61 ->
<<Enc5@element:6>>;
true ->
exit({error,{asn1,{illegal_integer,Enc5@element}}})
end
end|begin
%% attribute fraction(4) with type INTEGER
Enc7@element = element(5, Val),
if 0 =< Enc7@element, Enc7@element < 1000 ->
[<<0:1>>,
align|<<Enc7@element:16>>];
true ->
[<<1:1>>,
align|encode_unconstrained_number(Enc7@element)]
end
end].


'dec_TIME-OF-DAY-AND-DIFF-AND-FRACTION-ENCODING'(Bytes) ->

%% attribute local-time(1) with type SEQUENCE
{Term1,Bytes1} = 'dec_TIME-OF-DAY-AND-DIFF-AND-FRACTION-ENCODING_local-time'(Bytes),

%% attribute time-difference(2) with type TIME-DIFFERENCE
{Term2,Bytes2} = 'dec_TIME-DIFFERENCE'(Bytes1),
Res1 = {'TIME-OF-DAY-AND-DIFF-AND-FRACTION-ENCODING',Term1,Term2},
{Res1,Bytes2}.


'dec_TIME-OF-DAY-AND-DIFF-AND-FRACTION-ENCODING_local-time'(Bytes) ->

%% attribute hours(1) with type INTEGER
{Term1,Bytes1} = begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute minutes(2) with type INTEGER
{Term2,Bytes2} = begin
<<V2@V0:6/unsigned-unit:1,V2@Buf1/bitstring>> = Bytes1,
{V2@V0,V2@Buf1}
end,

%% attribute seconds(3) with type INTEGER
{Term3,Bytes3} = begin
<<V3@V0:6/unsigned-unit:1,V3@Buf1/bitstring>> = Bytes2,
{V3@V0,V3@Buf1}
end,

%% attribute fraction(4) with type INTEGER
{Term4,Bytes4} = begin
{V4@V0,V4@Buf1} = case Bytes3 of
<<0:1,V4@Buf2/bitstring>> ->
V4@Pad5 = bit_size(V4@Buf2) band 7,
<<_:V4@Pad5,V4@V3:2/unsigned-unit:8,V4@Buf4/bitstring>> = V4@Buf2,
{V4@V3,V4@Buf4};
<<1:1,V4@Buf2/bitstring>> ->
V4@Pad6 = bit_size(V4@Buf2) band 7,
{V4@V3,V4@Buf4} = case V4@Buf2 of
<<_:V4@Pad6,0:1,V4@V8:7,V4@Buf9/bitstring>> when V4@V8 =/= 0 ->
{V4@V8,V4@Buf9};
<<_:V4@Pad6,1:1,0:1,V4@V9:14,V4@Buf10/bitstring>> when V4@V9 =/= 0 ->
{V4@V9,V4@Buf10}
end,
<<V4@V11:V4@V3/signed-unit:8,V4@Buf12/bitstring>> = V4@Buf4,
{V4@V11,V4@Buf12}
end,
{V4@V0,V4@Buf1}
end,
Res1 = {'TIME-OF-DAY-AND-DIFF-AND-FRACTION-ENCODING_local-time',Term1,Term2,Term3,Term4},
{Res1,Bytes4}.

'enc_DURATION-INTERVAL-ENCODING'(Val) ->
[begin
Enc1@element = element(2, Val),
Enc2@element = element(3, Val),
if Enc1@element =:= asn1_NOVALUE ->
if Enc2@element =:= asn1_NOVALUE ->
<<0:1,0:1>>;
true ->
<<0:1,1:1>>
end;
true ->
if Enc2@element =:= asn1_NOVALUE ->
<<1:1,0:1>>;
true ->
<<1:1,1:1>>
end
end
end,
begin
Enc3@element = element(4, Val),
Enc4@element = element(5, Val),
if Enc3@element =:= asn1_NOVALUE ->
if Enc4@element =:= asn1_NOVALUE ->
<<0:1,0:1>>;
true ->
<<0:1,1:1>>
end;
true ->
if Enc4@element =:= asn1_NOVALUE ->
<<1:1,0:1>>;
true ->
<<1:1,1:1>>
end
end
end,
begin
Enc5@element = element(6, Val),
Enc6@element = element(7, Val),
if Enc5@element =:= asn1_NOVALUE ->
if Enc6@element =:= asn1_NOVALUE ->
<<0:1,0:1>>;
true ->
<<0:1,1:1>>
end;
true ->
if Enc6@element =:= asn1_NOVALUE ->
<<1:1,0:1>>;
true ->
<<1:1,1:1>>
end
end
end,
begin
Enc7@element = element(8, Val),
Enc8@element = element(9, Val),
if Enc7@element =:= asn1_NOVALUE ->
if Enc8@element =:= asn1_NOVALUE ->
<<0:1,0:1>>;
true ->
<<0:1,1:1>>
end;
true ->
if Enc8@element =:= asn1_NOVALUE ->
<<1:1,0:1>>;
true ->
<<1:1,1:1>>
end
end
end,
begin
%% attribute years(1) with type INTEGER
Enc9@element = element(2, Val),
if Enc9@element =:= asn1_NOVALUE ->
[];
Enc9@element bsr 5 =:= 0 ->
<<0:1,Enc9@element:5>>;
true ->
[<<1:1>>,
align|encode_unconstrained_number(Enc9@element)]
end
end,
begin
%% attribute months(2) with type INTEGER
Enc12@element = element(3, Val),
if Enc12@element =:= asn1_NOVALUE ->
[];
Enc12@element bsr 4 =:= 0 ->
<<0:1,Enc12@element:4>>;
true ->
[<<1:1>>,
align|encode_unconstrained_number(Enc12@element)]
end
end,
begin
%% attribute weeks(3) with type INTEGER
Enc15@element = element(4, Val),
if Enc15@element =:= asn1_NOVALUE ->
[];
Enc15@element bsr 6 =:= 0 ->
<<0:1,Enc15@element:6>>;
true ->
[<<1:1>>,
align|encode_unconstrained_number(Enc15@element)]
end
end,
begin
%% attribute days(4) with type INTEGER
Enc18@element = element(5, Val),
if Enc18@element =:= asn1_NOVALUE ->
[];
Enc18@element bsr 5 =:= 0 ->
<<0:1,Enc18@element:5>>;
true ->
[<<1:1>>,
align|encode_unconstrained_number(Enc18@element)]
end
end,
begin
%% attribute hours(5) with type INTEGER
Enc21@element = element(6, Val),
if Enc21@element =:= asn1_NOVALUE ->
[];
Enc21@element bsr 5 =:= 0 ->
<<0:1,Enc21@element:5>>;
true ->
[<<1:1>>,
align|encode_unconstrained_number(Enc21@element)]
end
end,
begin
%% attribute minutes(6) with type INTEGER
Enc24@element = element(7, Val),
if Enc24@element =:= asn1_NOVALUE ->
[];
Enc24@element bsr 6 =:= 0 ->
<<0:1,Enc24@element:6>>;
true ->
[<<1:1>>,
align|encode_unconstrained_number(Enc24@element)]
end
end,
begin
%% attribute seconds(7) with type INTEGER
Enc27@element = element(8, Val),
if Enc27@element =:= asn1_NOVALUE ->
[];
Enc27@element bsr 6 =:= 0 ->
<<0:1,Enc27@element:6>>;
true ->
[<<1:1>>,
align|encode_unconstrained_number(Enc27@element)]
end
end|begin
%% attribute fractional-part(8) with type SEQUENCE
Enc30@element = element(9, Val),
if Enc30@element =:= asn1_NOVALUE ->
[];
true ->
'enc_DURATION-INTERVAL-ENCODING_fractional-part'(Enc30@element)
end
end].
'enc_DURATION-INTERVAL-ENCODING_fractional-part'(Val) ->
[begin
%% attribute number-of-digits(1) with type INTEGER
Enc1@element = element(2, Val),
Enc1@element@sub = Enc1@element - 1,
if 0 =< Enc1@element@sub, Enc1@element@sub < 3 ->
<<0:1,Enc1@element@sub:2>>;
true ->
[<<1:1>>,
align|encode_unconstrained_number(Enc1@element)]
end
end|begin
%% attribute fractional-value(2) with type INTEGER
Enc3@element = element(3, Val),
if 0 =< Enc3@element, Enc3@element < 1000 ->
[<<0:1>>,
align|<<Enc3@element:16>>];
true ->
[<<1:1>>,
align|encode_unconstrained_number(Enc3@element)]
end
end].


'dec_DURATION-INTERVAL-ENCODING'(Bytes) ->
{Opt,Bytes1} = begin
<<V1@V0:8,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute years(1) with type INTEGER
{Term1,Bytes2} = case (Opt bsr 7) band 1 of
1 ->
begin
{V2@V0,V2@Buf1} = case Bytes1 of
<<0:1,V2@V3:5/unsigned-unit:1,V2@Buf4/bitstring>> ->
{V2@V3,V2@Buf4};
<<1:1,V2@Buf2/bitstring>> ->
V2@Pad6 = bit_size(V2@Buf2) band 7,
{V2@V3,V2@Buf4} = case V2@Buf2 of
<<_:V2@Pad6,0:1,V2@V8:7,V2@Buf9/bitstring>> when V2@V8 =/= 0 ->
{V2@V8,V2@Buf9};
<<_:V2@Pad6,1:1,0:1,V2@V9:14,V2@Buf10/bitstring>> when V2@V9 =/= 0 ->
{V2@V9,V2@Buf10}
end,
<<V2@V11:V2@V3/signed-unit:8,V2@Buf12/bitstring>> = V2@Buf4,
{V2@V11,V2@Buf12}
end,
{V2@V0,V2@Buf1}
end;
0 ->
{asn1_NOVALUE,Bytes1}
end,

%% attribute months(2) with type INTEGER
{Term2,Bytes3} = case (Opt bsr 6) band 1 of
1 ->
begin
{V3@V0,V3@Buf1} = case Bytes2 of
<<0:1,V3@V3:4/unsigned-unit:1,V3@Buf4/bitstring>> ->
{V3@V3,V3@Buf4};
<<1:1,V3@Buf2/bitstring>> ->
V3@Pad6 = bit_size(V3@Buf2) band 7,
{V3@V3,V3@Buf4} = case V3@Buf2 of
<<_:V3@Pad6,0:1,V3@V8:7,V3@Buf9/bitstring>> when V3@V8 =/= 0 ->
{V3@V8,V3@Buf9};
<<_:V3@Pad6,1:1,0:1,V3@V9:14,V3@Buf10/bitstring>> when V3@V9 =/= 0 ->
{V3@V9,V3@Buf10}
end,
<<V3@V11:V3@V3/signed-unit:8,V3@Buf12/bitstring>> = V3@Buf4,
{V3@V11,V3@Buf12}
end,
{V3@V0,V3@Buf1}
end;
0 ->
{asn1_NOVALUE,Bytes2}
end,

%% attribute weeks(3) with type INTEGER
{Term3,Bytes4} = case (Opt bsr 5) band 1 of
1 ->
begin
{V4@V0,V4@Buf1} = case Bytes3 of
<<0:1,V4@V3:6/unsigned-unit:1,V4@Buf4/bitstring>> ->
{V4@V3,V4@Buf4};
<<1:1,V4@Buf2/bitstring>> ->
V4@Pad6 = bit_size(V4@Buf2) band 7,
{V4@V3,V4@Buf4} = case V4@Buf2 of
<<_:V4@Pad6,0:1,V4@V8:7,V4@Buf9/bitstring>> when V4@V8 =/= 0 ->
{V4@V8,V4@Buf9};
<<_:V4@Pad6,1:1,0:1,V4@V9:14,V4@Buf10/bitstring>> when V4@V9 =/= 0 ->
{V4@V9,V4@Buf10}
end,
<<V4@V11:V4@V3/signed-unit:8,V4@Buf12/bitstring>> = V4@Buf4,
{V4@V11,V4@Buf12}
end,
{V4@V0,V4@Buf1}
end;
0 ->
{asn1_NOVALUE,Bytes3}
end,

%% attribute days(4) with type INTEGER
{Term4,Bytes5} = case (Opt bsr 4) band 1 of
1 ->
begin
{V5@V0,V5@Buf1} = case Bytes4 of
<<0:1,V5@V3:5/unsigned-unit:1,V5@Buf4/bitstring>> ->
{V5@V3,V5@Buf4};
<<1:1,V5@Buf2/bitstring>> ->
V5@Pad6 = bit_size(V5@Buf2) band 7,
{V5@V3,V5@Buf4} = case V5@Buf2 of
<<_:V5@Pad6,0:1,V5@V8:7,V5@Buf9/bitstring>> when V5@V8 =/= 0 ->
{V5@V8,V5@Buf9};
<<_:V5@Pad6,1:1,0:1,V5@V9:14,V5@Buf10/bitstring>> when V5@V9 =/= 0 ->
{V5@V9,V5@Buf10}
end,
<<V5@V11:V5@V3/signed-unit:8,V5@Buf12/bitstring>> = V5@Buf4,
{V5@V11,V5@Buf12}
end,
{V5@V0,V5@Buf1}
end;
0 ->
{asn1_NOVALUE,Bytes4}
end,

%% attribute hours(5) with type INTEGER
{Term5,Bytes6} = case (Opt bsr 3) band 1 of
1 ->
begin
{V6@V0,V6@Buf1} = case Bytes5 of
<<0:1,V6@V3:5/unsigned-unit:1,V6@Buf4/bitstring>> ->
{V6@V3,V6@Buf4};
<<1:1,V6@Buf2/bitstring>> ->
V6@Pad6 = bit_size(V6@Buf2) band 7,
{V6@V3,V6@Buf4} = case V6@Buf2 of
<<_:V6@Pad6,0:1,V6@V8:7,V6@Buf9/bitstring>> when V6@V8 =/= 0 ->
{V6@V8,V6@Buf9};
<<_:V6@Pad6,1:1,0:1,V6@V9:14,V6@Buf10/bitstring>> when V6@V9 =/= 0 ->
{V6@V9,V6@Buf10}
end,
<<V6@V11:V6@V3/signed-unit:8,V6@Buf12/bitstring>> = V6@Buf4,
{V6@V11,V6@Buf12}
end,
{V6@V0,V6@Buf1}
end;
0 ->
{asn1_NOVALUE,Bytes5}
end,

%% attribute minutes(6) with type INTEGER
{Term6,Bytes7} = case (Opt bsr 2) band 1 of
1 ->
begin
{V7@V0,V7@Buf1} = case Bytes6 of
<<0:1,V7@V3:6/unsigned-unit:1,V7@Buf4/bitstring>> ->
{V7@V3,V7@Buf4};
<<1:1,V7@Buf2/bitstring>> ->
V7@Pad6 = bit_size(V7@Buf2) band 7,
{V7@V3,V7@Buf4} = case V7@Buf2 of
<<_:V7@Pad6,0:1,V7@V8:7,V7@Buf9/bitstring>> when V7@V8 =/= 0 ->
{V7@V8,V7@Buf9};
<<_:V7@Pad6,1:1,0:1,V7@V9:14,V7@Buf10/bitstring>> when V7@V9 =/= 0 ->
{V7@V9,V7@Buf10}
end,
<<V7@V11:V7@V3/signed-unit:8,V7@Buf12/bitstring>> = V7@Buf4,
{V7@V11,V7@Buf12}
end,
{V7@V0,V7@Buf1}
end;
0 ->
{asn1_NOVALUE,Bytes6}
end,

%% attribute seconds(7) with type INTEGER
{Term7,Bytes8} = case (Opt bsr 1) band 1 of
1 ->
begin
{V8@V0,V8@Buf1} = case Bytes7 of
<<0:1,V8@V3:6/unsigned-unit:1,V8@Buf4/bitstring>> ->
{V8@V3,V8@Buf4};
<<1:1,V8@Buf2/bitstring>> ->
V8@Pad6 = bit_size(V8@Buf2) band 7,
{V8@V3,V8@Buf4} = case V8@Buf2 of
<<_:V8@Pad6,0:1,V8@V8:7,V8@Buf9/bitstring>> when V8@V8 =/= 0 ->
{V8@V8,V8@Buf9};
<<_:V8@Pad6,1:1,0:1,V8@V9:14,V8@Buf10/bitstring>> when V8@V9 =/= 0 ->
{V8@V9,V8@Buf10}
end,
<<V8@V11:V8@V3/signed-unit:8,V8@Buf12/bitstring>> = V8@Buf4,
{V8@V11,V8@Buf12}
end,
{V8@V0,V8@Buf1}
end;
0 ->
{asn1_NOVALUE,Bytes7}
end,

%% attribute fractional-part(8) with type SEQUENCE
{Term8,Bytes9} = case Opt band 1 of
1 ->
'dec_DURATION-INTERVAL-ENCODING_fractional-part'(Bytes8);
0 ->
{asn1_NOVALUE,Bytes8}
end,
Res1 = {'DURATION-INTERVAL-ENCODING',Term1,Term2,Term3,Term4,Term5,Term6,Term7,Term8},
{Res1,Bytes9}.


'dec_DURATION-INTERVAL-ENCODING_fractional-part'(Bytes) ->

%% attribute number-of-digits(1) with type INTEGER
{Term1,Bytes1} = begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:2/unsigned-unit:1,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + 1,
{V1@Add5,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@Buf9/bitstring>> when V1@V8 =/= 0 ->
{V1@V8,V1@Buf9};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@Buf10/bitstring>> when V1@V9 =/= 0 ->
{V1@V9,V1@Buf10}
end,
<<V1@V11:V1@V3/signed-unit:8,V1@Buf12/bitstring>> = V1@Buf4,
{V1@V11,V1@Buf12}
end,
{V1@V0,V1@Buf1}
end,

%% attribute fractional-value(2) with type INTEGER
{Term2,Bytes2} = begin
{V2@V0,V2@Buf1} = case Bytes1 of
<<0:1,V2@Buf2/bitstring>> ->
V2@Pad5 = bit_size(V2@Buf2) band 7,
<<_:V2@Pad5,V2@V3:2/unsigned-unit:8,V2@Buf4/bitstring>> = V2@Buf2,
{V2@V3,V2@Buf4};
<<1:1,V2@Buf2/bitstring>> ->
V2@Pad6 = bit_size(V2@Buf2) band 7,
{V2@V3,V2@Buf4} = case V2@Buf2 of
<<_:V2@Pad6,0:1,V2@V8:7,V2@Buf9/bitstring>> when V2@V8 =/= 0 ->
{V2@V8,V2@Buf9};
<<_:V2@Pad6,1:1,0:1,V2@V9:14,V2@Buf10/bitstring>> when V2@V9 =/= 0 ->
{V2@V9,V2@Buf10}
end,
<<V2@V11:V2@V3/signed-unit:8,V2@Buf12/bitstring>> = V2@Buf4,
{V2@V11,V2@Buf12}
end,
{V2@V0,V2@Buf1}
end,
Res1 = {'DURATION-INTERVAL-ENCODING_fractional-part',Term1,Term2},
{Res1,Bytes2}.

'enc_DURATION-EQUIVALENT'(Val) ->
[begin
Enc1@element = element(2, Val),
Enc2@element = element(3, Val),
if Enc1@element =:= asn1_NOVALUE ->
if Enc2@element =:= asn1_NOVALUE ->
<<0:1,0:1>>;
true ->
<<0:1,1:1>>
end;
true ->
if Enc2@element =:= asn1_NOVALUE ->
<<1:1,0:1>>;
true ->
<<1:1,1:1>>
end
end
end,
begin
Enc3@element = element(4, Val),
Enc4@element = element(5, Val),
if Enc3@element =:= asn1_NOVALUE ->
if Enc4@element =:= asn1_NOVALUE ->
<<0:1,0:1>>;
true ->
<<0:1,1:1>>
end;
true ->
if Enc4@element =:= asn1_NOVALUE ->
<<1:1,0:1>>;
true ->
<<1:1,1:1>>
end
end
end,
begin
Enc5@element = element(6, Val),
Enc6@element = element(7, Val),
if Enc5@element =:= asn1_NOVALUE ->
if Enc6@element =:= asn1_NOVALUE ->
<<0:1,0:1>>;
true ->
<<0:1,1:1>>
end;
true ->
if Enc6@element =:= asn1_NOVALUE ->
<<1:1,0:1>>;
true ->
<<1:1,1:1>>
end
end
end,
begin
Enc7@element = element(8, Val),
Enc8@element = element(9, Val),
if Enc7@element =:= asn1_NOVALUE ->
if Enc8@element =:= asn1_NOVALUE ->
<<0:1,0:1>>;
true ->
<<0:1,1:1>>
end;
true ->
if Enc8@element =:= asn1_NOVALUE ->
<<1:1,0:1>>;
true ->
<<1:1,1:1>>
end
end
end,
begin
%% attribute years(1) with type INTEGER
Enc9@element = element(2, Val),
if Enc9@element =:= asn1_NOVALUE ->
[];
Enc9@element >= 0 ->
begin
Enc9@element@bin = binary:encode_unsigned(Enc9@element),
Enc9@element@bin_size = byte_size(Enc9@element@bin),
if Enc9@element@bin_size < 128 ->
[align,
Enc9@element@bin_size|Enc9@element@bin];
Enc9@element@bin_size < 16384 ->
[align,
<<2:2,Enc9@element@bin_size:14>>|Enc9@element@bin];
true ->
[align|encode_fragmented(Enc9@element@bin, 8)]
end
end;
true ->
exit({error,{asn1,{illegal_integer,Enc9@element}}})
end
end,
begin
%% attribute months(2) with type INTEGER
Enc12@element = element(3, Val),
if Enc12@element =:= asn1_NOVALUE ->
[];
Enc12@element >= 0 ->
begin
Enc12@element@bin = binary:encode_unsigned(Enc12@element),
Enc12@element@bin_size = byte_size(Enc12@element@bin),
if Enc12@element@bin_size < 128 ->
[align,
Enc12@element@bin_size|Enc12@element@bin];
Enc12@element@bin_size < 16384 ->
[align,
<<2:2,Enc12@element@bin_size:14>>|Enc12@element@bin];
true ->
[align|encode_fragmented(Enc12@element@bin, 8)]
end
end;
true ->
exit({error,{asn1,{illegal_integer,Enc12@element}}})
end
end,
begin
%% attribute weeks(3) with type INTEGER
Enc15@element = element(4, Val),
if Enc15@element =:= asn1_NOVALUE ->
[];
Enc15@element >= 0 ->
begin
Enc15@element@bin = binary:encode_unsigned(Enc15@element),
Enc15@element@bin_size = byte_size(Enc15@element@bin),
if Enc15@element@bin_size < 128 ->
[align,
Enc15@element@bin_size|Enc15@element@bin];
Enc15@element@bin_size < 16384 ->
[align,
<<2:2,Enc15@element@bin_size:14>>|Enc15@element@bin];
true ->
[align|encode_fragmented(Enc15@element@bin, 8)]
end
end;
true ->
exit({error,{asn1,{illegal_integer,Enc15@element}}})
end
end,
begin
%% attribute days(4) with type INTEGER
Enc18@element = element(5, Val),
if Enc18@element =:= asn1_NOVALUE ->
[];
Enc18@element >= 0 ->
begin
Enc18@element@bin = binary:encode_unsigned(Enc18@element),
Enc18@element@bin_size = byte_size(Enc18@element@bin),
if Enc18@element@bin_size < 128 ->
[align,
Enc18@element@bin_size|Enc18@element@bin];
Enc18@element@bin_size < 16384 ->
[align,
<<2:2,Enc18@element@bin_size:14>>|Enc18@element@bin];
true ->
[align|encode_fragmented(Enc18@element@bin, 8)]
end
end;
true ->
exit({error,{asn1,{illegal_integer,Enc18@element}}})
end
end,
begin
%% attribute hours(5) with type INTEGER
Enc21@element = element(6, Val),
if Enc21@element =:= asn1_NOVALUE ->
[];
Enc21@element >= 0 ->
begin
Enc21@element@bin = binary:encode_unsigned(Enc21@element),
Enc21@element@bin_size = byte_size(Enc21@element@bin),
if Enc21@element@bin_size < 128 ->
[align,
Enc21@element@bin_size|Enc21@element@bin];
Enc21@element@bin_size < 16384 ->
[align,
<<2:2,Enc21@element@bin_size:14>>|Enc21@element@bin];
true ->
[align|encode_fragmented(Enc21@element@bin, 8)]
end
end;
true ->
exit({error,{asn1,{illegal_integer,Enc21@element}}})
end
end,
begin
%% attribute minutes(6) with type INTEGER
Enc24@element = element(7, Val),
if Enc24@element =:= asn1_NOVALUE ->
[];
Enc24@element >= 0 ->
begin
Enc24@element@bin = binary:encode_unsigned(Enc24@element),
Enc24@element@bin_size = byte_size(Enc24@element@bin),
if Enc24@element@bin_size < 128 ->
[align,
Enc24@element@bin_size|Enc24@element@bin];
Enc24@element@bin_size < 16384 ->
[align,
<<2:2,Enc24@element@bin_size:14>>|Enc24@element@bin];
true ->
[align|encode_fragmented(Enc24@element@bin, 8)]
end
end;
true ->
exit({error,{asn1,{illegal_integer,Enc24@element}}})
end
end,
begin
%% attribute seconds(7) with type INTEGER
Enc27@element = element(8, Val),
if Enc27@element =:= asn1_NOVALUE ->
[];
Enc27@element >= 0 ->
begin
Enc27@element@bin = binary:encode_unsigned(Enc27@element),
Enc27@element@bin_size = byte_size(Enc27@element@bin),
if Enc27@element@bin_size < 128 ->
[align,
Enc27@element@bin_size|Enc27@element@bin];
Enc27@element@bin_size < 16384 ->
[align,
<<2:2,Enc27@element@bin_size:14>>|Enc27@element@bin];
true ->
[align|encode_fragmented(Enc27@element@bin, 8)]
end
end;
true ->
exit({error,{asn1,{illegal_integer,Enc27@element}}})
end
end|begin
%% attribute fractional-part(8) with type SEQUENCE
Enc30@element = element(9, Val),
if Enc30@element =:= asn1_NOVALUE ->
[];
true ->
'enc_DURATION-EQUIVALENT_fractional-part'(Enc30@element)
end
end].
'enc_DURATION-EQUIVALENT_fractional-part'(Val) ->
[align,
begin
%% attribute number-of-digits(1) with type INTEGER
Enc1@element = element(2, Val),
Enc1@element@sub = Enc1@element - 1,
if Enc1@element@sub >= 0 ->
begin
Enc1@element@sub@bin = binary:encode_unsigned(Enc1@element@sub),
Enc1@element@sub@bin_size = byte_size(Enc1@element@sub@bin),
if Enc1@element@sub@bin_size < 128 ->
[Enc1@element@sub@bin_size|Enc1@element@sub@bin];
Enc1@element@sub@bin_size < 16384 ->
[<<2:2,Enc1@element@sub@bin_size:14>>|Enc1@element@sub@bin];
true ->
encode_fragmented(Enc1@element@sub@bin, 8)
end
end;
true ->
exit({error,{asn1,{illegal_integer,Enc1@element}}})
end
end|begin
%% attribute fractional-value(2) with type INTEGER
Enc3@element = element(3, Val),
if Enc3@element >= 0 ->
begin
Enc3@element@bin = binary:encode_unsigned(Enc3@element),
Enc3@element@bin_size = byte_size(Enc3@element@bin),
if Enc3@element@bin_size < 128 ->
[Enc3@element@bin_size|Enc3@element@bin];
Enc3@element@bin_size < 16384 ->
[<<2:2,Enc3@element@bin_size:14>>|Enc3@element@bin];
true ->
encode_fragmented(Enc3@element@bin, 8)
end
end;
true ->
exit({error,{asn1,{illegal_integer,Enc3@element}}})
end
end].


'dec_DURATION-EQUIVALENT'(Bytes) ->
{Opt,Bytes1} = begin
<<V1@V0:8,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,

%% attribute years(1) with type INTEGER
{Term1,Bytes2} = case (Opt bsr 7) band 1 of
1 ->
begin
V2@Pad3 = bit_size(Bytes1) band 7,
{V2@V0,V2@Buf1} = case Bytes1 of
<<_:V2@Pad3,0:1,V2@V5:7,V2@Buf6/bitstring>> when V2@V5 =/= 0 ->
{V2@V5,V2@Buf6};
<<_:V2@Pad3,1:1,0:1,V2@V6:14,V2@Buf7/bitstring>> when V2@V6 =/= 0 ->
{V2@V6,V2@Buf7}
end,
<<V2@V8:V2@V0/unit:8,V2@Buf9/bitstring>> = V2@Buf1,
{V2@V8,V2@Buf9}
end;
0 ->
{asn1_NOVALUE,Bytes1}
end,

%% attribute months(2) with type INTEGER
{Term2,Bytes3} = case (Opt bsr 6) band 1 of
1 ->
begin
V3@Pad3 = bit_size(Bytes2) band 7,
{V3@V0,V3@Buf1} = case Bytes2 of
<<_:V3@Pad3,0:1,V3@V5:7,V3@Buf6/bitstring>> when V3@V5 =/= 0 ->
{V3@V5,V3@Buf6};
<<_:V3@Pad3,1:1,0:1,V3@V6:14,V3@Buf7/bitstring>> when V3@V6 =/= 0 ->
{V3@V6,V3@Buf7}
end,
<<V3@V8:V3@V0/unit:8,V3@Buf9/bitstring>> = V3@Buf1,
{V3@V8,V3@Buf9}
end;
0 ->
{asn1_NOVALUE,Bytes2}
end,

%% attribute weeks(3) with type INTEGER
{Term3,Bytes4} = case (Opt bsr 5) band 1 of
1 ->
begin
V4@Pad3 = bit_size(Bytes3) band 7,
{V4@V0,V4@Buf1} = case Bytes3 of
<<_:V4@Pad3,0:1,V4@V5:7,V4@Buf6/bitstring>> when V4@V5 =/= 0 ->
{V4@V5,V4@Buf6};
<<_:V4@Pad3,1:1,0:1,V4@V6:14,V4@Buf7/bitstring>> when V4@V6 =/= 0 ->
{V4@V6,V4@Buf7}
end,
<<V4@V8:V4@V0/unit:8,V4@Buf9/bitstring>> = V4@Buf1,
{V4@V8,V4@Buf9}
end;
0 ->
{asn1_NOVALUE,Bytes3}
end,

%% attribute days(4) with type INTEGER
{Term4,Bytes5} = case (Opt bsr 4) band 1 of
1 ->
begin
V5@Pad3 = bit_size(Bytes4) band 7,
{V5@V0,V5@Buf1} = case Bytes4 of
<<_:V5@Pad3,0:1,V5@V5:7,V5@Buf6/bitstring>> when V5@V5 =/= 0 ->
{V5@V5,V5@Buf6};
<<_:V5@Pad3,1:1,0:1,V5@V6:14,V5@Buf7/bitstring>> when V5@V6 =/= 0 ->
{V5@V6,V5@Buf7}
end,
<<V5@V8:V5@V0/unit:8,V5@Buf9/bitstring>> = V5@Buf1,
{V5@V8,V5@Buf9}
end;
0 ->
{asn1_NOVALUE,Bytes4}
end,

%% attribute hours(5) with type INTEGER
{Term5,Bytes6} = case (Opt bsr 3) band 1 of
1 ->
begin
V6@Pad3 = bit_size(Bytes5) band 7,
{V6@V0,V6@Buf1} = case Bytes5 of
<<_:V6@Pad3,0:1,V6@V5:7,V6@Buf6/bitstring>> when V6@V5 =/= 0 ->
{V6@V5,V6@Buf6};
<<_:V6@Pad3,1:1,0:1,V6@V6:14,V6@Buf7/bitstring>> when V6@V6 =/= 0 ->
{V6@V6,V6@Buf7}
end,
<<V6@V8:V6@V0/unit:8,V6@Buf9/bitstring>> = V6@Buf1,
{V6@V8,V6@Buf9}
end;
0 ->
{asn1_NOVALUE,Bytes5}
end,

%% attribute minutes(6) with type INTEGER
{Term6,Bytes7} = case (Opt bsr 2) band 1 of
1 ->
begin
V7@Pad3 = bit_size(Bytes6) band 7,
{V7@V0,V7@Buf1} = case Bytes6 of
<<_:V7@Pad3,0:1,V7@V5:7,V7@Buf6/bitstring>> when V7@V5 =/= 0 ->
{V7@V5,V7@Buf6};
<<_:V7@Pad3,1:1,0:1,V7@V6:14,V7@Buf7/bitstring>> when V7@V6 =/= 0 ->
{V7@V6,V7@Buf7}
end,
<<V7@V8:V7@V0/unit:8,V7@Buf9/bitstring>> = V7@Buf1,
{V7@V8,V7@Buf9}
end;
0 ->
{asn1_NOVALUE,Bytes6}
end,

%% attribute seconds(7) with type INTEGER
{Term7,Bytes8} = case (Opt bsr 1) band 1 of
1 ->
begin
V8@Pad3 = bit_size(Bytes7) band 7,
{V8@V0,V8@Buf1} = case Bytes7 of
<<_:V8@Pad3,0:1,V8@V5:7,V8@Buf6/bitstring>> when V8@V5 =/= 0 ->
{V8@V5,V8@Buf6};
<<_:V8@Pad3,1:1,0:1,V8@V6:14,V8@Buf7/bitstring>> when V8@V6 =/= 0 ->
{V8@V6,V8@Buf7}
end,
<<V8@V8:V8@V0/unit:8,V8@Buf9/bitstring>> = V8@Buf1,
{V8@V8,V8@Buf9}
end;
0 ->
{asn1_NOVALUE,Bytes7}
end,

%% attribute fractional-part(8) with type SEQUENCE
{Term8,Bytes9} = case Opt band 1 of
1 ->
'dec_DURATION-EQUIVALENT_fractional-part'(Bytes8);
0 ->
{asn1_NOVALUE,Bytes8}
end,
Res1 = {'DURATION-EQUIVALENT',Term1,Term2,Term3,Term4,Term5,Term6,Term7,Term8},
{Res1,Bytes9}.


'dec_DURATION-EQUIVALENT_fractional-part'(Bytes) ->

%% attribute number-of-digits(1) with type INTEGER
{Term1,Bytes1} = begin
V1@Pad3 = bit_size(Bytes) band 7,
{V1@V0,V1@Buf1} = case Bytes of
<<_:V1@Pad3,0:1,V1@V5:7,V1@Buf6/bitstring>> when V1@V5 =/= 0 ->
{V1@V5,V1@Buf6};
<<_:V1@Pad3,1:1,0:1,V1@V6:14,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7}
end,
<<V1@V8:V1@V0/unit:8,V1@Buf9/bitstring>> = V1@Buf1,
V1@Add10 = V1@V8 + 1,
{V1@Add10,V1@Buf9}
end,

%% attribute fractional-value(2) with type INTEGER
{Term2,Bytes2} = begin
{V2@V0,V2@Buf1} = case Bytes1 of
<<0:1,V2@V3:7,V2@Buf4/bitstring>> when V2@V3 =/= 0 ->
{V2@V3,V2@Buf4};
<<1:1,0:1,V2@V4:14,V2@Buf5/bitstring>> when V2@V4 =/= 0 ->
{V2@V4,V2@Buf5}
end,
<<V2@V6:V2@V0/unit:8,V2@Buf7/bitstring>> = V2@Buf1,
{V2@V6,V2@Buf7}
end,
Res1 = {'DURATION-EQUIVALENT_fractional-part',Term1,Term2},
{Res1,Bytes2}.


%%%
%%% Run-time functions.
%%%

'dialyzer-suppressions'(Arg) ->
    complete(element(1, Arg)),
    ok.

complete(L0) ->
    L = complete(L0, []),
    case list_to_bitstring(L) of
        <<>> ->
            <<0>>;
        Bin ->
            Bin
    end.

complete([], Bits, []) ->
    case Bits band 7 of
        0 ->
            [];
        N ->
            [<<0:(8 - N)>>]
    end;
complete([], Bits, [H | More]) ->
    complete(H, Bits, More);
complete([align | T], Bits, More) ->
    case Bits band 7 of
        0 ->
            complete(T, More);
        1 ->
            [<<0:7>> | complete(T, More)];
        2 ->
            [<<0:6>> | complete(T, More)];
        3 ->
            [<<0:5>> | complete(T, More)];
        4 ->
            [<<0:4>> | complete(T, More)];
        5 ->
            [<<0:3>> | complete(T, More)];
        6 ->
            [<<0:2>> | complete(T, More)];
        7 ->
            [<<0:1>> | complete(T, More)]
    end;
complete([[] | T], Bits, More) ->
    complete(T, Bits, More);
complete([[_ | _] = H], Bits, More) ->
    complete(H, Bits, More);
complete([[_ | _] = H | T], Bits, More) ->
    complete(H, Bits, [T | More]);
complete([H | T], Bits, More) when is_integer(H); is_binary(H) ->
    [H | complete(T, Bits, More)];
complete([H | T], Bits, More) ->
    [H | complete(T, Bits + bit_size(H), More)];
complete(Bin, Bits, More) when is_binary(Bin) ->
    [Bin | complete([], Bits, More)];
complete(Bin, Bits, More) ->
    [Bin | complete([], Bits + bit_size(Bin), More)].

complete([], []) ->
    [];
complete([], [H | More]) ->
    complete(H, More);
complete([align | T], More) ->
    complete(T, More);
complete([[] | T], More) ->
    complete(T, More);
complete([[_ | _] = H], More) ->
    complete(H, More);
complete([[_ | _] = H | T], More) ->
    complete(H, [T | More]);
complete([H | T], More) when is_integer(H); is_binary(H) ->
    [H | complete(T, More)];
complete([H | T], More) ->
    [H | complete(T, bit_size(H), More)];
complete(Bin, More) when is_binary(Bin) ->
    [Bin | complete([], More)];
complete(Bin, More) ->
    [Bin | complete([], bit_size(Bin), More)].

encode_fragmented(Bin, Unit) ->
    encode_fragmented_1(Bin, Unit, 4).

encode_fragmented_1(Bin, Unit, N) ->
    SegSz = Unit * N * 16384,
    case Bin of
        <<B:SegSz/bitstring,T/bitstring>> ->
            [<<3:2,N:6>>, B | encode_fragmented_1(T, Unit, N)];
        _ when N > 1 ->
            encode_fragmented_1(Bin, Unit, N - 1);
        _ ->
            case bit_size(Bin) div Unit of
                Len when Len < 128 ->
                    [Len, Bin];
                Len when Len < 16384 ->
                    [<<2:2,Len:14>>, Bin]
            end
    end.

encode_unconstrained_number(Val) when not is_integer(Val) ->
    exit({error, {asn1, {illegal_integer, Val}}});
encode_unconstrained_number(Val) when Val >= 0 ->
    if
        Val < 128 ->
            [1, Val];
        Val < 256 ->
            [<<2,0>>, Val];
        true ->
            case binary:encode_unsigned(Val) of
                <<0:1,_/bitstring>> = Bin ->
                    case byte_size(Bin) of
                        Sz when Sz < 128 ->
                            [Sz, Bin];
                        Sz when Sz < 16384 ->
                            [<<2:2,Sz:14>>, Bin]
                    end;
                <<1:1,_/bitstring>> = Bin ->
                    case byte_size(Bin) + 1 of
                        Sz when Sz < 128 ->
                            [Sz, 0, Bin];
                        Sz when Sz < 16384 ->
                            [<<2:2,Sz:14,0:8>>, Bin]
                    end
            end
    end;
encode_unconstrained_number(Val) ->
    Oct = enint(Val, []),
    Len = length(Oct),
    if
        Len < 128 ->
            [Len | Oct];
        Len < 16384 ->
            [<<2:2,Len:14>> | Oct]
    end.

enint(- 1, [B1 | T]) when B1 > 127 ->
    [B1 | T];
enint(N, Acc) ->
    enint(N bsr 8, [N band 255 | Acc]).
