%% Generated by the Erlang ASN.1 compiler. Version: 5.0.17
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module TIME-DIFFERENCE.

-ifndef(_TIME_DIFFERENCE_HRL_).
-define(_TIME_DIFFERENCE_HRL_, true).

-record('TIME-DIFFERENCE', {
  sign,
  hours,
  minutes = asn1_NOVALUE
}).

-record('HOURS-AND-DIFF-ENCODING', {
  'local-hours',
  'time-difference'
}).

-record('MINUTES-ENCODING', {
  hours,
  minutes
}).

-record('MINUTES-UTC-ENCODING', {
  hours,
  minutes
}).

-record('MINUTES-AND-DIFF-ENCODING', {
  'local-time',
  'time-difference'
}).

-record('MINUTES-AND-DIFF-ENCODING_local-time', {
  hours,
  minutes
}).

-record('TIME-OF-DAY-ENCODING', {
  hours,
  minutes,
  seconds
}).

-record('TIME-OF-DAY-UTC-ENCODING', {
  hours,
  minutes,
  seconds
}).

-record('TIME-OF-DAY-AND-DIFF-ENCODING', {
  'local-time',
  'time-difference'
}).

-record('TIME-OF-DAY-AND-DIFF-ENCODING_local-time', {
  hours,
  minutes,
  seconds
}).

-record('HOURS-AND-FRACTION-ENCODING', {
  hours,
  fraction
}).

-record('HOURS-UTC-AND-FRACTION-ENCODING', {
  hours,
  fraction
}).

-record('HOURS-AND-DIFF-AND-FRACTION-ENCODING', {
  'local-hours',
  fraction,
  'time-difference'
}).

-record('MINUTES-AND-FRACTION-ENCODING', {
  hours,
  minutes,
  fraction
}).

-record('MINUTES-UTC-AND-FRACTION-ENCODING', {
  hours,
  minutes,
  fraction
}).

-record('MINUTES-AND-DIFF-AND-FRACTION-ENCODING', {
  'local-time',
  'time-difference'
}).

-record('MINUTES-AND-DIFF-AND-FRACTION-ENCODING_local-time', {
  hours,
  minutes,
  fraction
}).

-record('TIME-OF-DAY-AND-FRACTION-ENCODING', {
  hours,
  minutes,
  seconds,
  fraction
}).

-record('TIME-OF-DAY-UTC-AND-FRACTION-ENCODING', {
  hours,
  minutes,
  seconds,
  fraction
}).

-record('TIME-OF-DAY-AND-DIFF-AND-FRACTION-ENCODING', {
  'local-time',
  'time-difference'
}).

-record('TIME-OF-DAY-AND-DIFF-AND-FRACTION-ENCODING_local-time', {
  hours,
  minutes,
  seconds,
  fraction
}).

-record('DURATION-INTERVAL-ENCODING', {
  years = asn1_NOVALUE,
  months = asn1_NOVALUE,
  weeks = asn1_NOVALUE,
  days = asn1_NOVALUE,
  hours = asn1_NOVALUE,
  minutes = asn1_NOVALUE,
  seconds = asn1_NOVALUE,
  'fractional-part' = asn1_NOVALUE
}).

-record('DURATION-INTERVAL-ENCODING_fractional-part', {
  'number-of-digits',
  'fractional-value'
}).

-record('DURATION-EQUIVALENT', {
  years = asn1_NOVALUE,
  months = asn1_NOVALUE,
  weeks = asn1_NOVALUE,
  days = asn1_NOVALUE,
  hours = asn1_NOVALUE,
  minutes = asn1_NOVALUE,
  seconds = asn1_NOVALUE,
  'fractional-part' = asn1_NOVALUE
}).

-record('DURATION-EQUIVALENT_fractional-part', {
  'number-of-digits',
  'fractional-value'
}).

-endif. %% _TIME_DIFFERENCE_HRL_
