%% Generated by the Erlang ASN.1 compiler. Version: 5.0.17
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module YEAR.

-ifndef(_YEAR_HRL_).
-define(_YEAR_HRL_, true).

-record('YEAR-MONTH-ENCODING', {
  year,
  month
}).

-record('DATE-ENCODING', {
  year,
  month,
  day
}).

-endif. %% _YEAR_HRL_
