%% Generated by the Erlang ASN.1 PER (unaligned) compiler. Version: 5.0.21.1
%% Purpose: Encoding and decoding of the types in INTEGERS.

-module('INTEGERS').
-compile(nowarn_unused_vars).
-dialyzer(no_improper_lists).
-dialyzer(no_match).
-asn1_info([{vsn,'5.0.21.1'},
            {module,'INTEGERS'},
            {options,[{i,"/home/sandeep/Workspace/Github/asn1c-go/lib/per/testing/erlang/uper"},
 {outdir,"/home/sandeep/Workspace/Github/asn1c-go/lib/per/testing/erlang/uper"},
 uper,
 {i,"."}]}]).

-export([encoding_rule/0,maps/0,bit_string_format/0,
         legacy_erlang_types/0]).
-export(['dialyzer-suppressions'/1]).
-export([
'enc_INTEGER-NULL-NULL-FALSE'/1,
'enc_INTEGER-0-NULL-FALSE'/1,
'enc_INTEGER-10-NULL-FALSE'/1,
'enc_INTEGER-20-NULL-FALSE'/1,
'enc_INTEGER-100-NULL-FALSE'/1,
'enc_INTEGER-N10-NULL-FALSE'/1,
'enc_INTEGER-N100-NULL-FALSE'/1,
'enc_INTEGER-N200-NULL-FALSE'/1,
'enc_INTEGER-0-NULL-TRUE'/1,
'enc_INTEGER-10-NULL-TRUE'/1,
'enc_INTEGER-20-NULL-TRUE'/1,
'enc_INTEGER-N100-NULL-TRUE'/1,
'enc_INTEGER-0-1-FALSE'/1,
'enc_INTEGER-0-2-FALSE'/1,
'enc_INTEGER-0-4-FALSE'/1,
'enc_INTEGER-0-8-FALSE'/1,
'enc_INTEGER-0-16-FALSE'/1,
'enc_INTEGER-0-32-FALSE'/1,
'enc_INTEGER-0-64-FALSE'/1,
'enc_INTEGER-0-99-FALSE'/1,
'enc_INTEGER-0-100-FALSE'/1,
'enc_INTEGER-0-127-FALSE'/1,
'enc_INTEGER-0-128-FALSE'/1,
'enc_INTEGER-0-200-FALSE'/1,
'enc_INTEGER-0-253-FALSE'/1,
'enc_INTEGER-0-254-FALSE'/1,
'enc_INTEGER-0-255-FALSE'/1,
'enc_INTEGER-0-256-FALSE'/1,
'enc_INTEGER-0-257-FALSE'/1,
'enc_INTEGER-0-511-FALSE'/1,
'enc_INTEGER-0-512-FALSE'/1,
'enc_INTEGER-0-1000-FALSE'/1,
'enc_INTEGER-0-1024-FALSE'/1,
'enc_INTEGER-0-2047-FALSE'/1,
'enc_INTEGER-0-2048-FALSE'/1,
'enc_INTEGER-0-4096-FALSE'/1,
'enc_INTEGER-0-8192-FALSE'/1,
'enc_INTEGER-0-10000-FALSE'/1,
'enc_INTEGER-0-16384-FALSE'/1,
'enc_INTEGER-0-32768-FALSE'/1,
'enc_INTEGER-0-65534-FALSE'/1,
'enc_INTEGER-0-65535-FALSE'/1,
'enc_INTEGER-0-65536-FALSE'/1,
'enc_INTEGER-0-65537-FALSE'/1,
'enc_INTEGER-0-100000-FALSE'/1,
'enc_INTEGER-0-131072-FALSE'/1,
'enc_INTEGER-0-262144-FALSE'/1,
'enc_INTEGER-0-524288-FALSE'/1,
'enc_INTEGER-0-1000000-FALSE'/1,
'enc_INTEGER-0-1048576-FALSE'/1,
'enc_INTEGER-0-2097152-FALSE'/1,
'enc_INTEGER-0-4194304-FALSE'/1,
'enc_INTEGER-0-8388608-FALSE'/1,
'enc_INTEGER-0-16777216-FALSE'/1,
'enc_INTEGER-0-33554432-FALSE'/1,
'enc_INTEGER-0-67108864-FALSE'/1,
'enc_INTEGER-0-134217728-FALSE'/1,
'enc_INTEGER-0-268435456-FALSE'/1,
'enc_INTEGER-10-150-FALSE'/1,
'enc_INTEGER-20-40-FALSE'/1,
'enc_INTEGER-50-100-FALSE'/1,
'enc_INTEGER-50-50-FALSE'/1,
'enc_INTEGER-100-200-FALSE'/1,
'enc_INTEGER-1-1-FALSE'/1,
'enc_INTEGER-1-3-FALSE'/1,
'enc_INTEGER-N200-N10-FALSE'/1,
'enc_INTEGER-N100-100-FALSE'/1,
'enc_INTEGER-N100-N10-FALSE'/1,
'enc_INTEGER-N50-50-FALSE'/1,
'enc_INTEGER-N10-10-FALSE'/1,
'enc_INTEGER-0-1-TRUE'/1,
'enc_INTEGER-0-2-TRUE'/1,
'enc_INTEGER-0-4-TRUE'/1,
'enc_INTEGER-0-8-TRUE'/1,
'enc_INTEGER-0-16-TRUE'/1,
'enc_INTEGER-0-32-TRUE'/1,
'enc_INTEGER-0-64-TRUE'/1,
'enc_INTEGER-0-99-TRUE'/1,
'enc_INTEGER-0-100-TRUE'/1,
'enc_INTEGER-0-128-TRUE'/1,
'enc_INTEGER-0-200-TRUE'/1,
'enc_INTEGER-0-256-TRUE'/1,
'enc_INTEGER-0-257-TRUE'/1,
'enc_INTEGER-0-512-TRUE'/1,
'enc_INTEGER-0-1000-TRUE'/1,
'enc_INTEGER-0-1024-TRUE'/1,
'enc_INTEGER-0-2048-TRUE'/1,
'enc_INTEGER-0-4096-TRUE'/1,
'enc_INTEGER-0-8192-TRUE'/1,
'enc_INTEGER-0-10000-TRUE'/1,
'enc_INTEGER-0-16384-TRUE'/1,
'enc_INTEGER-0-32768-TRUE'/1,
'enc_INTEGER-0-65535-TRUE'/1,
'enc_INTEGER-0-65536-TRUE'/1,
'enc_INTEGER-0-100000-TRUE'/1,
'enc_INTEGER-0-131072-TRUE'/1,
'enc_INTEGER-0-262144-TRUE'/1,
'enc_INTEGER-0-524288-TRUE'/1,
'enc_INTEGER-0-1000000-TRUE'/1,
'enc_INTEGER-0-1048576-TRUE'/1,
'enc_INTEGER-0-2097152-TRUE'/1,
'enc_INTEGER-0-4194304-TRUE'/1,
'enc_INTEGER-0-8388608-TRUE'/1,
'enc_INTEGER-0-16777216-TRUE'/1,
'enc_INTEGER-0-33554432-TRUE'/1,
'enc_INTEGER-0-67108864-TRUE'/1,
'enc_INTEGER-0-134217728-TRUE'/1,
'enc_INTEGER-0-268435456-TRUE'/1,
'enc_INTEGER-10-150-TRUE'/1,
'enc_INTEGER-20-40-TRUE'/1,
'enc_INTEGER-50-100-TRUE'/1,
'enc_INTEGER-50-50-TRUE'/1,
'enc_INTEGER-100-100-TRUE'/1,
'enc_INTEGER-100-200-TRUE'/1,
'enc_INTEGER-1000-1000-TRUE'/1,
'enc_INTEGER-1-1-TRUE'/1,
'enc_INTEGER-1-3-TRUE'/1,
'enc_INTEGER-N500-500-TRUE'/1,
'enc_INTEGER-N200-N10-TRUE'/1,
'enc_INTEGER-N100-100-TRUE'/1,
'enc_INTEGER-N100-N10-TRUE'/1,
'enc_INTEGER-N50-50-TRUE'/1,
'enc_INTEGER-N10-10-TRUE'/1
]).

-export([
'dec_INTEGER-NULL-NULL-FALSE'/1,
'dec_INTEGER-0-NULL-FALSE'/1,
'dec_INTEGER-10-NULL-FALSE'/1,
'dec_INTEGER-20-NULL-FALSE'/1,
'dec_INTEGER-100-NULL-FALSE'/1,
'dec_INTEGER-N10-NULL-FALSE'/1,
'dec_INTEGER-N100-NULL-FALSE'/1,
'dec_INTEGER-N200-NULL-FALSE'/1,
'dec_INTEGER-0-NULL-TRUE'/1,
'dec_INTEGER-10-NULL-TRUE'/1,
'dec_INTEGER-20-NULL-TRUE'/1,
'dec_INTEGER-N100-NULL-TRUE'/1,
'dec_INTEGER-0-1-FALSE'/1,
'dec_INTEGER-0-2-FALSE'/1,
'dec_INTEGER-0-4-FALSE'/1,
'dec_INTEGER-0-8-FALSE'/1,
'dec_INTEGER-0-16-FALSE'/1,
'dec_INTEGER-0-32-FALSE'/1,
'dec_INTEGER-0-64-FALSE'/1,
'dec_INTEGER-0-99-FALSE'/1,
'dec_INTEGER-0-100-FALSE'/1,
'dec_INTEGER-0-127-FALSE'/1,
'dec_INTEGER-0-128-FALSE'/1,
'dec_INTEGER-0-200-FALSE'/1,
'dec_INTEGER-0-253-FALSE'/1,
'dec_INTEGER-0-254-FALSE'/1,
'dec_INTEGER-0-255-FALSE'/1,
'dec_INTEGER-0-256-FALSE'/1,
'dec_INTEGER-0-257-FALSE'/1,
'dec_INTEGER-0-511-FALSE'/1,
'dec_INTEGER-0-512-FALSE'/1,
'dec_INTEGER-0-1000-FALSE'/1,
'dec_INTEGER-0-1024-FALSE'/1,
'dec_INTEGER-0-2047-FALSE'/1,
'dec_INTEGER-0-2048-FALSE'/1,
'dec_INTEGER-0-4096-FALSE'/1,
'dec_INTEGER-0-8192-FALSE'/1,
'dec_INTEGER-0-10000-FALSE'/1,
'dec_INTEGER-0-16384-FALSE'/1,
'dec_INTEGER-0-32768-FALSE'/1,
'dec_INTEGER-0-65534-FALSE'/1,
'dec_INTEGER-0-65535-FALSE'/1,
'dec_INTEGER-0-65536-FALSE'/1,
'dec_INTEGER-0-65537-FALSE'/1,
'dec_INTEGER-0-100000-FALSE'/1,
'dec_INTEGER-0-131072-FALSE'/1,
'dec_INTEGER-0-262144-FALSE'/1,
'dec_INTEGER-0-524288-FALSE'/1,
'dec_INTEGER-0-1000000-FALSE'/1,
'dec_INTEGER-0-1048576-FALSE'/1,
'dec_INTEGER-0-2097152-FALSE'/1,
'dec_INTEGER-0-4194304-FALSE'/1,
'dec_INTEGER-0-8388608-FALSE'/1,
'dec_INTEGER-0-16777216-FALSE'/1,
'dec_INTEGER-0-33554432-FALSE'/1,
'dec_INTEGER-0-67108864-FALSE'/1,
'dec_INTEGER-0-134217728-FALSE'/1,
'dec_INTEGER-0-268435456-FALSE'/1,
'dec_INTEGER-10-150-FALSE'/1,
'dec_INTEGER-20-40-FALSE'/1,
'dec_INTEGER-50-100-FALSE'/1,
'dec_INTEGER-50-50-FALSE'/1,
'dec_INTEGER-100-200-FALSE'/1,
'dec_INTEGER-1-1-FALSE'/1,
'dec_INTEGER-1-3-FALSE'/1,
'dec_INTEGER-N200-N10-FALSE'/1,
'dec_INTEGER-N100-100-FALSE'/1,
'dec_INTEGER-N100-N10-FALSE'/1,
'dec_INTEGER-N50-50-FALSE'/1,
'dec_INTEGER-N10-10-FALSE'/1,
'dec_INTEGER-0-1-TRUE'/1,
'dec_INTEGER-0-2-TRUE'/1,
'dec_INTEGER-0-4-TRUE'/1,
'dec_INTEGER-0-8-TRUE'/1,
'dec_INTEGER-0-16-TRUE'/1,
'dec_INTEGER-0-32-TRUE'/1,
'dec_INTEGER-0-64-TRUE'/1,
'dec_INTEGER-0-99-TRUE'/1,
'dec_INTEGER-0-100-TRUE'/1,
'dec_INTEGER-0-128-TRUE'/1,
'dec_INTEGER-0-200-TRUE'/1,
'dec_INTEGER-0-256-TRUE'/1,
'dec_INTEGER-0-257-TRUE'/1,
'dec_INTEGER-0-512-TRUE'/1,
'dec_INTEGER-0-1000-TRUE'/1,
'dec_INTEGER-0-1024-TRUE'/1,
'dec_INTEGER-0-2048-TRUE'/1,
'dec_INTEGER-0-4096-TRUE'/1,
'dec_INTEGER-0-8192-TRUE'/1,
'dec_INTEGER-0-10000-TRUE'/1,
'dec_INTEGER-0-16384-TRUE'/1,
'dec_INTEGER-0-32768-TRUE'/1,
'dec_INTEGER-0-65535-TRUE'/1,
'dec_INTEGER-0-65536-TRUE'/1,
'dec_INTEGER-0-100000-TRUE'/1,
'dec_INTEGER-0-131072-TRUE'/1,
'dec_INTEGER-0-262144-TRUE'/1,
'dec_INTEGER-0-524288-TRUE'/1,
'dec_INTEGER-0-1000000-TRUE'/1,
'dec_INTEGER-0-1048576-TRUE'/1,
'dec_INTEGER-0-2097152-TRUE'/1,
'dec_INTEGER-0-4194304-TRUE'/1,
'dec_INTEGER-0-8388608-TRUE'/1,
'dec_INTEGER-0-16777216-TRUE'/1,
'dec_INTEGER-0-33554432-TRUE'/1,
'dec_INTEGER-0-67108864-TRUE'/1,
'dec_INTEGER-0-134217728-TRUE'/1,
'dec_INTEGER-0-268435456-TRUE'/1,
'dec_INTEGER-10-150-TRUE'/1,
'dec_INTEGER-20-40-TRUE'/1,
'dec_INTEGER-50-100-TRUE'/1,
'dec_INTEGER-50-50-TRUE'/1,
'dec_INTEGER-100-100-TRUE'/1,
'dec_INTEGER-100-200-TRUE'/1,
'dec_INTEGER-1000-1000-TRUE'/1,
'dec_INTEGER-1-1-TRUE'/1,
'dec_INTEGER-1-3-TRUE'/1,
'dec_INTEGER-N500-500-TRUE'/1,
'dec_INTEGER-N200-N10-TRUE'/1,
'dec_INTEGER-N100-100-TRUE'/1,
'dec_INTEGER-N100-N10-TRUE'/1,
'dec_INTEGER-N50-50-TRUE'/1,
'dec_INTEGER-N10-10-TRUE'/1
]).

-export([info/0]).

-export([encode/2,decode/2]).

encoding_rule() -> uper.

maps() -> false.

bit_string_format() -> bitstring.

legacy_erlang_types() -> false.

encode(Type, Data) ->
try complete(encode_disp(Type, Data)) of
  Bytes ->
    {ok,Bytes}
  catch
    Class:Exception:Stk when Class =:= error; Class =:= exit ->
      case Exception of
        {error,{asn1,Reason}} ->
          {error,{asn1,{Reason,Stk}}};
        Reason ->
         {error,{asn1,{Reason,Stk}}}
      end
end.

decode(Type, Data) ->
try
   {Result,_Rest} = decode_disp(Type, Data),
   {ok,Result}
  catch
    Class:Exception:Stk when Class =:= error; Class =:= exit ->
      case Exception of
        {error,{asn1,Reason}} ->
          {error,{asn1,{Reason,Stk}}};
        Reason ->
         {error,{asn1,{Reason,Stk}}}
      end
end.

encode_disp('INTEGER-NULL-NULL-FALSE', Data) -> 'enc_INTEGER-NULL-NULL-FALSE'(Data);
encode_disp('INTEGER-0-NULL-FALSE', Data) -> 'enc_INTEGER-0-NULL-FALSE'(Data);
encode_disp('INTEGER-10-NULL-FALSE', Data) -> 'enc_INTEGER-10-NULL-FALSE'(Data);
encode_disp('INTEGER-20-NULL-FALSE', Data) -> 'enc_INTEGER-20-NULL-FALSE'(Data);
encode_disp('INTEGER-100-NULL-FALSE', Data) -> 'enc_INTEGER-100-NULL-FALSE'(Data);
encode_disp('INTEGER-N10-NULL-FALSE', Data) -> 'enc_INTEGER-N10-NULL-FALSE'(Data);
encode_disp('INTEGER-N100-NULL-FALSE', Data) -> 'enc_INTEGER-N100-NULL-FALSE'(Data);
encode_disp('INTEGER-N200-NULL-FALSE', Data) -> 'enc_INTEGER-N200-NULL-FALSE'(Data);
encode_disp('INTEGER-0-NULL-TRUE', Data) -> 'enc_INTEGER-0-NULL-TRUE'(Data);
encode_disp('INTEGER-10-NULL-TRUE', Data) -> 'enc_INTEGER-10-NULL-TRUE'(Data);
encode_disp('INTEGER-20-NULL-TRUE', Data) -> 'enc_INTEGER-20-NULL-TRUE'(Data);
encode_disp('INTEGER-N100-NULL-TRUE', Data) -> 'enc_INTEGER-N100-NULL-TRUE'(Data);
encode_disp('INTEGER-0-1-FALSE', Data) -> 'enc_INTEGER-0-1-FALSE'(Data);
encode_disp('INTEGER-0-2-FALSE', Data) -> 'enc_INTEGER-0-2-FALSE'(Data);
encode_disp('INTEGER-0-4-FALSE', Data) -> 'enc_INTEGER-0-4-FALSE'(Data);
encode_disp('INTEGER-0-8-FALSE', Data) -> 'enc_INTEGER-0-8-FALSE'(Data);
encode_disp('INTEGER-0-16-FALSE', Data) -> 'enc_INTEGER-0-16-FALSE'(Data);
encode_disp('INTEGER-0-32-FALSE', Data) -> 'enc_INTEGER-0-32-FALSE'(Data);
encode_disp('INTEGER-0-64-FALSE', Data) -> 'enc_INTEGER-0-64-FALSE'(Data);
encode_disp('INTEGER-0-99-FALSE', Data) -> 'enc_INTEGER-0-99-FALSE'(Data);
encode_disp('INTEGER-0-100-FALSE', Data) -> 'enc_INTEGER-0-100-FALSE'(Data);
encode_disp('INTEGER-0-127-FALSE', Data) -> 'enc_INTEGER-0-127-FALSE'(Data);
encode_disp('INTEGER-0-128-FALSE', Data) -> 'enc_INTEGER-0-128-FALSE'(Data);
encode_disp('INTEGER-0-200-FALSE', Data) -> 'enc_INTEGER-0-200-FALSE'(Data);
encode_disp('INTEGER-0-253-FALSE', Data) -> 'enc_INTEGER-0-253-FALSE'(Data);
encode_disp('INTEGER-0-254-FALSE', Data) -> 'enc_INTEGER-0-254-FALSE'(Data);
encode_disp('INTEGER-0-255-FALSE', Data) -> 'enc_INTEGER-0-255-FALSE'(Data);
encode_disp('INTEGER-0-256-FALSE', Data) -> 'enc_INTEGER-0-256-FALSE'(Data);
encode_disp('INTEGER-0-257-FALSE', Data) -> 'enc_INTEGER-0-257-FALSE'(Data);
encode_disp('INTEGER-0-511-FALSE', Data) -> 'enc_INTEGER-0-511-FALSE'(Data);
encode_disp('INTEGER-0-512-FALSE', Data) -> 'enc_INTEGER-0-512-FALSE'(Data);
encode_disp('INTEGER-0-1000-FALSE', Data) -> 'enc_INTEGER-0-1000-FALSE'(Data);
encode_disp('INTEGER-0-1024-FALSE', Data) -> 'enc_INTEGER-0-1024-FALSE'(Data);
encode_disp('INTEGER-0-2047-FALSE', Data) -> 'enc_INTEGER-0-2047-FALSE'(Data);
encode_disp('INTEGER-0-2048-FALSE', Data) -> 'enc_INTEGER-0-2048-FALSE'(Data);
encode_disp('INTEGER-0-4096-FALSE', Data) -> 'enc_INTEGER-0-4096-FALSE'(Data);
encode_disp('INTEGER-0-8192-FALSE', Data) -> 'enc_INTEGER-0-8192-FALSE'(Data);
encode_disp('INTEGER-0-10000-FALSE', Data) -> 'enc_INTEGER-0-10000-FALSE'(Data);
encode_disp('INTEGER-0-16384-FALSE', Data) -> 'enc_INTEGER-0-16384-FALSE'(Data);
encode_disp('INTEGER-0-32768-FALSE', Data) -> 'enc_INTEGER-0-32768-FALSE'(Data);
encode_disp('INTEGER-0-65534-FALSE', Data) -> 'enc_INTEGER-0-65534-FALSE'(Data);
encode_disp('INTEGER-0-65535-FALSE', Data) -> 'enc_INTEGER-0-65535-FALSE'(Data);
encode_disp('INTEGER-0-65536-FALSE', Data) -> 'enc_INTEGER-0-65536-FALSE'(Data);
encode_disp('INTEGER-0-65537-FALSE', Data) -> 'enc_INTEGER-0-65537-FALSE'(Data);
encode_disp('INTEGER-0-100000-FALSE', Data) -> 'enc_INTEGER-0-100000-FALSE'(Data);
encode_disp('INTEGER-0-131072-FALSE', Data) -> 'enc_INTEGER-0-131072-FALSE'(Data);
encode_disp('INTEGER-0-262144-FALSE', Data) -> 'enc_INTEGER-0-262144-FALSE'(Data);
encode_disp('INTEGER-0-524288-FALSE', Data) -> 'enc_INTEGER-0-524288-FALSE'(Data);
encode_disp('INTEGER-0-1000000-FALSE', Data) -> 'enc_INTEGER-0-1000000-FALSE'(Data);
encode_disp('INTEGER-0-1048576-FALSE', Data) -> 'enc_INTEGER-0-1048576-FALSE'(Data);
encode_disp('INTEGER-0-2097152-FALSE', Data) -> 'enc_INTEGER-0-2097152-FALSE'(Data);
encode_disp('INTEGER-0-4194304-FALSE', Data) -> 'enc_INTEGER-0-4194304-FALSE'(Data);
encode_disp('INTEGER-0-8388608-FALSE', Data) -> 'enc_INTEGER-0-8388608-FALSE'(Data);
encode_disp('INTEGER-0-16777216-FALSE', Data) -> 'enc_INTEGER-0-16777216-FALSE'(Data);
encode_disp('INTEGER-0-33554432-FALSE', Data) -> 'enc_INTEGER-0-33554432-FALSE'(Data);
encode_disp('INTEGER-0-67108864-FALSE', Data) -> 'enc_INTEGER-0-67108864-FALSE'(Data);
encode_disp('INTEGER-0-134217728-FALSE', Data) -> 'enc_INTEGER-0-134217728-FALSE'(Data);
encode_disp('INTEGER-0-268435456-FALSE', Data) -> 'enc_INTEGER-0-268435456-FALSE'(Data);
encode_disp('INTEGER-10-150-FALSE', Data) -> 'enc_INTEGER-10-150-FALSE'(Data);
encode_disp('INTEGER-20-40-FALSE', Data) -> 'enc_INTEGER-20-40-FALSE'(Data);
encode_disp('INTEGER-50-100-FALSE', Data) -> 'enc_INTEGER-50-100-FALSE'(Data);
encode_disp('INTEGER-50-50-FALSE', Data) -> 'enc_INTEGER-50-50-FALSE'(Data);
encode_disp('INTEGER-100-200-FALSE', Data) -> 'enc_INTEGER-100-200-FALSE'(Data);
encode_disp('INTEGER-1-1-FALSE', Data) -> 'enc_INTEGER-1-1-FALSE'(Data);
encode_disp('INTEGER-1-3-FALSE', Data) -> 'enc_INTEGER-1-3-FALSE'(Data);
encode_disp('INTEGER-N200-N10-FALSE', Data) -> 'enc_INTEGER-N200-N10-FALSE'(Data);
encode_disp('INTEGER-N100-100-FALSE', Data) -> 'enc_INTEGER-N100-100-FALSE'(Data);
encode_disp('INTEGER-N100-N10-FALSE', Data) -> 'enc_INTEGER-N100-N10-FALSE'(Data);
encode_disp('INTEGER-N50-50-FALSE', Data) -> 'enc_INTEGER-N50-50-FALSE'(Data);
encode_disp('INTEGER-N10-10-FALSE', Data) -> 'enc_INTEGER-N10-10-FALSE'(Data);
encode_disp('INTEGER-0-1-TRUE', Data) -> 'enc_INTEGER-0-1-TRUE'(Data);
encode_disp('INTEGER-0-2-TRUE', Data) -> 'enc_INTEGER-0-2-TRUE'(Data);
encode_disp('INTEGER-0-4-TRUE', Data) -> 'enc_INTEGER-0-4-TRUE'(Data);
encode_disp('INTEGER-0-8-TRUE', Data) -> 'enc_INTEGER-0-8-TRUE'(Data);
encode_disp('INTEGER-0-16-TRUE', Data) -> 'enc_INTEGER-0-16-TRUE'(Data);
encode_disp('INTEGER-0-32-TRUE', Data) -> 'enc_INTEGER-0-32-TRUE'(Data);
encode_disp('INTEGER-0-64-TRUE', Data) -> 'enc_INTEGER-0-64-TRUE'(Data);
encode_disp('INTEGER-0-99-TRUE', Data) -> 'enc_INTEGER-0-99-TRUE'(Data);
encode_disp('INTEGER-0-100-TRUE', Data) -> 'enc_INTEGER-0-100-TRUE'(Data);
encode_disp('INTEGER-0-128-TRUE', Data) -> 'enc_INTEGER-0-128-TRUE'(Data);
encode_disp('INTEGER-0-200-TRUE', Data) -> 'enc_INTEGER-0-200-TRUE'(Data);
encode_disp('INTEGER-0-256-TRUE', Data) -> 'enc_INTEGER-0-256-TRUE'(Data);
encode_disp('INTEGER-0-257-TRUE', Data) -> 'enc_INTEGER-0-257-TRUE'(Data);
encode_disp('INTEGER-0-512-TRUE', Data) -> 'enc_INTEGER-0-512-TRUE'(Data);
encode_disp('INTEGER-0-1000-TRUE', Data) -> 'enc_INTEGER-0-1000-TRUE'(Data);
encode_disp('INTEGER-0-1024-TRUE', Data) -> 'enc_INTEGER-0-1024-TRUE'(Data);
encode_disp('INTEGER-0-2048-TRUE', Data) -> 'enc_INTEGER-0-2048-TRUE'(Data);
encode_disp('INTEGER-0-4096-TRUE', Data) -> 'enc_INTEGER-0-4096-TRUE'(Data);
encode_disp('INTEGER-0-8192-TRUE', Data) -> 'enc_INTEGER-0-8192-TRUE'(Data);
encode_disp('INTEGER-0-10000-TRUE', Data) -> 'enc_INTEGER-0-10000-TRUE'(Data);
encode_disp('INTEGER-0-16384-TRUE', Data) -> 'enc_INTEGER-0-16384-TRUE'(Data);
encode_disp('INTEGER-0-32768-TRUE', Data) -> 'enc_INTEGER-0-32768-TRUE'(Data);
encode_disp('INTEGER-0-65535-TRUE', Data) -> 'enc_INTEGER-0-65535-TRUE'(Data);
encode_disp('INTEGER-0-65536-TRUE', Data) -> 'enc_INTEGER-0-65536-TRUE'(Data);
encode_disp('INTEGER-0-100000-TRUE', Data) -> 'enc_INTEGER-0-100000-TRUE'(Data);
encode_disp('INTEGER-0-131072-TRUE', Data) -> 'enc_INTEGER-0-131072-TRUE'(Data);
encode_disp('INTEGER-0-262144-TRUE', Data) -> 'enc_INTEGER-0-262144-TRUE'(Data);
encode_disp('INTEGER-0-524288-TRUE', Data) -> 'enc_INTEGER-0-524288-TRUE'(Data);
encode_disp('INTEGER-0-1000000-TRUE', Data) -> 'enc_INTEGER-0-1000000-TRUE'(Data);
encode_disp('INTEGER-0-1048576-TRUE', Data) -> 'enc_INTEGER-0-1048576-TRUE'(Data);
encode_disp('INTEGER-0-2097152-TRUE', Data) -> 'enc_INTEGER-0-2097152-TRUE'(Data);
encode_disp('INTEGER-0-4194304-TRUE', Data) -> 'enc_INTEGER-0-4194304-TRUE'(Data);
encode_disp('INTEGER-0-8388608-TRUE', Data) -> 'enc_INTEGER-0-8388608-TRUE'(Data);
encode_disp('INTEGER-0-16777216-TRUE', Data) -> 'enc_INTEGER-0-16777216-TRUE'(Data);
encode_disp('INTEGER-0-33554432-TRUE', Data) -> 'enc_INTEGER-0-33554432-TRUE'(Data);
encode_disp('INTEGER-0-67108864-TRUE', Data) -> 'enc_INTEGER-0-67108864-TRUE'(Data);
encode_disp('INTEGER-0-134217728-TRUE', Data) -> 'enc_INTEGER-0-134217728-TRUE'(Data);
encode_disp('INTEGER-0-268435456-TRUE', Data) -> 'enc_INTEGER-0-268435456-TRUE'(Data);
encode_disp('INTEGER-10-150-TRUE', Data) -> 'enc_INTEGER-10-150-TRUE'(Data);
encode_disp('INTEGER-20-40-TRUE', Data) -> 'enc_INTEGER-20-40-TRUE'(Data);
encode_disp('INTEGER-50-100-TRUE', Data) -> 'enc_INTEGER-50-100-TRUE'(Data);
encode_disp('INTEGER-50-50-TRUE', Data) -> 'enc_INTEGER-50-50-TRUE'(Data);
encode_disp('INTEGER-100-100-TRUE', Data) -> 'enc_INTEGER-100-100-TRUE'(Data);
encode_disp('INTEGER-100-200-TRUE', Data) -> 'enc_INTEGER-100-200-TRUE'(Data);
encode_disp('INTEGER-1000-1000-TRUE', Data) -> 'enc_INTEGER-1000-1000-TRUE'(Data);
encode_disp('INTEGER-1-1-TRUE', Data) -> 'enc_INTEGER-1-1-TRUE'(Data);
encode_disp('INTEGER-1-3-TRUE', Data) -> 'enc_INTEGER-1-3-TRUE'(Data);
encode_disp('INTEGER-N500-500-TRUE', Data) -> 'enc_INTEGER-N500-500-TRUE'(Data);
encode_disp('INTEGER-N200-N10-TRUE', Data) -> 'enc_INTEGER-N200-N10-TRUE'(Data);
encode_disp('INTEGER-N100-100-TRUE', Data) -> 'enc_INTEGER-N100-100-TRUE'(Data);
encode_disp('INTEGER-N100-N10-TRUE', Data) -> 'enc_INTEGER-N100-N10-TRUE'(Data);
encode_disp('INTEGER-N50-50-TRUE', Data) -> 'enc_INTEGER-N50-50-TRUE'(Data);
encode_disp('INTEGER-N10-10-TRUE', Data) -> 'enc_INTEGER-N10-10-TRUE'(Data);
encode_disp(Type, _Data) -> exit({error,{asn1,{undefined_type,Type}}}).

decode_disp('INTEGER-NULL-NULL-FALSE', Data) -> 'dec_INTEGER-NULL-NULL-FALSE'(Data);
decode_disp('INTEGER-0-NULL-FALSE', Data) -> 'dec_INTEGER-0-NULL-FALSE'(Data);
decode_disp('INTEGER-10-NULL-FALSE', Data) -> 'dec_INTEGER-10-NULL-FALSE'(Data);
decode_disp('INTEGER-20-NULL-FALSE', Data) -> 'dec_INTEGER-20-NULL-FALSE'(Data);
decode_disp('INTEGER-100-NULL-FALSE', Data) -> 'dec_INTEGER-100-NULL-FALSE'(Data);
decode_disp('INTEGER-N10-NULL-FALSE', Data) -> 'dec_INTEGER-N10-NULL-FALSE'(Data);
decode_disp('INTEGER-N100-NULL-FALSE', Data) -> 'dec_INTEGER-N100-NULL-FALSE'(Data);
decode_disp('INTEGER-N200-NULL-FALSE', Data) -> 'dec_INTEGER-N200-NULL-FALSE'(Data);
decode_disp('INTEGER-0-NULL-TRUE', Data) -> 'dec_INTEGER-0-NULL-TRUE'(Data);
decode_disp('INTEGER-10-NULL-TRUE', Data) -> 'dec_INTEGER-10-NULL-TRUE'(Data);
decode_disp('INTEGER-20-NULL-TRUE', Data) -> 'dec_INTEGER-20-NULL-TRUE'(Data);
decode_disp('INTEGER-N100-NULL-TRUE', Data) -> 'dec_INTEGER-N100-NULL-TRUE'(Data);
decode_disp('INTEGER-0-1-FALSE', Data) -> 'dec_INTEGER-0-1-FALSE'(Data);
decode_disp('INTEGER-0-2-FALSE', Data) -> 'dec_INTEGER-0-2-FALSE'(Data);
decode_disp('INTEGER-0-4-FALSE', Data) -> 'dec_INTEGER-0-4-FALSE'(Data);
decode_disp('INTEGER-0-8-FALSE', Data) -> 'dec_INTEGER-0-8-FALSE'(Data);
decode_disp('INTEGER-0-16-FALSE', Data) -> 'dec_INTEGER-0-16-FALSE'(Data);
decode_disp('INTEGER-0-32-FALSE', Data) -> 'dec_INTEGER-0-32-FALSE'(Data);
decode_disp('INTEGER-0-64-FALSE', Data) -> 'dec_INTEGER-0-64-FALSE'(Data);
decode_disp('INTEGER-0-99-FALSE', Data) -> 'dec_INTEGER-0-99-FALSE'(Data);
decode_disp('INTEGER-0-100-FALSE', Data) -> 'dec_INTEGER-0-100-FALSE'(Data);
decode_disp('INTEGER-0-127-FALSE', Data) -> 'dec_INTEGER-0-127-FALSE'(Data);
decode_disp('INTEGER-0-128-FALSE', Data) -> 'dec_INTEGER-0-128-FALSE'(Data);
decode_disp('INTEGER-0-200-FALSE', Data) -> 'dec_INTEGER-0-200-FALSE'(Data);
decode_disp('INTEGER-0-253-FALSE', Data) -> 'dec_INTEGER-0-253-FALSE'(Data);
decode_disp('INTEGER-0-254-FALSE', Data) -> 'dec_INTEGER-0-254-FALSE'(Data);
decode_disp('INTEGER-0-255-FALSE', Data) -> 'dec_INTEGER-0-255-FALSE'(Data);
decode_disp('INTEGER-0-256-FALSE', Data) -> 'dec_INTEGER-0-256-FALSE'(Data);
decode_disp('INTEGER-0-257-FALSE', Data) -> 'dec_INTEGER-0-257-FALSE'(Data);
decode_disp('INTEGER-0-511-FALSE', Data) -> 'dec_INTEGER-0-511-FALSE'(Data);
decode_disp('INTEGER-0-512-FALSE', Data) -> 'dec_INTEGER-0-512-FALSE'(Data);
decode_disp('INTEGER-0-1000-FALSE', Data) -> 'dec_INTEGER-0-1000-FALSE'(Data);
decode_disp('INTEGER-0-1024-FALSE', Data) -> 'dec_INTEGER-0-1024-FALSE'(Data);
decode_disp('INTEGER-0-2047-FALSE', Data) -> 'dec_INTEGER-0-2047-FALSE'(Data);
decode_disp('INTEGER-0-2048-FALSE', Data) -> 'dec_INTEGER-0-2048-FALSE'(Data);
decode_disp('INTEGER-0-4096-FALSE', Data) -> 'dec_INTEGER-0-4096-FALSE'(Data);
decode_disp('INTEGER-0-8192-FALSE', Data) -> 'dec_INTEGER-0-8192-FALSE'(Data);
decode_disp('INTEGER-0-10000-FALSE', Data) -> 'dec_INTEGER-0-10000-FALSE'(Data);
decode_disp('INTEGER-0-16384-FALSE', Data) -> 'dec_INTEGER-0-16384-FALSE'(Data);
decode_disp('INTEGER-0-32768-FALSE', Data) -> 'dec_INTEGER-0-32768-FALSE'(Data);
decode_disp('INTEGER-0-65534-FALSE', Data) -> 'dec_INTEGER-0-65534-FALSE'(Data);
decode_disp('INTEGER-0-65535-FALSE', Data) -> 'dec_INTEGER-0-65535-FALSE'(Data);
decode_disp('INTEGER-0-65536-FALSE', Data) -> 'dec_INTEGER-0-65536-FALSE'(Data);
decode_disp('INTEGER-0-65537-FALSE', Data) -> 'dec_INTEGER-0-65537-FALSE'(Data);
decode_disp('INTEGER-0-100000-FALSE', Data) -> 'dec_INTEGER-0-100000-FALSE'(Data);
decode_disp('INTEGER-0-131072-FALSE', Data) -> 'dec_INTEGER-0-131072-FALSE'(Data);
decode_disp('INTEGER-0-262144-FALSE', Data) -> 'dec_INTEGER-0-262144-FALSE'(Data);
decode_disp('INTEGER-0-524288-FALSE', Data) -> 'dec_INTEGER-0-524288-FALSE'(Data);
decode_disp('INTEGER-0-1000000-FALSE', Data) -> 'dec_INTEGER-0-1000000-FALSE'(Data);
decode_disp('INTEGER-0-1048576-FALSE', Data) -> 'dec_INTEGER-0-1048576-FALSE'(Data);
decode_disp('INTEGER-0-2097152-FALSE', Data) -> 'dec_INTEGER-0-2097152-FALSE'(Data);
decode_disp('INTEGER-0-4194304-FALSE', Data) -> 'dec_INTEGER-0-4194304-FALSE'(Data);
decode_disp('INTEGER-0-8388608-FALSE', Data) -> 'dec_INTEGER-0-8388608-FALSE'(Data);
decode_disp('INTEGER-0-16777216-FALSE', Data) -> 'dec_INTEGER-0-16777216-FALSE'(Data);
decode_disp('INTEGER-0-33554432-FALSE', Data) -> 'dec_INTEGER-0-33554432-FALSE'(Data);
decode_disp('INTEGER-0-67108864-FALSE', Data) -> 'dec_INTEGER-0-67108864-FALSE'(Data);
decode_disp('INTEGER-0-134217728-FALSE', Data) -> 'dec_INTEGER-0-134217728-FALSE'(Data);
decode_disp('INTEGER-0-268435456-FALSE', Data) -> 'dec_INTEGER-0-268435456-FALSE'(Data);
decode_disp('INTEGER-10-150-FALSE', Data) -> 'dec_INTEGER-10-150-FALSE'(Data);
decode_disp('INTEGER-20-40-FALSE', Data) -> 'dec_INTEGER-20-40-FALSE'(Data);
decode_disp('INTEGER-50-100-FALSE', Data) -> 'dec_INTEGER-50-100-FALSE'(Data);
decode_disp('INTEGER-50-50-FALSE', Data) -> 'dec_INTEGER-50-50-FALSE'(Data);
decode_disp('INTEGER-100-200-FALSE', Data) -> 'dec_INTEGER-100-200-FALSE'(Data);
decode_disp('INTEGER-1-1-FALSE', Data) -> 'dec_INTEGER-1-1-FALSE'(Data);
decode_disp('INTEGER-1-3-FALSE', Data) -> 'dec_INTEGER-1-3-FALSE'(Data);
decode_disp('INTEGER-N200-N10-FALSE', Data) -> 'dec_INTEGER-N200-N10-FALSE'(Data);
decode_disp('INTEGER-N100-100-FALSE', Data) -> 'dec_INTEGER-N100-100-FALSE'(Data);
decode_disp('INTEGER-N100-N10-FALSE', Data) -> 'dec_INTEGER-N100-N10-FALSE'(Data);
decode_disp('INTEGER-N50-50-FALSE', Data) -> 'dec_INTEGER-N50-50-FALSE'(Data);
decode_disp('INTEGER-N10-10-FALSE', Data) -> 'dec_INTEGER-N10-10-FALSE'(Data);
decode_disp('INTEGER-0-1-TRUE', Data) -> 'dec_INTEGER-0-1-TRUE'(Data);
decode_disp('INTEGER-0-2-TRUE', Data) -> 'dec_INTEGER-0-2-TRUE'(Data);
decode_disp('INTEGER-0-4-TRUE', Data) -> 'dec_INTEGER-0-4-TRUE'(Data);
decode_disp('INTEGER-0-8-TRUE', Data) -> 'dec_INTEGER-0-8-TRUE'(Data);
decode_disp('INTEGER-0-16-TRUE', Data) -> 'dec_INTEGER-0-16-TRUE'(Data);
decode_disp('INTEGER-0-32-TRUE', Data) -> 'dec_INTEGER-0-32-TRUE'(Data);
decode_disp('INTEGER-0-64-TRUE', Data) -> 'dec_INTEGER-0-64-TRUE'(Data);
decode_disp('INTEGER-0-99-TRUE', Data) -> 'dec_INTEGER-0-99-TRUE'(Data);
decode_disp('INTEGER-0-100-TRUE', Data) -> 'dec_INTEGER-0-100-TRUE'(Data);
decode_disp('INTEGER-0-128-TRUE', Data) -> 'dec_INTEGER-0-128-TRUE'(Data);
decode_disp('INTEGER-0-200-TRUE', Data) -> 'dec_INTEGER-0-200-TRUE'(Data);
decode_disp('INTEGER-0-256-TRUE', Data) -> 'dec_INTEGER-0-256-TRUE'(Data);
decode_disp('INTEGER-0-257-TRUE', Data) -> 'dec_INTEGER-0-257-TRUE'(Data);
decode_disp('INTEGER-0-512-TRUE', Data) -> 'dec_INTEGER-0-512-TRUE'(Data);
decode_disp('INTEGER-0-1000-TRUE', Data) -> 'dec_INTEGER-0-1000-TRUE'(Data);
decode_disp('INTEGER-0-1024-TRUE', Data) -> 'dec_INTEGER-0-1024-TRUE'(Data);
decode_disp('INTEGER-0-2048-TRUE', Data) -> 'dec_INTEGER-0-2048-TRUE'(Data);
decode_disp('INTEGER-0-4096-TRUE', Data) -> 'dec_INTEGER-0-4096-TRUE'(Data);
decode_disp('INTEGER-0-8192-TRUE', Data) -> 'dec_INTEGER-0-8192-TRUE'(Data);
decode_disp('INTEGER-0-10000-TRUE', Data) -> 'dec_INTEGER-0-10000-TRUE'(Data);
decode_disp('INTEGER-0-16384-TRUE', Data) -> 'dec_INTEGER-0-16384-TRUE'(Data);
decode_disp('INTEGER-0-32768-TRUE', Data) -> 'dec_INTEGER-0-32768-TRUE'(Data);
decode_disp('INTEGER-0-65535-TRUE', Data) -> 'dec_INTEGER-0-65535-TRUE'(Data);
decode_disp('INTEGER-0-65536-TRUE', Data) -> 'dec_INTEGER-0-65536-TRUE'(Data);
decode_disp('INTEGER-0-100000-TRUE', Data) -> 'dec_INTEGER-0-100000-TRUE'(Data);
decode_disp('INTEGER-0-131072-TRUE', Data) -> 'dec_INTEGER-0-131072-TRUE'(Data);
decode_disp('INTEGER-0-262144-TRUE', Data) -> 'dec_INTEGER-0-262144-TRUE'(Data);
decode_disp('INTEGER-0-524288-TRUE', Data) -> 'dec_INTEGER-0-524288-TRUE'(Data);
decode_disp('INTEGER-0-1000000-TRUE', Data) -> 'dec_INTEGER-0-1000000-TRUE'(Data);
decode_disp('INTEGER-0-1048576-TRUE', Data) -> 'dec_INTEGER-0-1048576-TRUE'(Data);
decode_disp('INTEGER-0-2097152-TRUE', Data) -> 'dec_INTEGER-0-2097152-TRUE'(Data);
decode_disp('INTEGER-0-4194304-TRUE', Data) -> 'dec_INTEGER-0-4194304-TRUE'(Data);
decode_disp('INTEGER-0-8388608-TRUE', Data) -> 'dec_INTEGER-0-8388608-TRUE'(Data);
decode_disp('INTEGER-0-16777216-TRUE', Data) -> 'dec_INTEGER-0-16777216-TRUE'(Data);
decode_disp('INTEGER-0-33554432-TRUE', Data) -> 'dec_INTEGER-0-33554432-TRUE'(Data);
decode_disp('INTEGER-0-67108864-TRUE', Data) -> 'dec_INTEGER-0-67108864-TRUE'(Data);
decode_disp('INTEGER-0-134217728-TRUE', Data) -> 'dec_INTEGER-0-134217728-TRUE'(Data);
decode_disp('INTEGER-0-268435456-TRUE', Data) -> 'dec_INTEGER-0-268435456-TRUE'(Data);
decode_disp('INTEGER-10-150-TRUE', Data) -> 'dec_INTEGER-10-150-TRUE'(Data);
decode_disp('INTEGER-20-40-TRUE', Data) -> 'dec_INTEGER-20-40-TRUE'(Data);
decode_disp('INTEGER-50-100-TRUE', Data) -> 'dec_INTEGER-50-100-TRUE'(Data);
decode_disp('INTEGER-50-50-TRUE', Data) -> 'dec_INTEGER-50-50-TRUE'(Data);
decode_disp('INTEGER-100-100-TRUE', Data) -> 'dec_INTEGER-100-100-TRUE'(Data);
decode_disp('INTEGER-100-200-TRUE', Data) -> 'dec_INTEGER-100-200-TRUE'(Data);
decode_disp('INTEGER-1000-1000-TRUE', Data) -> 'dec_INTEGER-1000-1000-TRUE'(Data);
decode_disp('INTEGER-1-1-TRUE', Data) -> 'dec_INTEGER-1-1-TRUE'(Data);
decode_disp('INTEGER-1-3-TRUE', Data) -> 'dec_INTEGER-1-3-TRUE'(Data);
decode_disp('INTEGER-N500-500-TRUE', Data) -> 'dec_INTEGER-N500-500-TRUE'(Data);
decode_disp('INTEGER-N200-N10-TRUE', Data) -> 'dec_INTEGER-N200-N10-TRUE'(Data);
decode_disp('INTEGER-N100-100-TRUE', Data) -> 'dec_INTEGER-N100-100-TRUE'(Data);
decode_disp('INTEGER-N100-N10-TRUE', Data) -> 'dec_INTEGER-N100-N10-TRUE'(Data);
decode_disp('INTEGER-N50-50-TRUE', Data) -> 'dec_INTEGER-N50-50-TRUE'(Data);
decode_disp('INTEGER-N10-10-TRUE', Data) -> 'dec_INTEGER-N10-10-TRUE'(Data);
decode_disp(Type, _Data) -> exit({error,{asn1,{undefined_type,Type}}}).

info() ->
   case ?MODULE:module_info(attributes) of
     Attributes when is_list(Attributes) ->
       case lists:keyfind(asn1_info, 1, Attributes) of
         {_,Info} when is_list(Info) ->
           Info;
         _ ->
           []
       end;
     _ ->
       []
   end.
'enc_INTEGER-NULL-NULL-FALSE'(Val) ->
encode_unconstrained_number(Val).


'dec_INTEGER-NULL-NULL-FALSE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7,V1@Buf4/bitstring>> when V1@V3 =/= 0 ->
{V1@V3,V1@Buf4};
<<1:1,0:1,V1@V4:14,V1@Buf5/bitstring>> when V1@V4 =/= 0 ->
{V1@V4,V1@Buf5};
<<1:1,1:1,V1@V4:6,V1@Buf5/bitstring>> when V1@V4 =/= 0 ->
V1@Mul6 = V1@V4 * 16384,
{V1@Mul6,V1@Buf5}
end,
<<V1@V7:V1@V0/signed-unit:8,V1@Buf8/bitstring>> = V1@Buf1,
{V1@V7,V1@Buf8}
end.

'enc_INTEGER-0-NULL-FALSE'(Val) ->
if Val >= 0 ->
begin
Val@bin = binary:encode_unsigned(Val),
Val@bin_size = byte_size(Val@bin),
if Val@bin_size < 128 ->
[Val@bin_size|Val@bin];
Val@bin_size < 16384 ->
[<<2:2,Val@bin_size:14>>|Val@bin];
true ->
encode_fragmented(Val@bin, 8)
end
end;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-NULL-FALSE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7,V1@Buf4/bitstring>> when V1@V3 =/= 0 ->
{V1@V3,V1@Buf4};
<<1:1,0:1,V1@V4:14,V1@Buf5/bitstring>> when V1@V4 =/= 0 ->
{V1@V4,V1@Buf5};
<<1:1,1:1,V1@V4:6,V1@Buf5/bitstring>> when V1@V4 =/= 0 ->
V1@Mul6 = V1@V4 * 16384,
{V1@Mul6,V1@Buf5}
end,
<<V1@V7:V1@V0/unit:8,V1@Buf8/bitstring>> = V1@Buf1,
{V1@V7,V1@Buf8}
end.

'enc_INTEGER-10-NULL-FALSE'(Val) ->
Val@sub = Val - 10,
if Val@sub >= 0 ->
begin
Val@sub@bin = binary:encode_unsigned(Val@sub),
Val@sub@bin_size = byte_size(Val@sub@bin),
if Val@sub@bin_size < 128 ->
[Val@sub@bin_size|Val@sub@bin];
Val@sub@bin_size < 16384 ->
[<<2:2,Val@sub@bin_size:14>>|Val@sub@bin];
true ->
encode_fragmented(Val@sub@bin, 8)
end
end;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-10-NULL-FALSE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7,V1@Buf4/bitstring>> when V1@V3 =/= 0 ->
{V1@V3,V1@Buf4};
<<1:1,0:1,V1@V4:14,V1@Buf5/bitstring>> when V1@V4 =/= 0 ->
{V1@V4,V1@Buf5};
<<1:1,1:1,V1@V4:6,V1@Buf5/bitstring>> when V1@V4 =/= 0 ->
V1@Mul6 = V1@V4 * 16384,
{V1@Mul6,V1@Buf5}
end,
<<V1@V7:V1@V0/unit:8,V1@Buf8/bitstring>> = V1@Buf1,
V1@Add9 = V1@V7 + 10,
{V1@Add9,V1@Buf8}
end.

'enc_INTEGER-20-NULL-FALSE'(Val) ->
Val@sub = Val - 20,
if Val@sub >= 0 ->
begin
Val@sub@bin = binary:encode_unsigned(Val@sub),
Val@sub@bin_size = byte_size(Val@sub@bin),
if Val@sub@bin_size < 128 ->
[Val@sub@bin_size|Val@sub@bin];
Val@sub@bin_size < 16384 ->
[<<2:2,Val@sub@bin_size:14>>|Val@sub@bin];
true ->
encode_fragmented(Val@sub@bin, 8)
end
end;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-20-NULL-FALSE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7,V1@Buf4/bitstring>> when V1@V3 =/= 0 ->
{V1@V3,V1@Buf4};
<<1:1,0:1,V1@V4:14,V1@Buf5/bitstring>> when V1@V4 =/= 0 ->
{V1@V4,V1@Buf5};
<<1:1,1:1,V1@V4:6,V1@Buf5/bitstring>> when V1@V4 =/= 0 ->
V1@Mul6 = V1@V4 * 16384,
{V1@Mul6,V1@Buf5}
end,
<<V1@V7:V1@V0/unit:8,V1@Buf8/bitstring>> = V1@Buf1,
V1@Add9 = V1@V7 + 20,
{V1@Add9,V1@Buf8}
end.

'enc_INTEGER-100-NULL-FALSE'(Val) ->
Val@sub = Val - 100,
if Val@sub >= 0 ->
begin
Val@sub@bin = binary:encode_unsigned(Val@sub),
Val@sub@bin_size = byte_size(Val@sub@bin),
if Val@sub@bin_size < 128 ->
[Val@sub@bin_size|Val@sub@bin];
Val@sub@bin_size < 16384 ->
[<<2:2,Val@sub@bin_size:14>>|Val@sub@bin];
true ->
encode_fragmented(Val@sub@bin, 8)
end
end;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-100-NULL-FALSE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7,V1@Buf4/bitstring>> when V1@V3 =/= 0 ->
{V1@V3,V1@Buf4};
<<1:1,0:1,V1@V4:14,V1@Buf5/bitstring>> when V1@V4 =/= 0 ->
{V1@V4,V1@Buf5};
<<1:1,1:1,V1@V4:6,V1@Buf5/bitstring>> when V1@V4 =/= 0 ->
V1@Mul6 = V1@V4 * 16384,
{V1@Mul6,V1@Buf5}
end,
<<V1@V7:V1@V0/unit:8,V1@Buf8/bitstring>> = V1@Buf1,
V1@Add9 = V1@V7 + 100,
{V1@Add9,V1@Buf8}
end.

'enc_INTEGER-N10-NULL-FALSE'(Val) ->
Val@sub = Val - -10,
if Val@sub >= 0 ->
begin
Val@sub@bin = binary:encode_unsigned(Val@sub),
Val@sub@bin_size = byte_size(Val@sub@bin),
if Val@sub@bin_size < 128 ->
[Val@sub@bin_size|Val@sub@bin];
Val@sub@bin_size < 16384 ->
[<<2:2,Val@sub@bin_size:14>>|Val@sub@bin];
true ->
encode_fragmented(Val@sub@bin, 8)
end
end;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-N10-NULL-FALSE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7,V1@Buf4/bitstring>> when V1@V3 =/= 0 ->
{V1@V3,V1@Buf4};
<<1:1,0:1,V1@V4:14,V1@Buf5/bitstring>> when V1@V4 =/= 0 ->
{V1@V4,V1@Buf5};
<<1:1,1:1,V1@V4:6,V1@Buf5/bitstring>> when V1@V4 =/= 0 ->
V1@Mul6 = V1@V4 * 16384,
{V1@Mul6,V1@Buf5}
end,
<<V1@V7:V1@V0/unit:8,V1@Buf8/bitstring>> = V1@Buf1,
V1@Add9 = V1@V7 + -10,
{V1@Add9,V1@Buf8}
end.

'enc_INTEGER-N100-NULL-FALSE'(Val) ->
Val@sub = Val - -100,
if Val@sub >= 0 ->
begin
Val@sub@bin = binary:encode_unsigned(Val@sub),
Val@sub@bin_size = byte_size(Val@sub@bin),
if Val@sub@bin_size < 128 ->
[Val@sub@bin_size|Val@sub@bin];
Val@sub@bin_size < 16384 ->
[<<2:2,Val@sub@bin_size:14>>|Val@sub@bin];
true ->
encode_fragmented(Val@sub@bin, 8)
end
end;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-N100-NULL-FALSE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7,V1@Buf4/bitstring>> when V1@V3 =/= 0 ->
{V1@V3,V1@Buf4};
<<1:1,0:1,V1@V4:14,V1@Buf5/bitstring>> when V1@V4 =/= 0 ->
{V1@V4,V1@Buf5};
<<1:1,1:1,V1@V4:6,V1@Buf5/bitstring>> when V1@V4 =/= 0 ->
V1@Mul6 = V1@V4 * 16384,
{V1@Mul6,V1@Buf5}
end,
<<V1@V7:V1@V0/unit:8,V1@Buf8/bitstring>> = V1@Buf1,
V1@Add9 = V1@V7 + -100,
{V1@Add9,V1@Buf8}
end.

'enc_INTEGER-N200-NULL-FALSE'(Val) ->
Val@sub = Val - -200,
if Val@sub >= 0 ->
begin
Val@sub@bin = binary:encode_unsigned(Val@sub),
Val@sub@bin_size = byte_size(Val@sub@bin),
if Val@sub@bin_size < 128 ->
[Val@sub@bin_size|Val@sub@bin];
Val@sub@bin_size < 16384 ->
[<<2:2,Val@sub@bin_size:14>>|Val@sub@bin];
true ->
encode_fragmented(Val@sub@bin, 8)
end
end;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-N200-NULL-FALSE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7,V1@Buf4/bitstring>> when V1@V3 =/= 0 ->
{V1@V3,V1@Buf4};
<<1:1,0:1,V1@V4:14,V1@Buf5/bitstring>> when V1@V4 =/= 0 ->
{V1@V4,V1@Buf5};
<<1:1,1:1,V1@V4:6,V1@Buf5/bitstring>> when V1@V4 =/= 0 ->
V1@Mul6 = V1@V4 * 16384,
{V1@Mul6,V1@Buf5}
end,
<<V1@V7:V1@V0/unit:8,V1@Buf8/bitstring>> = V1@Buf1,
V1@Add9 = V1@V7 + -200,
{V1@Add9,V1@Buf8}
end.

'enc_INTEGER-0-NULL-TRUE'(Val) ->
if Val >= 0 ->
[<<0:1>>|begin
Val@bin = binary:encode_unsigned(Val),
Val@bin_size = byte_size(Val@bin),
if Val@bin_size < 128 ->
[Val@bin_size|Val@bin];
Val@bin_size < 16384 ->
[<<2:2,Val@bin_size:14>>|Val@bin];
true ->
encode_fragmented(Val@bin, 8)
end
end];
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-NULL-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-10-NULL-TRUE'(Val) ->
Val@sub = Val - 10,
if Val@sub >= 0 ->
[<<0:1>>|begin
Val@sub@bin = binary:encode_unsigned(Val@sub),
Val@sub@bin_size = byte_size(Val@sub@bin),
if Val@sub@bin_size < 128 ->
[Val@sub@bin_size|Val@sub@bin];
Val@sub@bin_size < 16384 ->
[<<2:2,Val@sub@bin_size:14>>|Val@sub@bin];
true ->
encode_fragmented(Val@sub@bin, 8)
end
end];
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-10-NULL-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/unit:8,V1@Buf11/bitstring>> = V1@Buf4,
V1@Add12 = V1@V10 + 10,
{V1@Add12,V1@Buf11};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-20-NULL-TRUE'(Val) ->
Val@sub = Val - 20,
if Val@sub >= 0 ->
[<<0:1>>|begin
Val@sub@bin = binary:encode_unsigned(Val@sub),
Val@sub@bin_size = byte_size(Val@sub@bin),
if Val@sub@bin_size < 128 ->
[Val@sub@bin_size|Val@sub@bin];
Val@sub@bin_size < 16384 ->
[<<2:2,Val@sub@bin_size:14>>|Val@sub@bin];
true ->
encode_fragmented(Val@sub@bin, 8)
end
end];
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-20-NULL-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/unit:8,V1@Buf11/bitstring>> = V1@Buf4,
V1@Add12 = V1@V10 + 20,
{V1@Add12,V1@Buf11};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-N100-NULL-TRUE'(Val) ->
Val@sub = Val - -100,
if Val@sub >= 0 ->
[<<0:1>>|begin
Val@sub@bin = binary:encode_unsigned(Val@sub),
Val@sub@bin_size = byte_size(Val@sub@bin),
if Val@sub@bin_size < 128 ->
[Val@sub@bin_size|Val@sub@bin];
Val@sub@bin_size < 16384 ->
[<<2:2,Val@sub@bin_size:14>>|Val@sub@bin];
true ->
encode_fragmented(Val@sub@bin, 8)
end
end];
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-N100-NULL-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/unit:8,V1@Buf11/bitstring>> = V1@Buf4,
V1@Add12 = V1@V10 + -100,
{V1@Add12,V1@Buf11};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-1-FALSE'(Val) ->
if Val bsr 1 =:= 0 ->
<<Val:1>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-1-FALSE'(Bytes) ->
begin
<<V1@V0:1,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-2-FALSE'(Val) ->
if 0 =< Val, Val < 3 ->
<<Val:2>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-2-FALSE'(Bytes) ->
begin
<<V1@V0:2,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-4-FALSE'(Val) ->
if 0 =< Val, Val < 5 ->
<<Val:3>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-4-FALSE'(Bytes) ->
begin
<<V1@V0:3,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-8-FALSE'(Val) ->
if 0 =< Val, Val < 9 ->
<<Val:4>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-8-FALSE'(Bytes) ->
begin
<<V1@V0:4,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-16-FALSE'(Val) ->
if 0 =< Val, Val < 17 ->
<<Val:5>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-16-FALSE'(Bytes) ->
begin
<<V1@V0:5,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-32-FALSE'(Val) ->
if 0 =< Val, Val < 33 ->
<<Val:6>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-32-FALSE'(Bytes) ->
begin
<<V1@V0:6,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-64-FALSE'(Val) ->
if 0 =< Val, Val < 65 ->
<<Val:7>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-64-FALSE'(Bytes) ->
begin
<<V1@V0:7,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-99-FALSE'(Val) ->
if 0 =< Val, Val < 100 ->
<<Val:7>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-99-FALSE'(Bytes) ->
begin
<<V1@V0:7,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-100-FALSE'(Val) ->
if 0 =< Val, Val < 101 ->
<<Val:7>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-100-FALSE'(Bytes) ->
begin
<<V1@V0:7,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-127-FALSE'(Val) ->
if Val bsr 7 =:= 0 ->
<<Val:7>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-127-FALSE'(Bytes) ->
begin
<<V1@V0:7,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-128-FALSE'(Val) ->
if 0 =< Val, Val < 129 ->
[Val];
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-128-FALSE'(Bytes) ->
begin
<<V1@V0:8,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-200-FALSE'(Val) ->
if 0 =< Val, Val < 201 ->
[Val];
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-200-FALSE'(Bytes) ->
begin
<<V1@V0:8,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-253-FALSE'(Val) ->
if 0 =< Val, Val < 254 ->
[Val];
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-253-FALSE'(Bytes) ->
begin
<<V1@V0:8,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-254-FALSE'(Val) ->
if 0 =< Val, Val < 255 ->
[Val];
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-254-FALSE'(Bytes) ->
begin
<<V1@V0:8,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-255-FALSE'(Val) ->
if Val bsr 8 =:= 0 ->
[Val];
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-255-FALSE'(Bytes) ->
begin
<<V1@V0:8,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-256-FALSE'(Val) ->
if 0 =< Val, Val < 257 ->
<<Val:9>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-256-FALSE'(Bytes) ->
begin
<<V1@V0:9,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-257-FALSE'(Val) ->
if 0 =< Val, Val < 258 ->
<<Val:9>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-257-FALSE'(Bytes) ->
begin
<<V1@V0:9,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-511-FALSE'(Val) ->
if Val bsr 9 =:= 0 ->
<<Val:9>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-511-FALSE'(Bytes) ->
begin
<<V1@V0:9,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-512-FALSE'(Val) ->
if 0 =< Val, Val < 513 ->
<<Val:10>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-512-FALSE'(Bytes) ->
begin
<<V1@V0:10,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-1000-FALSE'(Val) ->
if 0 =< Val, Val < 1001 ->
<<Val:10>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-1000-FALSE'(Bytes) ->
begin
<<V1@V0:10,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-1024-FALSE'(Val) ->
if 0 =< Val, Val < 1025 ->
<<Val:11>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-1024-FALSE'(Bytes) ->
begin
<<V1@V0:11,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-2047-FALSE'(Val) ->
if Val bsr 11 =:= 0 ->
<<Val:11>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-2047-FALSE'(Bytes) ->
begin
<<V1@V0:11,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-2048-FALSE'(Val) ->
if 0 =< Val, Val < 2049 ->
<<Val:12>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-2048-FALSE'(Bytes) ->
begin
<<V1@V0:12,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-4096-FALSE'(Val) ->
if 0 =< Val, Val < 4097 ->
<<Val:13>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-4096-FALSE'(Bytes) ->
begin
<<V1@V0:13,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-8192-FALSE'(Val) ->
if 0 =< Val, Val < 8193 ->
<<Val:14>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-8192-FALSE'(Bytes) ->
begin
<<V1@V0:14,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-10000-FALSE'(Val) ->
if 0 =< Val, Val < 10001 ->
<<Val:14>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-10000-FALSE'(Bytes) ->
begin
<<V1@V0:14,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-16384-FALSE'(Val) ->
if 0 =< Val, Val < 16385 ->
<<Val:15>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-16384-FALSE'(Bytes) ->
begin
<<V1@V0:15,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-32768-FALSE'(Val) ->
if 0 =< Val, Val < 32769 ->
<<Val:16>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-32768-FALSE'(Bytes) ->
begin
<<V1@V0:16,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-65534-FALSE'(Val) ->
if 0 =< Val, Val < 65535 ->
<<Val:16>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-65534-FALSE'(Bytes) ->
begin
<<V1@V0:16,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-65535-FALSE'(Val) ->
if Val bsr 16 =:= 0 ->
<<Val:16>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-65535-FALSE'(Bytes) ->
begin
<<V1@V0:16,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-65536-FALSE'(Val) ->
if 0 =< Val, Val < 65537 ->
<<Val:17>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-65536-FALSE'(Bytes) ->
begin
<<V1@V0:17,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-65537-FALSE'(Val) ->
if 0 =< Val, Val < 65538 ->
<<Val:17>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-65537-FALSE'(Bytes) ->
begin
<<V1@V0:17,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-100000-FALSE'(Val) ->
if 0 =< Val, Val < 100001 ->
<<Val:17>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-100000-FALSE'(Bytes) ->
begin
<<V1@V0:17,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-131072-FALSE'(Val) ->
if 0 =< Val, Val < 131073 ->
<<Val:18>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-131072-FALSE'(Bytes) ->
begin
<<V1@V0:18,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-262144-FALSE'(Val) ->
if 0 =< Val, Val < 262145 ->
<<Val:19>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-262144-FALSE'(Bytes) ->
begin
<<V1@V0:19,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-524288-FALSE'(Val) ->
if 0 =< Val, Val < 524289 ->
<<Val:20>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-524288-FALSE'(Bytes) ->
begin
<<V1@V0:20,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-1000000-FALSE'(Val) ->
if 0 =< Val, Val < 1000001 ->
<<Val:20>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-1000000-FALSE'(Bytes) ->
begin
<<V1@V0:20,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-1048576-FALSE'(Val) ->
if 0 =< Val, Val < 1048577 ->
<<Val:21>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-1048576-FALSE'(Bytes) ->
begin
<<V1@V0:21,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-2097152-FALSE'(Val) ->
if 0 =< Val, Val < 2097153 ->
<<Val:22>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-2097152-FALSE'(Bytes) ->
begin
<<V1@V0:22,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-4194304-FALSE'(Val) ->
if 0 =< Val, Val < 4194305 ->
<<Val:23>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-4194304-FALSE'(Bytes) ->
begin
<<V1@V0:23,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-8388608-FALSE'(Val) ->
if 0 =< Val, Val < 8388609 ->
<<Val:24>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-8388608-FALSE'(Bytes) ->
begin
<<V1@V0:24,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-16777216-FALSE'(Val) ->
if 0 =< Val, Val < 16777217 ->
<<Val:25>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-16777216-FALSE'(Bytes) ->
begin
<<V1@V0:25,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-33554432-FALSE'(Val) ->
if 0 =< Val, Val < 33554433 ->
<<Val:26>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-33554432-FALSE'(Bytes) ->
begin
<<V1@V0:26,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-67108864-FALSE'(Val) ->
if 0 =< Val, Val < 67108865 ->
<<Val:27>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-67108864-FALSE'(Bytes) ->
begin
<<V1@V0:27,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-134217728-FALSE'(Val) ->
if 0 =< Val, Val < 134217729 ->
<<Val:28>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-134217728-FALSE'(Bytes) ->
begin
<<V1@V0:28,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-268435456-FALSE'(Val) ->
if 0 =< Val, Val < 268435457 ->
<<Val:29>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-0-268435456-FALSE'(Bytes) ->
begin
<<V1@V0:29,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-10-150-FALSE'(Val) ->
Val@sub = Val - 10,
if 0 =< Val@sub, Val@sub < 141 ->
[Val@sub];
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-10-150-FALSE'(Bytes) ->
begin
<<V1@V0:8,V1@Buf1/bitstring>> = Bytes,
V1@Add2 = V1@V0 + 10,
{V1@Add2,V1@Buf1}
end.

'enc_INTEGER-20-40-FALSE'(Val) ->
Val@sub = Val - 20,
if 0 =< Val@sub, Val@sub < 21 ->
<<Val@sub:5>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-20-40-FALSE'(Bytes) ->
begin
<<V1@V0:5,V1@Buf1/bitstring>> = Bytes,
V1@Add2 = V1@V0 + 20,
{V1@Add2,V1@Buf1}
end.

'enc_INTEGER-50-100-FALSE'(Val) ->
Val@sub = Val - 50,
if 0 =< Val@sub, Val@sub < 51 ->
<<Val@sub:6>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-50-100-FALSE'(Bytes) ->
begin
<<V1@V0:6,V1@Buf1/bitstring>> = Bytes,
V1@Add2 = V1@V0 + 50,
{V1@Add2,V1@Buf1}
end.

'enc_INTEGER-50-50-FALSE'(Val) ->
if Val =:= 50 ->
[];
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-50-50-FALSE'(Bytes) ->
begin
<<V1@V0:0,V1@Buf1/bitstring>> = Bytes,
V1@Add2 = V1@V0 + 50,
{V1@Add2,V1@Buf1}
end.

'enc_INTEGER-100-200-FALSE'(Val) ->
Val@sub = Val - 100,
if 0 =< Val@sub, Val@sub < 101 ->
<<Val@sub:7>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-100-200-FALSE'(Bytes) ->
begin
<<V1@V0:7,V1@Buf1/bitstring>> = Bytes,
V1@Add2 = V1@V0 + 100,
{V1@Add2,V1@Buf1}
end.

'enc_INTEGER-1-1-FALSE'(Val) ->
if Val =:= 1 ->
[];
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-1-1-FALSE'(Bytes) ->
begin
<<V1@V0:0,V1@Buf1/bitstring>> = Bytes,
V1@Add2 = V1@V0 + 1,
{V1@Add2,V1@Buf1}
end.

'enc_INTEGER-1-3-FALSE'(Val) ->
Val@sub = Val - 1,
if 0 =< Val@sub, Val@sub < 3 ->
<<Val@sub:2>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-1-3-FALSE'(Bytes) ->
begin
<<V1@V0:2,V1@Buf1/bitstring>> = Bytes,
V1@Add2 = V1@V0 + 1,
{V1@Add2,V1@Buf1}
end.

'enc_INTEGER-N200-N10-FALSE'(Val) ->
Val@sub = Val - -200,
if 0 =< Val@sub, Val@sub < 191 ->
[Val@sub];
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-N200-N10-FALSE'(Bytes) ->
begin
<<V1@V0:8,V1@Buf1/bitstring>> = Bytes,
V1@Add2 = V1@V0 + -200,
{V1@Add2,V1@Buf1}
end.

'enc_INTEGER-N100-100-FALSE'(Val) ->
Val@sub = Val - -100,
if 0 =< Val@sub, Val@sub < 201 ->
[Val@sub];
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-N100-100-FALSE'(Bytes) ->
begin
<<V1@V0:8,V1@Buf1/bitstring>> = Bytes,
V1@Add2 = V1@V0 + -100,
{V1@Add2,V1@Buf1}
end.

'enc_INTEGER-N100-N10-FALSE'(Val) ->
Val@sub = Val - -100,
if 0 =< Val@sub, Val@sub < 91 ->
<<Val@sub:7>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-N100-N10-FALSE'(Bytes) ->
begin
<<V1@V0:7,V1@Buf1/bitstring>> = Bytes,
V1@Add2 = V1@V0 + -100,
{V1@Add2,V1@Buf1}
end.

'enc_INTEGER-N50-50-FALSE'(Val) ->
Val@sub = Val - -50,
if 0 =< Val@sub, Val@sub < 101 ->
<<Val@sub:7>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-N50-50-FALSE'(Bytes) ->
begin
<<V1@V0:7,V1@Buf1/bitstring>> = Bytes,
V1@Add2 = V1@V0 + -50,
{V1@Add2,V1@Buf1}
end.

'enc_INTEGER-N10-10-FALSE'(Val) ->
Val@sub = Val - -10,
if 0 =< Val@sub, Val@sub < 21 ->
<<Val@sub:5>>;
true ->
exit({error,{asn1,{illegal_integer,Val}}})
end.


'dec_INTEGER-N10-10-FALSE'(Bytes) ->
begin
<<V1@V0:5,V1@Buf1/bitstring>> = Bytes,
V1@Add2 = V1@V0 + -10,
{V1@Add2,V1@Buf1}
end.

'enc_INTEGER-0-1-TRUE'(Val) ->
if Val bsr 1 =:= 0 ->
<<0:1,Val:1>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-1-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:1,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-2-TRUE'(Val) ->
if 0 =< Val, Val < 3 ->
<<0:1,Val:2>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-2-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:2,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-4-TRUE'(Val) ->
if 0 =< Val, Val < 5 ->
<<0:1,Val:3>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-4-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:3,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-8-TRUE'(Val) ->
if 0 =< Val, Val < 9 ->
<<0:1,Val:4>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-8-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:4,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-16-TRUE'(Val) ->
if 0 =< Val, Val < 17 ->
<<0:1,Val:5>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-16-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:5,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-32-TRUE'(Val) ->
if 0 =< Val, Val < 33 ->
<<0:1,Val:6>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-32-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:6,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-64-TRUE'(Val) ->
if 0 =< Val, Val < 65 ->
<<0:1,Val:7>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-64-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-99-TRUE'(Val) ->
if 0 =< Val, Val < 100 ->
<<0:1,Val:7>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-99-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-100-TRUE'(Val) ->
if 0 =< Val, Val < 101 ->
<<0:1,Val:7>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-100-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-128-TRUE'(Val) ->
if 0 =< Val, Val < 129 ->
[<<0:1,Val:8>>];
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-128-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:8,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-200-TRUE'(Val) ->
if 0 =< Val, Val < 201 ->
[<<0:1,Val:8>>];
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-200-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:8,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-256-TRUE'(Val) ->
if 0 =< Val, Val < 257 ->
<<0:1,Val:9>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-256-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:9,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-257-TRUE'(Val) ->
if 0 =< Val, Val < 258 ->
<<0:1,Val:9>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-257-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:9,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-512-TRUE'(Val) ->
if 0 =< Val, Val < 513 ->
<<0:1,Val:10>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-512-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:10,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-1000-TRUE'(Val) ->
if 0 =< Val, Val < 1001 ->
<<0:1,Val:10>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-1000-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:10,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-1024-TRUE'(Val) ->
if 0 =< Val, Val < 1025 ->
<<0:1,Val:11>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-1024-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:11,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-2048-TRUE'(Val) ->
if 0 =< Val, Val < 2049 ->
<<0:1,Val:12>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-2048-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:12,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-4096-TRUE'(Val) ->
if 0 =< Val, Val < 4097 ->
<<0:1,Val:13>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-4096-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:13,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-8192-TRUE'(Val) ->
if 0 =< Val, Val < 8193 ->
<<0:1,Val:14>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-8192-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:14,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-10000-TRUE'(Val) ->
if 0 =< Val, Val < 10001 ->
<<0:1,Val:14>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-10000-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:14,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-16384-TRUE'(Val) ->
if 0 =< Val, Val < 16385 ->
<<0:1,Val:15>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-16384-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:15,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-32768-TRUE'(Val) ->
if 0 =< Val, Val < 32769 ->
<<0:1,Val:16>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-32768-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:16,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-65535-TRUE'(Val) ->
if Val bsr 16 =:= 0 ->
<<0:1,Val:16>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-65535-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:16,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-65536-TRUE'(Val) ->
if 0 =< Val, Val < 65537 ->
<<0:1,Val:17>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-65536-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:17,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-100000-TRUE'(Val) ->
if 0 =< Val, Val < 100001 ->
<<0:1,Val:17>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-100000-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:17,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-131072-TRUE'(Val) ->
if 0 =< Val, Val < 131073 ->
<<0:1,Val:18>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-131072-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:18,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-262144-TRUE'(Val) ->
if 0 =< Val, Val < 262145 ->
<<0:1,Val:19>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-262144-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:19,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-524288-TRUE'(Val) ->
if 0 =< Val, Val < 524289 ->
<<0:1,Val:20>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-524288-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:20,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-1000000-TRUE'(Val) ->
if 0 =< Val, Val < 1000001 ->
<<0:1,Val:20>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-1000000-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:20,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-1048576-TRUE'(Val) ->
if 0 =< Val, Val < 1048577 ->
<<0:1,Val:21>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-1048576-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:21,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-2097152-TRUE'(Val) ->
if 0 =< Val, Val < 2097153 ->
<<0:1,Val:22>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-2097152-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:22,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-4194304-TRUE'(Val) ->
if 0 =< Val, Val < 4194305 ->
<<0:1,Val:23>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-4194304-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:23,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-8388608-TRUE'(Val) ->
if 0 =< Val, Val < 8388609 ->
<<0:1,Val:24>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-8388608-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:24,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-16777216-TRUE'(Val) ->
if 0 =< Val, Val < 16777217 ->
<<0:1,Val:25>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-16777216-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:25,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-33554432-TRUE'(Val) ->
if 0 =< Val, Val < 33554433 ->
<<0:1,Val:26>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-33554432-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:26,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-67108864-TRUE'(Val) ->
if 0 =< Val, Val < 67108865 ->
<<0:1,Val:27>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-67108864-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:27,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-134217728-TRUE'(Val) ->
if 0 =< Val, Val < 134217729 ->
<<0:1,Val:28>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-134217728-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:28,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-0-268435456-TRUE'(Val) ->
if 0 =< Val, Val < 268435457 ->
<<0:1,Val:29>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-0-268435456-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:29,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-10-150-TRUE'(Val) ->
Val@sub = Val - 10,
if 0 =< Val@sub, Val@sub < 141 ->
[<<0:1,Val@sub:8>>];
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-10-150-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:8,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + 10,
{V1@Add5,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-20-40-TRUE'(Val) ->
Val@sub = Val - 20,
if 0 =< Val@sub, Val@sub < 21 ->
<<0:1,Val@sub:5>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-20-40-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:5,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + 20,
{V1@Add5,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-50-100-TRUE'(Val) ->
Val@sub = Val - 50,
if 0 =< Val@sub, Val@sub < 51 ->
<<0:1,Val@sub:6>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-50-100-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:6,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + 50,
{V1@Add5,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-50-50-TRUE'(Val) ->
if Val =:= 50 ->
<<0:1>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-50-50-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:0,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + 50,
{V1@Add5,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-100-100-TRUE'(Val) ->
if Val =:= 100 ->
<<0:1>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-100-100-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:0,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + 100,
{V1@Add5,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-100-200-TRUE'(Val) ->
Val@sub = Val - 100,
if 0 =< Val@sub, Val@sub < 101 ->
<<0:1,Val@sub:7>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-100-200-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + 100,
{V1@Add5,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-1000-1000-TRUE'(Val) ->
if Val =:= 1000 ->
<<0:1>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-1000-1000-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:0,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + 1000,
{V1@Add5,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-1-1-TRUE'(Val) ->
if Val =:= 1 ->
<<0:1>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-1-1-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:0,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + 1,
{V1@Add5,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-1-3-TRUE'(Val) ->
Val@sub = Val - 1,
if 0 =< Val@sub, Val@sub < 3 ->
<<0:1,Val@sub:2>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-1-3-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:2,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + 1,
{V1@Add5,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-N500-500-TRUE'(Val) ->
Val@sub = Val - -500,
if 0 =< Val@sub, Val@sub < 1001 ->
<<0:1,Val@sub:10>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-N500-500-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:10,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + -500,
{V1@Add5,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-N200-N10-TRUE'(Val) ->
Val@sub = Val - -200,
if 0 =< Val@sub, Val@sub < 191 ->
[<<0:1,Val@sub:8>>];
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-N200-N10-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:8,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + -200,
{V1@Add5,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-N100-100-TRUE'(Val) ->
Val@sub = Val - -100,
if 0 =< Val@sub, Val@sub < 201 ->
[<<0:1,Val@sub:8>>];
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-N100-100-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:8,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + -100,
{V1@Add5,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-N100-N10-TRUE'(Val) ->
Val@sub = Val - -100,
if 0 =< Val@sub, Val@sub < 91 ->
<<0:1,Val@sub:7>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-N100-N10-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + -100,
{V1@Add5,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-N50-50-TRUE'(Val) ->
Val@sub = Val - -50,
if 0 =< Val@sub, Val@sub < 101 ->
<<0:1,Val@sub:7>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-N50-50-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + -50,
{V1@Add5,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.

'enc_INTEGER-N10-10-TRUE'(Val) ->
Val@sub = Val - -10,
if 0 =< Val@sub, Val@sub < 21 ->
<<0:1,Val@sub:5>>;
true ->
[<<1:1>>|encode_unconstrained_number(Val)]
end.


'dec_INTEGER-N10-10-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:5,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + -10,
{V1@Add5,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<0:1,V1@V6:7,V1@Buf7/bitstring>> when V1@V6 =/= 0 ->
{V1@V6,V1@Buf7};
<<1:1,0:1,V1@V7:14,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
{V1@V7,V1@Buf8};
<<1:1,1:1,V1@V7:6,V1@Buf8/bitstring>> when V1@V7 =/= 0 ->
V1@Mul9 = V1@V7 * 16384,
{V1@Mul9,V1@Buf8}
end,
<<V1@V10:V1@V3/signed-unit:8,V1@Buf11/bitstring>> = V1@Buf4,
{V1@V10,V1@Buf11}
end,
{V1@V0,V1@Buf1}
end.


%%%
%%% Run-time functions.
%%%

'dialyzer-suppressions'(Arg) ->
    complete(element(1, Arg)),
    ok.

complete(InList) when is_list(InList) ->
    case list_to_bitstring(InList) of
        <<>> ->
            <<0>>;
        Res ->
            Sz = bit_size(Res),
            case Sz band 7 of
                0 ->
                    Res;
                Bits ->
                    <<Res:Sz/bitstring,0:(8 - Bits)>>
            end
    end;
complete(Bin) when is_binary(Bin) ->
    case Bin of
        <<>> ->
            <<0>>;
        _ ->
            Bin
    end;
complete(InList) when is_bitstring(InList) ->
    Sz = bit_size(InList),
    PadLen = 8 - Sz band 7,
    <<InList:Sz/bitstring,0:PadLen>>.

encode_fragmented(Bin, Unit) ->
    encode_fragmented_1(Bin, Unit, 4).

encode_fragmented_1(Bin, Unit, N) ->
    SegSz = Unit * N * 16384,
    case Bin of
        <<B:SegSz/bitstring,T/bitstring>> ->
            [<<3:2,N:6>>, B | encode_fragmented_1(T, Unit, N)];
        _ when N > 1 ->
            encode_fragmented_1(Bin, Unit, N - 1);
        _ ->
            case bit_size(Bin) div Unit of
                Len when Len < 128 ->
                    [Len, Bin];
                Len when Len < 16384 ->
                    [<<2:2,Len:14>>, Bin]
            end
    end.

encode_unconstrained_number(Val) when not is_integer(Val) ->
    exit({error, {asn1, {illegal_integer, Val}}});
encode_unconstrained_number(Val) when Val >= 0 ->
    if
        Val < 128 ->
            [1, Val];
        Val < 256 ->
            [<<2,0>>, Val];
        true ->
            case binary:encode_unsigned(Val) of
                <<0:1,_/bitstring>> = Bin ->
                    case byte_size(Bin) of
                        Sz when Sz < 128 ->
                            [Sz, Bin];
                        Sz when Sz < 16384 ->
                            [<<2:2,Sz:14>>, Bin]
                    end;
                <<1:1,_/bitstring>> = Bin ->
                    case byte_size(Bin) + 1 of
                        Sz when Sz < 128 ->
                            [Sz, 0, Bin];
                        Sz when Sz < 16384 ->
                            [<<2:2,Sz:14,0:8>>, Bin]
                    end
            end
    end;
encode_unconstrained_number(Val) ->
    Oct = enint(Val, []),
    Len = length(Oct),
    if
        Len < 128 ->
            [Len | Oct];
        Len < 16384 ->
            [<<2:2,Len:14>> | Oct]
    end.

enint(-1, [B1 | T]) when B1 > 127 ->
    [B1 | T];
enint(N, Acc) ->
    enint(N bsr 8, [N band 255 | Acc]).
