%% Generated by the Erlang ASN.1 PER (unaligned) compiler. Version: 5.0.21.1
%% Purpose: Encoding and decoding of the types in REALS.

-module('REALS').
-compile(nowarn_unused_vars).
-dialyzer(no_improper_lists).
-dialyzer(no_match).
-asn1_info([{vsn,'5.0.21.1'},
            {module,'REALS'},
            {options,[{i,"/home/sandeep/Workspace/Github/asn1c-go/lib/per/testing/erlang/uper"},
 {outdir,"/home/sandeep/Workspace/Github/asn1c-go/lib/per/testing/erlang/uper"},
 uper,
 {i,"."}]}]).

-export([encoding_rule/0,maps/0,bit_string_format/0,
         legacy_erlang_types/0]).
-export(['dialyzer-suppressions'/1]).
-export([
'enc_FLOAT-64'/1
]).

-export([
'dec_FLOAT-64'/1
]).

-export([info/0]).

-export([encode/2,decode/2]).

encoding_rule() -> uper.

maps() -> false.

bit_string_format() -> bitstring.

legacy_erlang_types() -> false.

encode(Type, Data) ->
try complete(encode_disp(Type, Data)) of
  Bytes ->
    {ok,Bytes}
  catch
    Class:Exception:Stk when Class =:= error; Class =:= exit ->
      case Exception of
        {error,{asn1,Reason}} ->
          {error,{asn1,{Reason,Stk}}};
        Reason ->
         {error,{asn1,{Reason,Stk}}}
      end
end.

decode(Type, Data) ->
try
   {Result,_Rest} = decode_disp(Type, Data),
   {ok,Result}
  catch
    Class:Exception:Stk when Class =:= error; Class =:= exit ->
      case Exception of
        {error,{asn1,Reason}} ->
          {error,{asn1,{Reason,Stk}}};
        Reason ->
         {error,{asn1,{Reason,Stk}}}
      end
end.

encode_disp('FLOAT-64', Data) -> 'enc_FLOAT-64'(Data);
encode_disp(Type, _Data) -> exit({error,{asn1,{undefined_type,Type}}}).

decode_disp('FLOAT-64', Data) -> 'dec_FLOAT-64'(Data);
decode_disp(Type, _Data) -> exit({error,{asn1,{undefined_type,Type}}}).

info() ->
   case ?MODULE:module_info(attributes) of
     Attributes when is_list(Attributes) ->
       case lists:keyfind(asn1_info, 1, Attributes) of
         {_,Info} when is_list(Info) ->
           Info;
         _ ->
           []
       end;
     _ ->
       []
   end.
'enc_FLOAT-64'(Val) ->
Enc1@bin = encode_real(Val),
Enc1@len = byte_size(Enc1@bin),
if Enc1@len < 128 ->
[Enc1@len|Enc1@bin];
Enc1@len < 16384 ->
[<<2:2,Enc1@len:14>>|Enc1@bin];
true ->
encode_fragmented(Enc1@bin, 8)
end.


'dec_FLOAT-64'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,0:1,V1@V4:14,V1@Buf5/bitstring>> ->
{V1@V4,V1@Buf5};
<<1:1,1:1,V1@V4:6,V1@Buf5/bitstring>> ->
V1@Mul6 = V1@V4 * 16384,
{V1@Mul6,V1@Buf5}
end,
<<V1@V7:V1@V0/binary-unit:8,V1@Buf8/bitstring>> = V1@Buf1,
{V1@V9,V1@Buf10}  = {decode_real(V1@V7),V1@Buf8},
{V1@V9,V1@Buf10}
end.


%%%
%%% Run-time functions.
%%%

'dialyzer-suppressions'(Arg) ->
    complete(element(1, Arg)),
    ok.

complete(InList) when is_list(InList) ->
    case list_to_bitstring(InList) of
        <<>> ->
            <<0>>;
        Res ->
            Sz = bit_size(Res),
            case Sz band 7 of
                0 ->
                    Res;
                Bits ->
                    <<Res:Sz/bitstring,0:(8 - Bits)>>
            end
    end;
complete(Bin) when is_binary(Bin) ->
    case Bin of
        <<>> ->
            <<0>>;
        _ ->
            Bin
    end;
complete(InList) when is_bitstring(InList) ->
    Sz = bit_size(InList),
    PadLen = 8 - Sz band 7,
    <<InList:Sz/bitstring,0:PadLen>>.

decode_integer2(Len, <<0:1,_:7,_Bs/binary>> = Bin, RemovedBytes) ->
    <<Int:Len/unit:8,Buffer2/binary>> = Bin,
    {Int, Buffer2, RemovedBytes};
decode_integer2(Len, <<1:1,B2:7,Bs/binary>>, RemovedBytes) ->
    <<N:Len/unit:8,Buffer2/binary>> = <<B2,Bs/binary>>,
    Int = N - (1 bsl (8 * Len - 1)),
    {Int, Buffer2, RemovedBytes}.

decode_real(Buffer) ->
    Sz = byte_size(Buffer),
    {RealVal, <<>>, Sz} = decode_real2(Buffer, [], Sz, 0),
    RealVal.

decode_real2(Buffer, _C, 0, _RemBytes) ->
    {0, Buffer};
decode_real2(Buffer0, _C, Len, RemBytes1) ->
    <<First,Buffer2/binary>> = Buffer0,
    if
        First =:= 64 ->
            {'PLUS-INFINITY', Buffer2};
        First =:= 65 ->
            {'MINUS-INFINITY', Buffer2};
        First =:= 1
        orelse
        First =:= 2
        orelse
        First =:= 3 ->
            {NRx, Rest} = split_binary(Buffer2, Len - 1),
            {binary_to_list(NRx), Rest, Len};
        true ->
            <<_B7:1,Sign:1,BB:2,_FF:2,EE:2>> = <<First>>,
            Base =
                case BB of
                    0 ->
                        2;
                    _ ->
                        exit({error, {asn1, {non_supported_base, BB}}})
                end,
            {FirstLen, {Exp, Buffer3, _Rb2}, RemBytes2} =
                case EE of
                    0 ->
                        {2,
                         decode_integer2(1, Buffer2, RemBytes1),
                         RemBytes1 + 1};
                    1 ->
                        {3,
                         decode_integer2(2, Buffer2, RemBytes1),
                         RemBytes1 + 2};
                    2 ->
                        {4,
                         decode_integer2(3, Buffer2, RemBytes1),
                         RemBytes1 + 3};
                    3 ->
                        <<ExpLen1,RestBuffer/binary>> = Buffer2,
                        {ExpLen1 + 2,
                         decode_integer2(ExpLen1, RestBuffer, RemBytes1),
                         RemBytes1 + ExpLen1}
                end,
            Length = Len - FirstLen,
            <<LongInt:Length/unit:8,RestBuff/binary>> = Buffer3,
            {{Mantissa, Buffer4}, RemBytes3} =
                if
                    Sign =:= 0 ->
                        {{LongInt, RestBuff}, 1 + Length};
                    true ->
                        {{-LongInt, RestBuff}, 1 + Length}
                end,
            {{Mantissa, Base, Exp}, Buffer4, RemBytes2 + RemBytes3}
    end.

encode_fragmented(Bin, Unit) ->
    encode_fragmented_1(Bin, Unit, 4).

encode_fragmented_1(Bin, Unit, N) ->
    SegSz = Unit * N * 16384,
    case Bin of
        <<B:SegSz/bitstring,T/bitstring>> ->
            [<<3:2,N:6>>, B | encode_fragmented_1(T, Unit, N)];
        _ when N > 1 ->
            encode_fragmented_1(Bin, Unit, N - 1);
        _ ->
            case bit_size(Bin) div Unit of
                Len when Len < 128 ->
                    [Len, Bin];
                Len when Len < 16384 ->
                    [<<2:2,Len:14>>, Bin]
            end
    end.

encode_neg_integer(-1, [B1 | _T] = L) when B1 > 127 ->
    L;
encode_neg_integer(N, Acc) ->
    encode_neg_integer(N bsr 8, [N band 255 | Acc]).

encode_pos_integer(0, [B | _Acc] = L) when B < 128 ->
    L;
encode_pos_integer(N, Acc) ->
    encode_pos_integer(N bsr 8, [N band 255 | Acc]).

encode_real(Real) ->
    encode_real([], Real).

encode_real(_C, {Mantissa, Base, Exponent}) when Base =:= 2 ->
    {Man, ExpAdd} = truncate_zeros(Mantissa),
    Exp = Exponent + ExpAdd,
    OctExp =
        if
            Exp >= 0 ->
                list_to_binary(encode_pos_integer(Exp, []));
            true ->
                list_to_binary(encode_neg_integer(Exp, []))
        end,
    SignBit =
        if
            Man > 0 ->
                0;
            true ->
                1
        end,
    SFactor = 0,
    OctExpLen = byte_size(OctExp),
    if
        OctExpLen > 255 ->
            exit({error, {asn1, {to_big_exp_in_encode_real, OctExpLen}}});
        true ->
            true
    end,
    {LenCode, EOctets} =
        case OctExpLen of
            1 ->
                {0, OctExp};
            2 ->
                {1, OctExp};
            3 ->
                {2, OctExp};
            _ ->
                {3, <<OctExpLen,OctExp/binary>>}
        end,
    BB = 0,
    FirstOctet = <<1:1,SignBit:1,BB:2,SFactor:2,LenCode:2>>,
    OctMantissa =
        if
            Man > 0 ->
                list_to_binary(real_mininum_octets(Man));
            true ->
                list_to_binary(real_mininum_octets(-Man))
        end,
    <<FirstOctet/binary,EOctets/binary,OctMantissa/binary>>;
encode_real(C, {Mantissa, Base, Exponent})
    when Base =:= 10, is_integer(Mantissa), is_integer(Exponent) ->
    ManStr = integer_to_list(Mantissa),
    encode_real_as_string(C, ManStr, Exponent);
encode_real(_C, {_, Base, _}) ->
    exit({error, {asn1, {encode_real_non_supported_encoding, Base}}});
encode_real(C, Real) when is_list(Real) ->
    {Mantissa, Exponent} =
        case string:lexemes(Real, "Ee") of
            [NR2] ->
                {NR2, 0};
            [NR3MB, NR3E] ->
                {NR3MB, list_to_integer(NR3E)}
        end,
    ZeroDecimal =
        fun("0") ->
               "";
           (L) ->
               L
        end,
    {NewMantissa, LenDecimal} =
        case Mantissa of
            [$. | Dec] ->
                NewMan = remove_trailing_zeros(Dec),
                {NewMan, length(ZeroDecimal(NewMan))};
            _ ->
                case string:lexemes(Mantissa, ",.") of
                    [Num] ->
                        {integer_to_list(list_to_integer(Num)), 0};
                    [Num, Dec] ->
                        NewDec = ZeroDecimal(remove_trailing_zeros(Dec)),
                        NewMan =
                            integer_to_list(list_to_integer(Num))
                            ++
                            NewDec,
                        {integer_to_list(list_to_integer(NewMan)),
                         length(NewDec)}
                end
        end,
    encode_real_as_string(C, NewMantissa, Exponent - LenDecimal).

encode_real_as_string(_C, Mantissa, Exponent)
    when is_list(Mantissa), is_integer(Exponent) ->
    TruncMant = remove_trailing_zeros(Mantissa),
    ExpIncr = length(Mantissa) - length(TruncMant),
    ExpStr = integer_to_list(Exponent + ExpIncr),
    ExpBin =
        case ExpStr of
            "0" ->
                <<"E+0">>;
            _ ->
                ExpB = list_to_binary(ExpStr),
                <<$E,ExpB/binary>>
        end,
    ManBin = list_to_binary(TruncMant),
    NR3 = 3,
    <<NR3,ManBin/binary,$.,ExpBin/binary>>.

real_mininum_octets(0, Acc) ->
    Acc;
real_mininum_octets(Val, Acc) ->
    real_mininum_octets(Val bsr 8, [Val band 255 | Acc]).

real_mininum_octets(Val) ->
    real_mininum_octets(Val, []).

remove_trailing_zeros(IntStr) ->
    case
        lists:dropwhile(fun($0) ->
                               true;
                           (_) ->
                               false
                        end,
                        lists:reverse(IntStr))
    of
        [] ->
            "0";
        ReversedIntStr ->
            lists:reverse(ReversedIntStr)
    end.

truncate_zeros(0, Sum) ->
    {0, Sum};
truncate_zeros(M, Sum) ->
    case M band 15 =:= M band 14 of
        true ->
            truncate_zeros(M bsr 1, Sum + 1);
        _ ->
            {M, Sum}
    end.

truncate_zeros(Num) ->
    truncate_zeros(Num, 0).
