%% Generated by the Erlang ASN.1 PER (aligned) compiler. Version: 5.0.21.1
%% Purpose: Encoding and decoding of the types in OCTETSTRINGS.

-module('OCTETSTRINGS').
-compile(nowarn_unused_vars).
-dialyzer(no_improper_lists).
-dialyzer(no_match).
-asn1_info([{vsn,'5.0.21.1'},
            {module,'OCTETSTRINGS'},
            {options,[{i,"/home/sandeep/Workspace/Github/asn1c-go/lib/per/testing/erlang/aper"},
 {outdir,"/home/sandeep/Workspace/Github/asn1c-go/lib/per/testing/erlang/aper"},
 per,
 {i,"."}]}]).

-export([encoding_rule/0,maps/0,bit_string_format/0,
         legacy_erlang_types/0]).
-export(['dialyzer-suppressions'/1]).
-export([
'enc_OCTETSTRING-NULL-NULL-FALSE'/1,
'enc_OCTETSTRING-0-NULL-FALSE'/1,
'enc_OCTETSTRING-1-NULL-FALSE'/1,
'enc_OCTETSTRING-10-NULL-FALSE'/1,
'enc_OCTETSTRING-1-1-FALSE'/1,
'enc_OCTETSTRING-4-4-FALSE'/1,
'enc_OCTETSTRING-8-8-FALSE'/1,
'enc_OCTETSTRING-16-16-FALSE'/1,
'enc_OCTETSTRING-64-64-FALSE'/1,
'enc_OCTETSTRING-1-127-FALSE'/1,
'enc_OCTETSTRING-1-128-FALSE'/1,
'enc_OCTETSTRING-1-255-FALSE'/1,
'enc_OCTETSTRING-1-256-FALSE'/1,
'enc_OCTETSTRING-0-2-FALSE'/1,
'enc_OCTETSTRING-0-4-FALSE'/1,
'enc_OCTETSTRING-0-8-FALSE'/1,
'enc_OCTETSTRING-0-10-FALSE'/1,
'enc_OCTETSTRING-0-16-FALSE'/1,
'enc_OCTETSTRING-0-32-FALSE'/1,
'enc_OCTETSTRING-0-64-FALSE'/1,
'enc_OCTETSTRING-0-128-FALSE'/1,
'enc_OCTETSTRING-0-256-FALSE'/1,
'enc_OCTETSTRING-0-512-FALSE'/1,
'enc_OCTETSTRING-0-1024-FALSE'/1,
'enc_OCTETSTRING-0-2048-FALSE'/1,
'enc_OCTETSTRING-0-4096-FALSE'/1,
'enc_OCTETSTRING-0-8192-FALSE'/1,
'enc_OCTETSTRING-0-16384-FALSE'/1,
'enc_OCTETSTRING-0-32768-FALSE'/1,
'enc_OCTETSTRING-0-65536-FALSE'/1,
'enc_OCTETSTRING-0-131072-FALSE'/1,
'enc_OCTETSTRING-0-262144-FALSE'/1,
'enc_OCTETSTRING-0-524288-FALSE'/1,
'enc_OCTETSTRING-0-1048576-FALSE'/1,
'enc_OCTETSTRING-0-2097152-FALSE'/1,
'enc_OCTETSTRING-0-0-TRUE'/1,
'enc_OCTETSTRING-0-1-TRUE'/1,
'enc_OCTETSTRING-0-2-TRUE'/1,
'enc_OCTETSTRING-0-4-TRUE'/1,
'enc_OCTETSTRING-0-8-TRUE'/1,
'enc_OCTETSTRING-0-16-TRUE'/1,
'enc_OCTETSTRING-0-32-TRUE'/1,
'enc_OCTETSTRING-0-64-TRUE'/1,
'enc_OCTETSTRING-0-128-TRUE'/1,
'enc_OCTETSTRING-0-256-TRUE'/1,
'enc_OCTETSTRING-0-512-TRUE'/1,
'enc_OCTETSTRING-0-1024-TRUE'/1,
'enc_OCTETSTRING-0-2048-TRUE'/1,
'enc_OCTETSTRING-0-4096-TRUE'/1,
'enc_OCTETSTRING-0-8192-TRUE'/1,
'enc_OCTETSTRING-0-16384-TRUE'/1,
'enc_OCTETSTRING-0-32768-TRUE'/1,
'enc_OCTETSTRING-0-65536-TRUE'/1,
'enc_OCTETSTRING-0-131072-TRUE'/1,
'enc_OCTETSTRING-0-262144-TRUE'/1,
'enc_OCTETSTRING-0-524288-TRUE'/1,
'enc_OCTETSTRING-1-1-TRUE'/1,
'enc_OCTETSTRING-4-4-TRUE'/1,
'enc_OCTETSTRING-8-8-TRUE'/1,
'enc_OCTETSTRING-16-16-TRUE'/1,
'enc_OCTETSTRING-64-64-TRUE'/1,
'enc_OCTETSTRING-1-127-TRUE'/1,
'enc_OCTETSTRING-1-128-TRUE'/1,
'enc_OCTETSTRING-1-255-TRUE'/1,
'enc_OCTETSTRING-1-256-TRUE'/1
]).

-export([
'dec_OCTETSTRING-NULL-NULL-FALSE'/1,
'dec_OCTETSTRING-0-NULL-FALSE'/1,
'dec_OCTETSTRING-1-NULL-FALSE'/1,
'dec_OCTETSTRING-10-NULL-FALSE'/1,
'dec_OCTETSTRING-1-1-FALSE'/1,
'dec_OCTETSTRING-4-4-FALSE'/1,
'dec_OCTETSTRING-8-8-FALSE'/1,
'dec_OCTETSTRING-16-16-FALSE'/1,
'dec_OCTETSTRING-64-64-FALSE'/1,
'dec_OCTETSTRING-1-127-FALSE'/1,
'dec_OCTETSTRING-1-128-FALSE'/1,
'dec_OCTETSTRING-1-255-FALSE'/1,
'dec_OCTETSTRING-1-256-FALSE'/1,
'dec_OCTETSTRING-0-2-FALSE'/1,
'dec_OCTETSTRING-0-4-FALSE'/1,
'dec_OCTETSTRING-0-8-FALSE'/1,
'dec_OCTETSTRING-0-10-FALSE'/1,
'dec_OCTETSTRING-0-16-FALSE'/1,
'dec_OCTETSTRING-0-32-FALSE'/1,
'dec_OCTETSTRING-0-64-FALSE'/1,
'dec_OCTETSTRING-0-128-FALSE'/1,
'dec_OCTETSTRING-0-256-FALSE'/1,
'dec_OCTETSTRING-0-512-FALSE'/1,
'dec_OCTETSTRING-0-1024-FALSE'/1,
'dec_OCTETSTRING-0-2048-FALSE'/1,
'dec_OCTETSTRING-0-4096-FALSE'/1,
'dec_OCTETSTRING-0-8192-FALSE'/1,
'dec_OCTETSTRING-0-16384-FALSE'/1,
'dec_OCTETSTRING-0-32768-FALSE'/1,
'dec_OCTETSTRING-0-65536-FALSE'/1,
'dec_OCTETSTRING-0-131072-FALSE'/1,
'dec_OCTETSTRING-0-262144-FALSE'/1,
'dec_OCTETSTRING-0-524288-FALSE'/1,
'dec_OCTETSTRING-0-1048576-FALSE'/1,
'dec_OCTETSTRING-0-2097152-FALSE'/1,
'dec_OCTETSTRING-0-0-TRUE'/1,
'dec_OCTETSTRING-0-1-TRUE'/1,
'dec_OCTETSTRING-0-2-TRUE'/1,
'dec_OCTETSTRING-0-4-TRUE'/1,
'dec_OCTETSTRING-0-8-TRUE'/1,
'dec_OCTETSTRING-0-16-TRUE'/1,
'dec_OCTETSTRING-0-32-TRUE'/1,
'dec_OCTETSTRING-0-64-TRUE'/1,
'dec_OCTETSTRING-0-128-TRUE'/1,
'dec_OCTETSTRING-0-256-TRUE'/1,
'dec_OCTETSTRING-0-512-TRUE'/1,
'dec_OCTETSTRING-0-1024-TRUE'/1,
'dec_OCTETSTRING-0-2048-TRUE'/1,
'dec_OCTETSTRING-0-4096-TRUE'/1,
'dec_OCTETSTRING-0-8192-TRUE'/1,
'dec_OCTETSTRING-0-16384-TRUE'/1,
'dec_OCTETSTRING-0-32768-TRUE'/1,
'dec_OCTETSTRING-0-65536-TRUE'/1,
'dec_OCTETSTRING-0-131072-TRUE'/1,
'dec_OCTETSTRING-0-262144-TRUE'/1,
'dec_OCTETSTRING-0-524288-TRUE'/1,
'dec_OCTETSTRING-1-1-TRUE'/1,
'dec_OCTETSTRING-4-4-TRUE'/1,
'dec_OCTETSTRING-8-8-TRUE'/1,
'dec_OCTETSTRING-16-16-TRUE'/1,
'dec_OCTETSTRING-64-64-TRUE'/1,
'dec_OCTETSTRING-1-127-TRUE'/1,
'dec_OCTETSTRING-1-128-TRUE'/1,
'dec_OCTETSTRING-1-255-TRUE'/1,
'dec_OCTETSTRING-1-256-TRUE'/1
]).

-export([info/0]).

-export([encode/2,decode/2]).

encoding_rule() -> per.

maps() -> false.

bit_string_format() -> bitstring.

legacy_erlang_types() -> false.

encode(Type, Data) ->
try complete(encode_disp(Type, Data)) of
  Bytes ->
    {ok,Bytes}
  catch
    Class:Exception:Stk when Class =:= error; Class =:= exit ->
      case Exception of
        {error,{asn1,Reason}} ->
          {error,{asn1,{Reason,Stk}}};
        Reason ->
         {error,{asn1,{Reason,Stk}}}
      end
end.

decode(Type, Data) ->
try
   {Result,_Rest} = decode_disp(Type, Data),
   {ok,Result}
  catch
    Class:Exception:Stk when Class =:= error; Class =:= exit ->
      case Exception of
        {error,{asn1,Reason}} ->
          {error,{asn1,{Reason,Stk}}};
        Reason ->
         {error,{asn1,{Reason,Stk}}}
      end
end.

encode_disp('OCTETSTRING-NULL-NULL-FALSE', Data) -> 'enc_OCTETSTRING-NULL-NULL-FALSE'(Data);
encode_disp('OCTETSTRING-0-NULL-FALSE', Data) -> 'enc_OCTETSTRING-0-NULL-FALSE'(Data);
encode_disp('OCTETSTRING-1-NULL-FALSE', Data) -> 'enc_OCTETSTRING-1-NULL-FALSE'(Data);
encode_disp('OCTETSTRING-10-NULL-FALSE', Data) -> 'enc_OCTETSTRING-10-NULL-FALSE'(Data);
encode_disp('OCTETSTRING-1-1-FALSE', Data) -> 'enc_OCTETSTRING-1-1-FALSE'(Data);
encode_disp('OCTETSTRING-4-4-FALSE', Data) -> 'enc_OCTETSTRING-4-4-FALSE'(Data);
encode_disp('OCTETSTRING-8-8-FALSE', Data) -> 'enc_OCTETSTRING-8-8-FALSE'(Data);
encode_disp('OCTETSTRING-16-16-FALSE', Data) -> 'enc_OCTETSTRING-16-16-FALSE'(Data);
encode_disp('OCTETSTRING-64-64-FALSE', Data) -> 'enc_OCTETSTRING-64-64-FALSE'(Data);
encode_disp('OCTETSTRING-1-127-FALSE', Data) -> 'enc_OCTETSTRING-1-127-FALSE'(Data);
encode_disp('OCTETSTRING-1-128-FALSE', Data) -> 'enc_OCTETSTRING-1-128-FALSE'(Data);
encode_disp('OCTETSTRING-1-255-FALSE', Data) -> 'enc_OCTETSTRING-1-255-FALSE'(Data);
encode_disp('OCTETSTRING-1-256-FALSE', Data) -> 'enc_OCTETSTRING-1-256-FALSE'(Data);
encode_disp('OCTETSTRING-0-2-FALSE', Data) -> 'enc_OCTETSTRING-0-2-FALSE'(Data);
encode_disp('OCTETSTRING-0-4-FALSE', Data) -> 'enc_OCTETSTRING-0-4-FALSE'(Data);
encode_disp('OCTETSTRING-0-8-FALSE', Data) -> 'enc_OCTETSTRING-0-8-FALSE'(Data);
encode_disp('OCTETSTRING-0-10-FALSE', Data) -> 'enc_OCTETSTRING-0-10-FALSE'(Data);
encode_disp('OCTETSTRING-0-16-FALSE', Data) -> 'enc_OCTETSTRING-0-16-FALSE'(Data);
encode_disp('OCTETSTRING-0-32-FALSE', Data) -> 'enc_OCTETSTRING-0-32-FALSE'(Data);
encode_disp('OCTETSTRING-0-64-FALSE', Data) -> 'enc_OCTETSTRING-0-64-FALSE'(Data);
encode_disp('OCTETSTRING-0-128-FALSE', Data) -> 'enc_OCTETSTRING-0-128-FALSE'(Data);
encode_disp('OCTETSTRING-0-256-FALSE', Data) -> 'enc_OCTETSTRING-0-256-FALSE'(Data);
encode_disp('OCTETSTRING-0-512-FALSE', Data) -> 'enc_OCTETSTRING-0-512-FALSE'(Data);
encode_disp('OCTETSTRING-0-1024-FALSE', Data) -> 'enc_OCTETSTRING-0-1024-FALSE'(Data);
encode_disp('OCTETSTRING-0-2048-FALSE', Data) -> 'enc_OCTETSTRING-0-2048-FALSE'(Data);
encode_disp('OCTETSTRING-0-4096-FALSE', Data) -> 'enc_OCTETSTRING-0-4096-FALSE'(Data);
encode_disp('OCTETSTRING-0-8192-FALSE', Data) -> 'enc_OCTETSTRING-0-8192-FALSE'(Data);
encode_disp('OCTETSTRING-0-16384-FALSE', Data) -> 'enc_OCTETSTRING-0-16384-FALSE'(Data);
encode_disp('OCTETSTRING-0-32768-FALSE', Data) -> 'enc_OCTETSTRING-0-32768-FALSE'(Data);
encode_disp('OCTETSTRING-0-65536-FALSE', Data) -> 'enc_OCTETSTRING-0-65536-FALSE'(Data);
encode_disp('OCTETSTRING-0-131072-FALSE', Data) -> 'enc_OCTETSTRING-0-131072-FALSE'(Data);
encode_disp('OCTETSTRING-0-262144-FALSE', Data) -> 'enc_OCTETSTRING-0-262144-FALSE'(Data);
encode_disp('OCTETSTRING-0-524288-FALSE', Data) -> 'enc_OCTETSTRING-0-524288-FALSE'(Data);
encode_disp('OCTETSTRING-0-1048576-FALSE', Data) -> 'enc_OCTETSTRING-0-1048576-FALSE'(Data);
encode_disp('OCTETSTRING-0-2097152-FALSE', Data) -> 'enc_OCTETSTRING-0-2097152-FALSE'(Data);
encode_disp('OCTETSTRING-0-0-TRUE', Data) -> 'enc_OCTETSTRING-0-0-TRUE'(Data);
encode_disp('OCTETSTRING-0-1-TRUE', Data) -> 'enc_OCTETSTRING-0-1-TRUE'(Data);
encode_disp('OCTETSTRING-0-2-TRUE', Data) -> 'enc_OCTETSTRING-0-2-TRUE'(Data);
encode_disp('OCTETSTRING-0-4-TRUE', Data) -> 'enc_OCTETSTRING-0-4-TRUE'(Data);
encode_disp('OCTETSTRING-0-8-TRUE', Data) -> 'enc_OCTETSTRING-0-8-TRUE'(Data);
encode_disp('OCTETSTRING-0-16-TRUE', Data) -> 'enc_OCTETSTRING-0-16-TRUE'(Data);
encode_disp('OCTETSTRING-0-32-TRUE', Data) -> 'enc_OCTETSTRING-0-32-TRUE'(Data);
encode_disp('OCTETSTRING-0-64-TRUE', Data) -> 'enc_OCTETSTRING-0-64-TRUE'(Data);
encode_disp('OCTETSTRING-0-128-TRUE', Data) -> 'enc_OCTETSTRING-0-128-TRUE'(Data);
encode_disp('OCTETSTRING-0-256-TRUE', Data) -> 'enc_OCTETSTRING-0-256-TRUE'(Data);
encode_disp('OCTETSTRING-0-512-TRUE', Data) -> 'enc_OCTETSTRING-0-512-TRUE'(Data);
encode_disp('OCTETSTRING-0-1024-TRUE', Data) -> 'enc_OCTETSTRING-0-1024-TRUE'(Data);
encode_disp('OCTETSTRING-0-2048-TRUE', Data) -> 'enc_OCTETSTRING-0-2048-TRUE'(Data);
encode_disp('OCTETSTRING-0-4096-TRUE', Data) -> 'enc_OCTETSTRING-0-4096-TRUE'(Data);
encode_disp('OCTETSTRING-0-8192-TRUE', Data) -> 'enc_OCTETSTRING-0-8192-TRUE'(Data);
encode_disp('OCTETSTRING-0-16384-TRUE', Data) -> 'enc_OCTETSTRING-0-16384-TRUE'(Data);
encode_disp('OCTETSTRING-0-32768-TRUE', Data) -> 'enc_OCTETSTRING-0-32768-TRUE'(Data);
encode_disp('OCTETSTRING-0-65536-TRUE', Data) -> 'enc_OCTETSTRING-0-65536-TRUE'(Data);
encode_disp('OCTETSTRING-0-131072-TRUE', Data) -> 'enc_OCTETSTRING-0-131072-TRUE'(Data);
encode_disp('OCTETSTRING-0-262144-TRUE', Data) -> 'enc_OCTETSTRING-0-262144-TRUE'(Data);
encode_disp('OCTETSTRING-0-524288-TRUE', Data) -> 'enc_OCTETSTRING-0-524288-TRUE'(Data);
encode_disp('OCTETSTRING-1-1-TRUE', Data) -> 'enc_OCTETSTRING-1-1-TRUE'(Data);
encode_disp('OCTETSTRING-4-4-TRUE', Data) -> 'enc_OCTETSTRING-4-4-TRUE'(Data);
encode_disp('OCTETSTRING-8-8-TRUE', Data) -> 'enc_OCTETSTRING-8-8-TRUE'(Data);
encode_disp('OCTETSTRING-16-16-TRUE', Data) -> 'enc_OCTETSTRING-16-16-TRUE'(Data);
encode_disp('OCTETSTRING-64-64-TRUE', Data) -> 'enc_OCTETSTRING-64-64-TRUE'(Data);
encode_disp('OCTETSTRING-1-127-TRUE', Data) -> 'enc_OCTETSTRING-1-127-TRUE'(Data);
encode_disp('OCTETSTRING-1-128-TRUE', Data) -> 'enc_OCTETSTRING-1-128-TRUE'(Data);
encode_disp('OCTETSTRING-1-255-TRUE', Data) -> 'enc_OCTETSTRING-1-255-TRUE'(Data);
encode_disp('OCTETSTRING-1-256-TRUE', Data) -> 'enc_OCTETSTRING-1-256-TRUE'(Data);
encode_disp(Type, _Data) -> exit({error,{asn1,{undefined_type,Type}}}).

decode_disp('OCTETSTRING-NULL-NULL-FALSE', Data) -> 'dec_OCTETSTRING-NULL-NULL-FALSE'(Data);
decode_disp('OCTETSTRING-0-NULL-FALSE', Data) -> 'dec_OCTETSTRING-0-NULL-FALSE'(Data);
decode_disp('OCTETSTRING-1-NULL-FALSE', Data) -> 'dec_OCTETSTRING-1-NULL-FALSE'(Data);
decode_disp('OCTETSTRING-10-NULL-FALSE', Data) -> 'dec_OCTETSTRING-10-NULL-FALSE'(Data);
decode_disp('OCTETSTRING-1-1-FALSE', Data) -> 'dec_OCTETSTRING-1-1-FALSE'(Data);
decode_disp('OCTETSTRING-4-4-FALSE', Data) -> 'dec_OCTETSTRING-4-4-FALSE'(Data);
decode_disp('OCTETSTRING-8-8-FALSE', Data) -> 'dec_OCTETSTRING-8-8-FALSE'(Data);
decode_disp('OCTETSTRING-16-16-FALSE', Data) -> 'dec_OCTETSTRING-16-16-FALSE'(Data);
decode_disp('OCTETSTRING-64-64-FALSE', Data) -> 'dec_OCTETSTRING-64-64-FALSE'(Data);
decode_disp('OCTETSTRING-1-127-FALSE', Data) -> 'dec_OCTETSTRING-1-127-FALSE'(Data);
decode_disp('OCTETSTRING-1-128-FALSE', Data) -> 'dec_OCTETSTRING-1-128-FALSE'(Data);
decode_disp('OCTETSTRING-1-255-FALSE', Data) -> 'dec_OCTETSTRING-1-255-FALSE'(Data);
decode_disp('OCTETSTRING-1-256-FALSE', Data) -> 'dec_OCTETSTRING-1-256-FALSE'(Data);
decode_disp('OCTETSTRING-0-2-FALSE', Data) -> 'dec_OCTETSTRING-0-2-FALSE'(Data);
decode_disp('OCTETSTRING-0-4-FALSE', Data) -> 'dec_OCTETSTRING-0-4-FALSE'(Data);
decode_disp('OCTETSTRING-0-8-FALSE', Data) -> 'dec_OCTETSTRING-0-8-FALSE'(Data);
decode_disp('OCTETSTRING-0-10-FALSE', Data) -> 'dec_OCTETSTRING-0-10-FALSE'(Data);
decode_disp('OCTETSTRING-0-16-FALSE', Data) -> 'dec_OCTETSTRING-0-16-FALSE'(Data);
decode_disp('OCTETSTRING-0-32-FALSE', Data) -> 'dec_OCTETSTRING-0-32-FALSE'(Data);
decode_disp('OCTETSTRING-0-64-FALSE', Data) -> 'dec_OCTETSTRING-0-64-FALSE'(Data);
decode_disp('OCTETSTRING-0-128-FALSE', Data) -> 'dec_OCTETSTRING-0-128-FALSE'(Data);
decode_disp('OCTETSTRING-0-256-FALSE', Data) -> 'dec_OCTETSTRING-0-256-FALSE'(Data);
decode_disp('OCTETSTRING-0-512-FALSE', Data) -> 'dec_OCTETSTRING-0-512-FALSE'(Data);
decode_disp('OCTETSTRING-0-1024-FALSE', Data) -> 'dec_OCTETSTRING-0-1024-FALSE'(Data);
decode_disp('OCTETSTRING-0-2048-FALSE', Data) -> 'dec_OCTETSTRING-0-2048-FALSE'(Data);
decode_disp('OCTETSTRING-0-4096-FALSE', Data) -> 'dec_OCTETSTRING-0-4096-FALSE'(Data);
decode_disp('OCTETSTRING-0-8192-FALSE', Data) -> 'dec_OCTETSTRING-0-8192-FALSE'(Data);
decode_disp('OCTETSTRING-0-16384-FALSE', Data) -> 'dec_OCTETSTRING-0-16384-FALSE'(Data);
decode_disp('OCTETSTRING-0-32768-FALSE', Data) -> 'dec_OCTETSTRING-0-32768-FALSE'(Data);
decode_disp('OCTETSTRING-0-65536-FALSE', Data) -> 'dec_OCTETSTRING-0-65536-FALSE'(Data);
decode_disp('OCTETSTRING-0-131072-FALSE', Data) -> 'dec_OCTETSTRING-0-131072-FALSE'(Data);
decode_disp('OCTETSTRING-0-262144-FALSE', Data) -> 'dec_OCTETSTRING-0-262144-FALSE'(Data);
decode_disp('OCTETSTRING-0-524288-FALSE', Data) -> 'dec_OCTETSTRING-0-524288-FALSE'(Data);
decode_disp('OCTETSTRING-0-1048576-FALSE', Data) -> 'dec_OCTETSTRING-0-1048576-FALSE'(Data);
decode_disp('OCTETSTRING-0-2097152-FALSE', Data) -> 'dec_OCTETSTRING-0-2097152-FALSE'(Data);
decode_disp('OCTETSTRING-0-0-TRUE', Data) -> 'dec_OCTETSTRING-0-0-TRUE'(Data);
decode_disp('OCTETSTRING-0-1-TRUE', Data) -> 'dec_OCTETSTRING-0-1-TRUE'(Data);
decode_disp('OCTETSTRING-0-2-TRUE', Data) -> 'dec_OCTETSTRING-0-2-TRUE'(Data);
decode_disp('OCTETSTRING-0-4-TRUE', Data) -> 'dec_OCTETSTRING-0-4-TRUE'(Data);
decode_disp('OCTETSTRING-0-8-TRUE', Data) -> 'dec_OCTETSTRING-0-8-TRUE'(Data);
decode_disp('OCTETSTRING-0-16-TRUE', Data) -> 'dec_OCTETSTRING-0-16-TRUE'(Data);
decode_disp('OCTETSTRING-0-32-TRUE', Data) -> 'dec_OCTETSTRING-0-32-TRUE'(Data);
decode_disp('OCTETSTRING-0-64-TRUE', Data) -> 'dec_OCTETSTRING-0-64-TRUE'(Data);
decode_disp('OCTETSTRING-0-128-TRUE', Data) -> 'dec_OCTETSTRING-0-128-TRUE'(Data);
decode_disp('OCTETSTRING-0-256-TRUE', Data) -> 'dec_OCTETSTRING-0-256-TRUE'(Data);
decode_disp('OCTETSTRING-0-512-TRUE', Data) -> 'dec_OCTETSTRING-0-512-TRUE'(Data);
decode_disp('OCTETSTRING-0-1024-TRUE', Data) -> 'dec_OCTETSTRING-0-1024-TRUE'(Data);
decode_disp('OCTETSTRING-0-2048-TRUE', Data) -> 'dec_OCTETSTRING-0-2048-TRUE'(Data);
decode_disp('OCTETSTRING-0-4096-TRUE', Data) -> 'dec_OCTETSTRING-0-4096-TRUE'(Data);
decode_disp('OCTETSTRING-0-8192-TRUE', Data) -> 'dec_OCTETSTRING-0-8192-TRUE'(Data);
decode_disp('OCTETSTRING-0-16384-TRUE', Data) -> 'dec_OCTETSTRING-0-16384-TRUE'(Data);
decode_disp('OCTETSTRING-0-32768-TRUE', Data) -> 'dec_OCTETSTRING-0-32768-TRUE'(Data);
decode_disp('OCTETSTRING-0-65536-TRUE', Data) -> 'dec_OCTETSTRING-0-65536-TRUE'(Data);
decode_disp('OCTETSTRING-0-131072-TRUE', Data) -> 'dec_OCTETSTRING-0-131072-TRUE'(Data);
decode_disp('OCTETSTRING-0-262144-TRUE', Data) -> 'dec_OCTETSTRING-0-262144-TRUE'(Data);
decode_disp('OCTETSTRING-0-524288-TRUE', Data) -> 'dec_OCTETSTRING-0-524288-TRUE'(Data);
decode_disp('OCTETSTRING-1-1-TRUE', Data) -> 'dec_OCTETSTRING-1-1-TRUE'(Data);
decode_disp('OCTETSTRING-4-4-TRUE', Data) -> 'dec_OCTETSTRING-4-4-TRUE'(Data);
decode_disp('OCTETSTRING-8-8-TRUE', Data) -> 'dec_OCTETSTRING-8-8-TRUE'(Data);
decode_disp('OCTETSTRING-16-16-TRUE', Data) -> 'dec_OCTETSTRING-16-16-TRUE'(Data);
decode_disp('OCTETSTRING-64-64-TRUE', Data) -> 'dec_OCTETSTRING-64-64-TRUE'(Data);
decode_disp('OCTETSTRING-1-127-TRUE', Data) -> 'dec_OCTETSTRING-1-127-TRUE'(Data);
decode_disp('OCTETSTRING-1-128-TRUE', Data) -> 'dec_OCTETSTRING-1-128-TRUE'(Data);
decode_disp('OCTETSTRING-1-255-TRUE', Data) -> 'dec_OCTETSTRING-1-255-TRUE'(Data);
decode_disp('OCTETSTRING-1-256-TRUE', Data) -> 'dec_OCTETSTRING-1-256-TRUE'(Data);
decode_disp(Type, _Data) -> exit({error,{asn1,{undefined_type,Type}}}).

info() ->
   case ?MODULE:module_info(attributes) of
     Attributes when is_list(Attributes) ->
       case lists:keyfind(asn1_info, 1, Attributes) of
         {_,Info} when is_list(Info) ->
           Info;
         _ ->
           []
       end;
     _ ->
       []
   end.
'enc_OCTETSTRING-NULL-NULL-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 128 ->
[align,
Enc1@len|Val];
Enc1@len < 16384 ->
[align,
<<2:2,Enc1@len:14>>|Val];
true ->
[align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-NULL-NULL-FALSE'(Bytes) ->
begin
V1@Pad3 = bit_size(Bytes) band 7,
{V1@V0,V1@Buf1} = case Bytes of
<<_:V1@Pad3,0:1,V1@V5:7,V1@V7:V1@V5/binary-unit:8,V1@Buf8/bitstring>> ->
{V1@V7,V1@Buf8};
<<_:V1@Pad3,1:1,0:1,V1@V6:14,V1@V8:V1@V6/binary-unit:8,V1@Buf9/bitstring>> ->
{V1@V8,V1@Buf9};
<<_:V1@Pad3,1:1,1:1,V1@V6:6,V1@Buf7/bitstring>> ->
{V1@V8,V1@Buf9}  = decode_fragmented(V1@V6, V1@Buf7, 8),
{V1@V8,V1@Buf9}
end,
V1@Conv10 = binary:copy(V1@V0),
{V1@Conv10,V1@Buf1}
end.

'enc_OCTETSTRING-0-NULL-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 128 ->
[align,
Enc1@len|Val];
Enc1@len < 16384 ->
[align,
<<2:2,Enc1@len:14>>|Val];
true ->
[align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-NULL-FALSE'(Bytes) ->
begin
V1@Pad3 = bit_size(Bytes) band 7,
{V1@V0,V1@Buf1} = case Bytes of
<<_:V1@Pad3,0:1,V1@V5:7,V1@V7:V1@V5/binary-unit:8,V1@Buf8/bitstring>> ->
{V1@V7,V1@Buf8};
<<_:V1@Pad3,1:1,0:1,V1@V6:14,V1@V8:V1@V6/binary-unit:8,V1@Buf9/bitstring>> ->
{V1@V8,V1@Buf9};
<<_:V1@Pad3,1:1,1:1,V1@V6:6,V1@Buf7/bitstring>> ->
{V1@V8,V1@Buf9}  = decode_fragmented(V1@V6, V1@Buf7, 8),
{V1@V8,V1@Buf9}
end,
V1@Conv10 = binary:copy(V1@V0),
{V1@Conv10,V1@Buf1}
end.

'enc_OCTETSTRING-1-NULL-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 128 ->
[align,
Enc1@len|Val];
Enc1@len < 16384 ->
[align,
<<2:2,Enc1@len:14>>|Val];
true ->
[align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-1-NULL-FALSE'(Bytes) ->
begin
V1@Pad3 = bit_size(Bytes) band 7,
{V1@V0,V1@Buf1} = case Bytes of
<<_:V1@Pad3,0:1,V1@V5:7,V1@V7:V1@V5/binary-unit:8,V1@Buf8/bitstring>> ->
{V1@V7,V1@Buf8};
<<_:V1@Pad3,1:1,0:1,V1@V6:14,V1@V8:V1@V6/binary-unit:8,V1@Buf9/bitstring>> ->
{V1@V8,V1@Buf9};
<<_:V1@Pad3,1:1,1:1,V1@V6:6,V1@Buf7/bitstring>> ->
{V1@V8,V1@Buf9}  = decode_fragmented(V1@V6, V1@Buf7, 8),
{V1@V8,V1@Buf9}
end,
V1@Conv10 = binary:copy(V1@V0),
{V1@Conv10,V1@Buf1}
end.

'enc_OCTETSTRING-10-NULL-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 128 ->
[align,
Enc1@len|Val];
Enc1@len < 16384 ->
[align,
<<2:2,Enc1@len:14>>|Val];
true ->
[align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-10-NULL-FALSE'(Bytes) ->
begin
V1@Pad3 = bit_size(Bytes) band 7,
{V1@V0,V1@Buf1} = case Bytes of
<<_:V1@Pad3,0:1,V1@V5:7,V1@V7:V1@V5/binary-unit:8,V1@Buf8/bitstring>> ->
{V1@V7,V1@Buf8};
<<_:V1@Pad3,1:1,0:1,V1@V6:14,V1@V8:V1@V6/binary-unit:8,V1@Buf9/bitstring>> ->
{V1@V8,V1@Buf9};
<<_:V1@Pad3,1:1,1:1,V1@V6:6,V1@Buf7/bitstring>> ->
{V1@V8,V1@Buf9}  = decode_fragmented(V1@V6, V1@Buf7, 8),
{V1@V8,V1@Buf9}
end,
V1@Conv10 = binary:copy(V1@V0),
{V1@Conv10,V1@Buf1}
end.

'enc_OCTETSTRING-1-1-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len =:= 1 ->
Val
end.


'dec_OCTETSTRING-1-1-FALSE'(Bytes) ->
begin
<<V1@V0:1/binary-unit:8,V1@Buf1/bitstring>> = Bytes,
V1@Conv2 = binary:copy(V1@V0),
{V1@Conv2,V1@Buf1}
end.

'enc_OCTETSTRING-4-4-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len =:= 4 ->
[align|Val]
end.


'dec_OCTETSTRING-4-4-FALSE'(Bytes) ->
begin
V1@Pad2 = bit_size(Bytes) band 7,
<<_:V1@Pad2,V1@V0:4/binary-unit:8,V1@Buf1/bitstring>> = Bytes,
V1@Conv4 = binary:copy(V1@V0),
{V1@Conv4,V1@Buf1}
end.

'enc_OCTETSTRING-8-8-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len =:= 8 ->
[align|Val]
end.


'dec_OCTETSTRING-8-8-FALSE'(Bytes) ->
begin
V1@Pad2 = bit_size(Bytes) band 7,
<<_:V1@Pad2,V1@V0:8/binary-unit:8,V1@Buf1/bitstring>> = Bytes,
V1@Conv4 = binary:copy(V1@V0),
{V1@Conv4,V1@Buf1}
end.

'enc_OCTETSTRING-16-16-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len =:= 16 ->
[align|Val]
end.


'dec_OCTETSTRING-16-16-FALSE'(Bytes) ->
begin
V1@Pad2 = bit_size(Bytes) band 7,
<<_:V1@Pad2,V1@V0:16/binary-unit:8,V1@Buf1/bitstring>> = Bytes,
V1@Conv4 = binary:copy(V1@V0),
{V1@Conv4,V1@Buf1}
end.

'enc_OCTETSTRING-64-64-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len =:= 64 ->
[align|Val]
end.


'dec_OCTETSTRING-64-64-FALSE'(Bytes) ->
begin
V1@Pad2 = bit_size(Bytes) band 7,
<<_:V1@Pad2,V1@V0:64/binary-unit:8,V1@Buf1/bitstring>> = Bytes,
V1@Conv4 = binary:copy(V1@V0),
{V1@Conv4,V1@Buf1}
end.

'enc_OCTETSTRING-1-127-FALSE'(Val) ->
Enc1@len = byte_size(Val),
Enc1@len@sub = Enc1@len - 1,
if 0 =< Enc1@len@sub, Enc1@len@sub < 127 ->
[<<Enc1@len@sub:7>>,
align|Val]
end.


'dec_OCTETSTRING-1-127-FALSE'(Bytes) ->
begin
<<V1@V0:7/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
V1@Add2 = V1@V0 + 1,
V1@Pad5 = bit_size(V1@Buf1) band 7,
<<_:V1@Pad5,V1@V3:V1@Add2/binary-unit:8,V1@Buf4/bitstring>> = V1@Buf1,
V1@Conv7 = binary:copy(V1@V3),
{V1@Conv7,V1@Buf4}
end.

'enc_OCTETSTRING-1-128-FALSE'(Val) ->
Enc1@len = byte_size(Val),
Enc1@len@sub = Enc1@len - 1,
if Enc1@len@sub bsr 7 =:= 0 ->
[<<Enc1@len@sub:7>>,
align|Val]
end.


'dec_OCTETSTRING-1-128-FALSE'(Bytes) ->
begin
<<V1@V0:7/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
V1@Add2 = V1@V0 + 1,
V1@Pad5 = bit_size(V1@Buf1) band 7,
<<_:V1@Pad5,V1@V3:V1@Add2/binary-unit:8,V1@Buf4/bitstring>> = V1@Buf1,
V1@Conv7 = binary:copy(V1@V3),
{V1@Conv7,V1@Buf4}
end.

'enc_OCTETSTRING-1-255-FALSE'(Val) ->
Enc1@len = byte_size(Val),
Enc1@len@sub = Enc1@len - 1,
if 0 =< Enc1@len@sub, Enc1@len@sub < 255 ->
[Enc1@len@sub,
align|Val]
end.


'dec_OCTETSTRING-1-255-FALSE'(Bytes) ->
begin
<<V1@V0:8/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
V1@Add2 = V1@V0 + 1,
V1@Pad5 = bit_size(V1@Buf1) band 7,
<<_:V1@Pad5,V1@V3:V1@Add2/binary-unit:8,V1@Buf4/bitstring>> = V1@Buf1,
V1@Conv7 = binary:copy(V1@V3),
{V1@Conv7,V1@Buf4}
end.

'enc_OCTETSTRING-1-256-FALSE'(Val) ->
Enc1@len = byte_size(Val),
Enc1@len@sub = Enc1@len - 1,
if Enc1@len@sub bsr 8 =:= 0 ->
[align,
Enc1@len@sub|Val]
end.


'dec_OCTETSTRING-1-256-FALSE'(Bytes) ->
begin
V1@Pad2 = bit_size(Bytes) band 7,
<<_:V1@Pad2,V1@V0:1/unsigned-unit:8,V1@Buf1/bitstring>> = Bytes,
V1@Add4 = V1@V0 + 1,
<<V1@V5:V1@Add4/binary-unit:8,V1@Buf6/bitstring>> = V1@Buf1,
V1@Conv7 = binary:copy(V1@V5),
{V1@Conv7,V1@Buf6}
end.

'enc_OCTETSTRING-0-2-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 3 ->
[<<Enc1@len:2>>,
align|Val]
end.


'dec_OCTETSTRING-0-2-FALSE'(Bytes) ->
begin
<<V1@V0:2/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
V1@Pad4 = bit_size(V1@Buf1) band 7,
<<_:V1@Pad4,V1@V2:V1@V0/binary-unit:8,V1@Buf3/bitstring>> = V1@Buf1,
V1@Conv6 = binary:copy(V1@V2),
{V1@Conv6,V1@Buf3}
end.

'enc_OCTETSTRING-0-4-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 5 ->
[<<Enc1@len:3>>,
align|Val]
end.


'dec_OCTETSTRING-0-4-FALSE'(Bytes) ->
begin
<<V1@V0:3/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
V1@Pad4 = bit_size(V1@Buf1) band 7,
<<_:V1@Pad4,V1@V2:V1@V0/binary-unit:8,V1@Buf3/bitstring>> = V1@Buf1,
V1@Conv6 = binary:copy(V1@V2),
{V1@Conv6,V1@Buf3}
end.

'enc_OCTETSTRING-0-8-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 9 ->
[<<Enc1@len:4>>,
align|Val]
end.


'dec_OCTETSTRING-0-8-FALSE'(Bytes) ->
begin
<<V1@V0:4/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
V1@Pad4 = bit_size(V1@Buf1) band 7,
<<_:V1@Pad4,V1@V2:V1@V0/binary-unit:8,V1@Buf3/bitstring>> = V1@Buf1,
V1@Conv6 = binary:copy(V1@V2),
{V1@Conv6,V1@Buf3}
end.

'enc_OCTETSTRING-0-10-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 11 ->
[<<Enc1@len:4>>,
align|Val]
end.


'dec_OCTETSTRING-0-10-FALSE'(Bytes) ->
begin
<<V1@V0:4/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
V1@Pad4 = bit_size(V1@Buf1) band 7,
<<_:V1@Pad4,V1@V2:V1@V0/binary-unit:8,V1@Buf3/bitstring>> = V1@Buf1,
V1@Conv6 = binary:copy(V1@V2),
{V1@Conv6,V1@Buf3}
end.

'enc_OCTETSTRING-0-16-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 17 ->
[<<Enc1@len:5>>,
align|Val]
end.


'dec_OCTETSTRING-0-16-FALSE'(Bytes) ->
begin
<<V1@V0:5/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
V1@Pad4 = bit_size(V1@Buf1) band 7,
<<_:V1@Pad4,V1@V2:V1@V0/binary-unit:8,V1@Buf3/bitstring>> = V1@Buf1,
V1@Conv6 = binary:copy(V1@V2),
{V1@Conv6,V1@Buf3}
end.

'enc_OCTETSTRING-0-32-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 33 ->
[<<Enc1@len:6>>,
align|Val]
end.


'dec_OCTETSTRING-0-32-FALSE'(Bytes) ->
begin
<<V1@V0:6/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
V1@Pad4 = bit_size(V1@Buf1) band 7,
<<_:V1@Pad4,V1@V2:V1@V0/binary-unit:8,V1@Buf3/bitstring>> = V1@Buf1,
V1@Conv6 = binary:copy(V1@V2),
{V1@Conv6,V1@Buf3}
end.

'enc_OCTETSTRING-0-64-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 65 ->
[<<Enc1@len:7>>,
align|Val]
end.


'dec_OCTETSTRING-0-64-FALSE'(Bytes) ->
begin
<<V1@V0:7/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
V1@Pad4 = bit_size(V1@Buf1) band 7,
<<_:V1@Pad4,V1@V2:V1@V0/binary-unit:8,V1@Buf3/bitstring>> = V1@Buf1,
V1@Conv6 = binary:copy(V1@V2),
{V1@Conv6,V1@Buf3}
end.

'enc_OCTETSTRING-0-128-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 129 ->
[Enc1@len,
align|Val]
end.


'dec_OCTETSTRING-0-128-FALSE'(Bytes) ->
begin
<<V1@V0:8/unsigned-unit:1,V1@Buf1/bitstring>> = Bytes,
V1@Pad4 = bit_size(V1@Buf1) band 7,
<<_:V1@Pad4,V1@V2:V1@V0/binary-unit:8,V1@Buf3/bitstring>> = V1@Buf1,
V1@Conv6 = binary:copy(V1@V2),
{V1@Conv6,V1@Buf3}
end.

'enc_OCTETSTRING-0-256-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 257 ->
[align,
<<Enc1@len:16>>|Val]
end.


'dec_OCTETSTRING-0-256-FALSE'(Bytes) ->
begin
V1@Pad2 = bit_size(Bytes) band 7,
<<_:V1@Pad2,V1@V0:2/unsigned-unit:8,V1@V4:V1@V0/binary-unit:8,V1@Buf5/bitstring>> = Bytes,
V1@Conv6 = binary:copy(V1@V4),
{V1@Conv6,V1@Buf5}
end.

'enc_OCTETSTRING-0-512-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 513 ->
[align,
<<Enc1@len:16>>|Val]
end.


'dec_OCTETSTRING-0-512-FALSE'(Bytes) ->
begin
V1@Pad2 = bit_size(Bytes) band 7,
<<_:V1@Pad2,V1@V0:2/unsigned-unit:8,V1@V4:V1@V0/binary-unit:8,V1@Buf5/bitstring>> = Bytes,
V1@Conv6 = binary:copy(V1@V4),
{V1@Conv6,V1@Buf5}
end.

'enc_OCTETSTRING-0-1024-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 1025 ->
[align,
<<Enc1@len:16>>|Val]
end.


'dec_OCTETSTRING-0-1024-FALSE'(Bytes) ->
begin
V1@Pad2 = bit_size(Bytes) band 7,
<<_:V1@Pad2,V1@V0:2/unsigned-unit:8,V1@V4:V1@V0/binary-unit:8,V1@Buf5/bitstring>> = Bytes,
V1@Conv6 = binary:copy(V1@V4),
{V1@Conv6,V1@Buf5}
end.

'enc_OCTETSTRING-0-2048-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 2049 ->
[align,
<<Enc1@len:16>>|Val]
end.


'dec_OCTETSTRING-0-2048-FALSE'(Bytes) ->
begin
V1@Pad2 = bit_size(Bytes) band 7,
<<_:V1@Pad2,V1@V0:2/unsigned-unit:8,V1@V4:V1@V0/binary-unit:8,V1@Buf5/bitstring>> = Bytes,
V1@Conv6 = binary:copy(V1@V4),
{V1@Conv6,V1@Buf5}
end.

'enc_OCTETSTRING-0-4096-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 4097 ->
[align,
<<Enc1@len:16>>|Val]
end.


'dec_OCTETSTRING-0-4096-FALSE'(Bytes) ->
begin
V1@Pad2 = bit_size(Bytes) band 7,
<<_:V1@Pad2,V1@V0:2/unsigned-unit:8,V1@V4:V1@V0/binary-unit:8,V1@Buf5/bitstring>> = Bytes,
V1@Conv6 = binary:copy(V1@V4),
{V1@Conv6,V1@Buf5}
end.

'enc_OCTETSTRING-0-8192-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 8193 ->
[align,
<<Enc1@len:16>>|Val]
end.


'dec_OCTETSTRING-0-8192-FALSE'(Bytes) ->
begin
V1@Pad2 = bit_size(Bytes) band 7,
<<_:V1@Pad2,V1@V0:2/unsigned-unit:8,V1@V4:V1@V0/binary-unit:8,V1@Buf5/bitstring>> = Bytes,
V1@Conv6 = binary:copy(V1@V4),
{V1@Conv6,V1@Buf5}
end.

'enc_OCTETSTRING-0-16384-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 16385 ->
[align,
<<Enc1@len:16>>|Val]
end.


'dec_OCTETSTRING-0-16384-FALSE'(Bytes) ->
begin
V1@Pad2 = bit_size(Bytes) band 7,
<<_:V1@Pad2,V1@V0:2/unsigned-unit:8,V1@V4:V1@V0/binary-unit:8,V1@Buf5/bitstring>> = Bytes,
V1@Conv6 = binary:copy(V1@V4),
{V1@Conv6,V1@Buf5}
end.

'enc_OCTETSTRING-0-32768-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 32769 ->
[align,
<<Enc1@len:16>>|Val]
end.


'dec_OCTETSTRING-0-32768-FALSE'(Bytes) ->
begin
V1@Pad2 = bit_size(Bytes) band 7,
<<_:V1@Pad2,V1@V0:2/unsigned-unit:8,V1@V4:V1@V0/binary-unit:8,V1@Buf5/bitstring>> = Bytes,
V1@Conv6 = binary:copy(V1@V4),
{V1@Conv6,V1@Buf5}
end.

'enc_OCTETSTRING-0-65536-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 128 ->
[align,
Enc1@len|Val];
Enc1@len < 16384 ->
[align,
<<2:2,Enc1@len:14>>|Val];
true ->
[align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-65536-FALSE'(Bytes) ->
begin
V1@Pad3 = bit_size(Bytes) band 7,
{V1@V0,V1@Buf1} = case Bytes of
<<_:V1@Pad3,0:1,V1@V5:7,V1@V7:V1@V5/binary-unit:8,V1@Buf8/bitstring>> ->
{V1@V7,V1@Buf8};
<<_:V1@Pad3,1:1,0:1,V1@V6:14,V1@V8:V1@V6/binary-unit:8,V1@Buf9/bitstring>> ->
{V1@V8,V1@Buf9};
<<_:V1@Pad3,1:1,1:1,V1@V6:6,V1@Buf7/bitstring>> ->
{V1@V8,V1@Buf9}  = decode_fragmented(V1@V6, V1@Buf7, 8),
{V1@V8,V1@Buf9}
end,
V1@Conv10 = binary:copy(V1@V0),
{V1@Conv10,V1@Buf1}
end.

'enc_OCTETSTRING-0-131072-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 128 ->
[align,
Enc1@len|Val];
Enc1@len < 16384 ->
[align,
<<2:2,Enc1@len:14>>|Val];
true ->
[align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-131072-FALSE'(Bytes) ->
begin
V1@Pad3 = bit_size(Bytes) band 7,
{V1@V0,V1@Buf1} = case Bytes of
<<_:V1@Pad3,0:1,V1@V5:7,V1@V7:V1@V5/binary-unit:8,V1@Buf8/bitstring>> ->
{V1@V7,V1@Buf8};
<<_:V1@Pad3,1:1,0:1,V1@V6:14,V1@V8:V1@V6/binary-unit:8,V1@Buf9/bitstring>> ->
{V1@V8,V1@Buf9};
<<_:V1@Pad3,1:1,1:1,V1@V6:6,V1@Buf7/bitstring>> ->
{V1@V8,V1@Buf9}  = decode_fragmented(V1@V6, V1@Buf7, 8),
{V1@V8,V1@Buf9}
end,
V1@Conv10 = binary:copy(V1@V0),
{V1@Conv10,V1@Buf1}
end.

'enc_OCTETSTRING-0-262144-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 128 ->
[align,
Enc1@len|Val];
Enc1@len < 16384 ->
[align,
<<2:2,Enc1@len:14>>|Val];
true ->
[align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-262144-FALSE'(Bytes) ->
begin
V1@Pad3 = bit_size(Bytes) band 7,
{V1@V0,V1@Buf1} = case Bytes of
<<_:V1@Pad3,0:1,V1@V5:7,V1@V7:V1@V5/binary-unit:8,V1@Buf8/bitstring>> ->
{V1@V7,V1@Buf8};
<<_:V1@Pad3,1:1,0:1,V1@V6:14,V1@V8:V1@V6/binary-unit:8,V1@Buf9/bitstring>> ->
{V1@V8,V1@Buf9};
<<_:V1@Pad3,1:1,1:1,V1@V6:6,V1@Buf7/bitstring>> ->
{V1@V8,V1@Buf9}  = decode_fragmented(V1@V6, V1@Buf7, 8),
{V1@V8,V1@Buf9}
end,
V1@Conv10 = binary:copy(V1@V0),
{V1@Conv10,V1@Buf1}
end.

'enc_OCTETSTRING-0-524288-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 128 ->
[align,
Enc1@len|Val];
Enc1@len < 16384 ->
[align,
<<2:2,Enc1@len:14>>|Val];
true ->
[align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-524288-FALSE'(Bytes) ->
begin
V1@Pad3 = bit_size(Bytes) band 7,
{V1@V0,V1@Buf1} = case Bytes of
<<_:V1@Pad3,0:1,V1@V5:7,V1@V7:V1@V5/binary-unit:8,V1@Buf8/bitstring>> ->
{V1@V7,V1@Buf8};
<<_:V1@Pad3,1:1,0:1,V1@V6:14,V1@V8:V1@V6/binary-unit:8,V1@Buf9/bitstring>> ->
{V1@V8,V1@Buf9};
<<_:V1@Pad3,1:1,1:1,V1@V6:6,V1@Buf7/bitstring>> ->
{V1@V8,V1@Buf9}  = decode_fragmented(V1@V6, V1@Buf7, 8),
{V1@V8,V1@Buf9}
end,
V1@Conv10 = binary:copy(V1@V0),
{V1@Conv10,V1@Buf1}
end.

'enc_OCTETSTRING-0-1048576-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 128 ->
[align,
Enc1@len|Val];
Enc1@len < 16384 ->
[align,
<<2:2,Enc1@len:14>>|Val];
true ->
[align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-1048576-FALSE'(Bytes) ->
begin
V1@Pad3 = bit_size(Bytes) band 7,
{V1@V0,V1@Buf1} = case Bytes of
<<_:V1@Pad3,0:1,V1@V5:7,V1@V7:V1@V5/binary-unit:8,V1@Buf8/bitstring>> ->
{V1@V7,V1@Buf8};
<<_:V1@Pad3,1:1,0:1,V1@V6:14,V1@V8:V1@V6/binary-unit:8,V1@Buf9/bitstring>> ->
{V1@V8,V1@Buf9};
<<_:V1@Pad3,1:1,1:1,V1@V6:6,V1@Buf7/bitstring>> ->
{V1@V8,V1@Buf9}  = decode_fragmented(V1@V6, V1@Buf7, 8),
{V1@V8,V1@Buf9}
end,
V1@Conv10 = binary:copy(V1@V0),
{V1@Conv10,V1@Buf1}
end.

'enc_OCTETSTRING-0-2097152-FALSE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 128 ->
[align,
Enc1@len|Val];
Enc1@len < 16384 ->
[align,
<<2:2,Enc1@len:14>>|Val];
true ->
[align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-2097152-FALSE'(Bytes) ->
begin
V1@Pad3 = bit_size(Bytes) band 7,
{V1@V0,V1@Buf1} = case Bytes of
<<_:V1@Pad3,0:1,V1@V5:7,V1@V7:V1@V5/binary-unit:8,V1@Buf8/bitstring>> ->
{V1@V7,V1@Buf8};
<<_:V1@Pad3,1:1,0:1,V1@V6:14,V1@V8:V1@V6/binary-unit:8,V1@Buf9/bitstring>> ->
{V1@V8,V1@Buf9};
<<_:V1@Pad3,1:1,1:1,V1@V6:6,V1@Buf7/bitstring>> ->
{V1@V8,V1@Buf9}  = decode_fragmented(V1@V6, V1@Buf7, 8),
{V1@V8,V1@Buf9}
end,
V1@Conv10 = binary:copy(V1@V0),
{V1@Conv10,V1@Buf1}
end.

'enc_OCTETSTRING-0-0-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len =:= 0 ->
[<<0:1>>|Val];
Enc1@len < 128 ->
[<<1:1>>,
align,
Enc1@len|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-0-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:0/binary-unit:8,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-0-1-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 2 ->
[<<0:1,Enc1@len:1>>,
align|Val];
Enc1@len < 128 ->
[<<1:1>>,
align,
Enc1@len|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-1-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:1/unsigned-unit:1,V1@Buf4/bitstring>> ->
V1@Pad7 = bit_size(V1@Buf4) band 7,
<<_:V1@Pad7,V1@V5:V1@V3/binary-unit:8,V1@Buf6/bitstring>> = V1@Buf4,
{V1@V5,V1@Buf6};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-0-2-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 3 ->
[<<0:1,Enc1@len:2>>,
align|Val];
Enc1@len < 128 ->
[<<1:1>>,
align,
Enc1@len|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-2-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:2/unsigned-unit:1,V1@Buf4/bitstring>> ->
V1@Pad7 = bit_size(V1@Buf4) band 7,
<<_:V1@Pad7,V1@V5:V1@V3/binary-unit:8,V1@Buf6/bitstring>> = V1@Buf4,
{V1@V5,V1@Buf6};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-0-4-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 5 ->
[<<0:1,Enc1@len:3>>,
align|Val];
Enc1@len < 128 ->
[<<1:1>>,
align,
Enc1@len|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-4-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:3/unsigned-unit:1,V1@Buf4/bitstring>> ->
V1@Pad7 = bit_size(V1@Buf4) band 7,
<<_:V1@Pad7,V1@V5:V1@V3/binary-unit:8,V1@Buf6/bitstring>> = V1@Buf4,
{V1@V5,V1@Buf6};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-0-8-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 9 ->
[<<0:1,Enc1@len:4>>,
align|Val];
Enc1@len < 128 ->
[<<1:1>>,
align,
Enc1@len|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-8-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:4/unsigned-unit:1,V1@Buf4/bitstring>> ->
V1@Pad7 = bit_size(V1@Buf4) band 7,
<<_:V1@Pad7,V1@V5:V1@V3/binary-unit:8,V1@Buf6/bitstring>> = V1@Buf4,
{V1@V5,V1@Buf6};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-0-16-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 17 ->
[<<0:1,Enc1@len:5>>,
align|Val];
Enc1@len < 128 ->
[<<1:1>>,
align,
Enc1@len|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-16-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:5/unsigned-unit:1,V1@Buf4/bitstring>> ->
V1@Pad7 = bit_size(V1@Buf4) band 7,
<<_:V1@Pad7,V1@V5:V1@V3/binary-unit:8,V1@Buf6/bitstring>> = V1@Buf4,
{V1@V5,V1@Buf6};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-0-32-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 33 ->
[<<0:1,Enc1@len:6>>,
align|Val];
Enc1@len < 128 ->
[<<1:1>>,
align,
Enc1@len|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-32-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:6/unsigned-unit:1,V1@Buf4/bitstring>> ->
V1@Pad7 = bit_size(V1@Buf4) band 7,
<<_:V1@Pad7,V1@V5:V1@V3/binary-unit:8,V1@Buf6/bitstring>> = V1@Buf4,
{V1@V5,V1@Buf6};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-0-64-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 65 ->
[<<0:1,Enc1@len:7>>,
align|Val];
Enc1@len < 128 ->
[<<1:1>>,
align,
Enc1@len|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-64-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7/unsigned-unit:1,V1@Buf4/bitstring>> ->
V1@Pad7 = bit_size(V1@Buf4) band 7,
<<_:V1@Pad7,V1@V5:V1@V3/binary-unit:8,V1@Buf6/bitstring>> = V1@Buf4,
{V1@V5,V1@Buf6};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-0-128-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 129 ->
[<<0:1,Enc1@len:8>>,
align|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-128-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:8/unsigned-unit:1,V1@Buf4/bitstring>> ->
V1@Pad7 = bit_size(V1@Buf4) band 7,
<<_:V1@Pad7,V1@V5:V1@V3/binary-unit:8,V1@Buf6/bitstring>> = V1@Buf4,
{V1@V5,V1@Buf6};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-0-256-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 257 ->
[<<0:1>>,
align,
<<Enc1@len:16>>|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-256-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@Buf2/bitstring>> ->
V1@Pad5 = bit_size(V1@Buf2) band 7,
<<_:V1@Pad5,V1@V3:2/unsigned-unit:8,V1@V7:V1@V3/binary-unit:8,V1@Buf8/bitstring>> = V1@Buf2,
{V1@V7,V1@Buf8};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-0-512-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 513 ->
[<<0:1>>,
align,
<<Enc1@len:16>>|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-512-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@Buf2/bitstring>> ->
V1@Pad5 = bit_size(V1@Buf2) band 7,
<<_:V1@Pad5,V1@V3:2/unsigned-unit:8,V1@V7:V1@V3/binary-unit:8,V1@Buf8/bitstring>> = V1@Buf2,
{V1@V7,V1@Buf8};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-0-1024-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 1025 ->
[<<0:1>>,
align,
<<Enc1@len:16>>|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-1024-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@Buf2/bitstring>> ->
V1@Pad5 = bit_size(V1@Buf2) band 7,
<<_:V1@Pad5,V1@V3:2/unsigned-unit:8,V1@V7:V1@V3/binary-unit:8,V1@Buf8/bitstring>> = V1@Buf2,
{V1@V7,V1@Buf8};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-0-2048-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 2049 ->
[<<0:1>>,
align,
<<Enc1@len:16>>|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-2048-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@Buf2/bitstring>> ->
V1@Pad5 = bit_size(V1@Buf2) band 7,
<<_:V1@Pad5,V1@V3:2/unsigned-unit:8,V1@V7:V1@V3/binary-unit:8,V1@Buf8/bitstring>> = V1@Buf2,
{V1@V7,V1@Buf8};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-0-4096-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 4097 ->
[<<0:1>>,
align,
<<Enc1@len:16>>|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-4096-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@Buf2/bitstring>> ->
V1@Pad5 = bit_size(V1@Buf2) band 7,
<<_:V1@Pad5,V1@V3:2/unsigned-unit:8,V1@V7:V1@V3/binary-unit:8,V1@Buf8/bitstring>> = V1@Buf2,
{V1@V7,V1@Buf8};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-0-8192-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 8193 ->
[<<0:1>>,
align,
<<Enc1@len:16>>|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-8192-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@Buf2/bitstring>> ->
V1@Pad5 = bit_size(V1@Buf2) band 7,
<<_:V1@Pad5,V1@V3:2/unsigned-unit:8,V1@V7:V1@V3/binary-unit:8,V1@Buf8/bitstring>> = V1@Buf2,
{V1@V7,V1@Buf8};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-0-16384-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 16385 ->
[<<0:1>>,
align,
<<Enc1@len:16>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-16384-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@Buf2/bitstring>> ->
V1@Pad5 = bit_size(V1@Buf2) band 7,
<<_:V1@Pad5,V1@V3:2/unsigned-unit:8,V1@V7:V1@V3/binary-unit:8,V1@Buf8/bitstring>> = V1@Buf2,
{V1@V7,V1@Buf8};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-0-32768-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 32769 ->
[<<0:1>>,
align,
<<Enc1@len:16>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-32768-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@Buf2/bitstring>> ->
V1@Pad5 = bit_size(V1@Buf2) band 7,
<<_:V1@Pad5,V1@V3:2/unsigned-unit:8,V1@V7:V1@V3/binary-unit:8,V1@Buf8/bitstring>> = V1@Buf2,
{V1@V7,V1@Buf8};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-0-65536-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 128 ->
[align,
Enc1@len|Val];
Enc1@len < 16384 ->
[align,
<<2:2,Enc1@len:14>>|Val];
true ->
[align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-65536-TRUE'(Bytes) ->
begin
V1@Pad3 = bit_size(Bytes) band 7,
{V1@V0,V1@Buf1} = case Bytes of
<<_:V1@Pad3,0:1,V1@V5:7,V1@V7:V1@V5/binary-unit:8,V1@Buf8/bitstring>> ->
{V1@V7,V1@Buf8};
<<_:V1@Pad3,1:1,0:1,V1@V6:14,V1@V8:V1@V6/binary-unit:8,V1@Buf9/bitstring>> ->
{V1@V8,V1@Buf9};
<<_:V1@Pad3,1:1,1:1,V1@V6:6,V1@Buf7/bitstring>> ->
{V1@V8,V1@Buf9}  = decode_fragmented(V1@V6, V1@Buf7, 8),
{V1@V8,V1@Buf9}
end,
V1@Conv10 = binary:copy(V1@V0),
{V1@Conv10,V1@Buf1}
end.

'enc_OCTETSTRING-0-131072-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 128 ->
[align,
Enc1@len|Val];
Enc1@len < 16384 ->
[align,
<<2:2,Enc1@len:14>>|Val];
true ->
[align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-131072-TRUE'(Bytes) ->
begin
V1@Pad3 = bit_size(Bytes) band 7,
{V1@V0,V1@Buf1} = case Bytes of
<<_:V1@Pad3,0:1,V1@V5:7,V1@V7:V1@V5/binary-unit:8,V1@Buf8/bitstring>> ->
{V1@V7,V1@Buf8};
<<_:V1@Pad3,1:1,0:1,V1@V6:14,V1@V8:V1@V6/binary-unit:8,V1@Buf9/bitstring>> ->
{V1@V8,V1@Buf9};
<<_:V1@Pad3,1:1,1:1,V1@V6:6,V1@Buf7/bitstring>> ->
{V1@V8,V1@Buf9}  = decode_fragmented(V1@V6, V1@Buf7, 8),
{V1@V8,V1@Buf9}
end,
V1@Conv10 = binary:copy(V1@V0),
{V1@Conv10,V1@Buf1}
end.

'enc_OCTETSTRING-0-262144-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 128 ->
[align,
Enc1@len|Val];
Enc1@len < 16384 ->
[align,
<<2:2,Enc1@len:14>>|Val];
true ->
[align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-262144-TRUE'(Bytes) ->
begin
V1@Pad3 = bit_size(Bytes) band 7,
{V1@V0,V1@Buf1} = case Bytes of
<<_:V1@Pad3,0:1,V1@V5:7,V1@V7:V1@V5/binary-unit:8,V1@Buf8/bitstring>> ->
{V1@V7,V1@Buf8};
<<_:V1@Pad3,1:1,0:1,V1@V6:14,V1@V8:V1@V6/binary-unit:8,V1@Buf9/bitstring>> ->
{V1@V8,V1@Buf9};
<<_:V1@Pad3,1:1,1:1,V1@V6:6,V1@Buf7/bitstring>> ->
{V1@V8,V1@Buf9}  = decode_fragmented(V1@V6, V1@Buf7, 8),
{V1@V8,V1@Buf9}
end,
V1@Conv10 = binary:copy(V1@V0),
{V1@Conv10,V1@Buf1}
end.

'enc_OCTETSTRING-0-524288-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len < 128 ->
[align,
Enc1@len|Val];
Enc1@len < 16384 ->
[align,
<<2:2,Enc1@len:14>>|Val];
true ->
[align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-0-524288-TRUE'(Bytes) ->
begin
V1@Pad3 = bit_size(Bytes) band 7,
{V1@V0,V1@Buf1} = case Bytes of
<<_:V1@Pad3,0:1,V1@V5:7,V1@V7:V1@V5/binary-unit:8,V1@Buf8/bitstring>> ->
{V1@V7,V1@Buf8};
<<_:V1@Pad3,1:1,0:1,V1@V6:14,V1@V8:V1@V6/binary-unit:8,V1@Buf9/bitstring>> ->
{V1@V8,V1@Buf9};
<<_:V1@Pad3,1:1,1:1,V1@V6:6,V1@Buf7/bitstring>> ->
{V1@V8,V1@Buf9}  = decode_fragmented(V1@V6, V1@Buf7, 8),
{V1@V8,V1@Buf9}
end,
V1@Conv10 = binary:copy(V1@V0),
{V1@Conv10,V1@Buf1}
end.

'enc_OCTETSTRING-1-1-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len =:= 1 ->
[<<0:1>>|Val];
Enc1@len < 128 ->
[<<1:1>>,
align,
Enc1@len|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-1-1-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:1/binary-unit:8,V1@Buf4/bitstring>> ->
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-4-4-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len =:= 4 ->
[<<0:1>>,
align|Val];
Enc1@len < 128 ->
[<<1:1>>,
align,
Enc1@len|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-4-4-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@Buf2/bitstring>> ->
V1@Pad5 = bit_size(V1@Buf2) band 7,
<<_:V1@Pad5,V1@V3:4/binary-unit:8,V1@Buf4/bitstring>> = V1@Buf2,
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-8-8-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len =:= 8 ->
[<<0:1>>,
align|Val];
Enc1@len < 128 ->
[<<1:1>>,
align,
Enc1@len|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-8-8-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@Buf2/bitstring>> ->
V1@Pad5 = bit_size(V1@Buf2) band 7,
<<_:V1@Pad5,V1@V3:8/binary-unit:8,V1@Buf4/bitstring>> = V1@Buf2,
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-16-16-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len =:= 16 ->
[<<0:1>>,
align|Val];
Enc1@len < 128 ->
[<<1:1>>,
align,
Enc1@len|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-16-16-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@Buf2/bitstring>> ->
V1@Pad5 = bit_size(V1@Buf2) band 7,
<<_:V1@Pad5,V1@V3:16/binary-unit:8,V1@Buf4/bitstring>> = V1@Buf2,
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-64-64-TRUE'(Val) ->
Enc1@len = byte_size(Val),
if Enc1@len =:= 64 ->
[<<0:1>>,
align|Val];
Enc1@len < 128 ->
[<<1:1>>,
align,
Enc1@len|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-64-64-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@Buf2/bitstring>> ->
V1@Pad5 = bit_size(V1@Buf2) band 7,
<<_:V1@Pad5,V1@V3:64/binary-unit:8,V1@Buf4/bitstring>> = V1@Buf2,
{V1@V3,V1@Buf4};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-1-127-TRUE'(Val) ->
Enc1@len = byte_size(Val),
Enc1@len@sub = Enc1@len - 1,
if 0 =< Enc1@len@sub, Enc1@len@sub < 127 ->
[<<0:1,Enc1@len@sub:7>>,
align|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-1-127-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7/unsigned-unit:1,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + 1,
V1@Pad8 = bit_size(V1@Buf4) band 7,
<<_:V1@Pad8,V1@V6:V1@Add5/binary-unit:8,V1@Buf7/bitstring>> = V1@Buf4,
{V1@V6,V1@Buf7};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-1-128-TRUE'(Val) ->
Enc1@len = byte_size(Val),
Enc1@len@sub = Enc1@len - 1,
if Enc1@len@sub bsr 7 =:= 0 ->
[<<0:1,Enc1@len@sub:7>>,
align|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-1-128-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7/unsigned-unit:1,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + 1,
V1@Pad8 = bit_size(V1@Buf4) band 7,
<<_:V1@Pad8,V1@V6:V1@Add5/binary-unit:8,V1@Buf7/bitstring>> = V1@Buf4,
{V1@V6,V1@Buf7};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-1-255-TRUE'(Val) ->
Enc1@len = byte_size(Val),
Enc1@len@sub = Enc1@len - 1,
if 0 =< Enc1@len@sub, Enc1@len@sub < 255 ->
[<<0:1,Enc1@len@sub:8>>,
align|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-1-255-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:8/unsigned-unit:1,V1@Buf4/bitstring>> ->
V1@Add5 = V1@V3 + 1,
V1@Pad8 = bit_size(V1@Buf4) band 7,
<<_:V1@Pad8,V1@V6:V1@Add5/binary-unit:8,V1@Buf7/bitstring>> = V1@Buf4,
{V1@V6,V1@Buf7};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.

'enc_OCTETSTRING-1-256-TRUE'(Val) ->
Enc1@len = byte_size(Val),
Enc1@len@sub = Enc1@len - 1,
if Enc1@len@sub bsr 8 =:= 0 ->
[<<0:1>>,
align,
Enc1@len@sub|Val];
Enc1@len < 16384 ->
[<<1:1>>,
align,
<<2:2,Enc1@len:14>>|Val];
true ->
[<<1:1>>,
align|encode_fragmented(Val, 8)]
end.


'dec_OCTETSTRING-1-256-TRUE'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@Buf2/bitstring>> ->
V1@Pad5 = bit_size(V1@Buf2) band 7,
<<_:V1@Pad5,V1@V3:1/unsigned-unit:8,V1@Buf4/bitstring>> = V1@Buf2,
V1@Add7 = V1@V3 + 1,
<<V1@V8:V1@Add7/binary-unit:8,V1@Buf9/bitstring>> = V1@Buf4,
{V1@V8,V1@Buf9};
<<1:1,V1@Buf2/bitstring>> ->
V1@Pad6 = bit_size(V1@Buf2) band 7,
{V1@V3,V1@Buf4} = case V1@Buf2 of
<<_:V1@Pad6,0:1,V1@V8:7,V1@V10:V1@V8/binary-unit:8,V1@Buf11/bitstring>> ->
{V1@V10,V1@Buf11};
<<_:V1@Pad6,1:1,0:1,V1@V9:14,V1@V11:V1@V9/binary-unit:8,V1@Buf12/bitstring>> ->
{V1@V11,V1@Buf12};
<<_:V1@Pad6,1:1,1:1,V1@V9:6,V1@Buf10/bitstring>> ->
{V1@V11,V1@Buf12}  = decode_fragmented(V1@V9, V1@Buf10, 8),
{V1@V11,V1@Buf12}
end,
{V1@V3,V1@Buf4}
end,
V1@Conv13 = binary:copy(V1@V0),
{V1@Conv13,V1@Buf1}
end.


%%%
%%% Run-time functions.
%%%

'dialyzer-suppressions'(Arg) ->
    complete(element(1, Arg)),
    ok.

complete(L0) ->
    L = complete(L0, []),
    case list_to_bitstring(L) of
        <<>> ->
            <<0>>;
        Bin ->
            Bin
    end.

complete([], Bits, []) ->
    case Bits band 7 of
        0 ->
            [];
        N ->
            [<<0:(8 - N)>>]
    end;
complete([], Bits, [H | More]) ->
    complete(H, Bits, More);
complete([align | T], Bits, More) ->
    case Bits band 7 of
        0 ->
            complete(T, More);
        1 ->
            [<<0:7>> | complete(T, More)];
        2 ->
            [<<0:6>> | complete(T, More)];
        3 ->
            [<<0:5>> | complete(T, More)];
        4 ->
            [<<0:4>> | complete(T, More)];
        5 ->
            [<<0:3>> | complete(T, More)];
        6 ->
            [<<0:2>> | complete(T, More)];
        7 ->
            [<<0:1>> | complete(T, More)]
    end;
complete([[] | T], Bits, More) ->
    complete(T, Bits, More);
complete([[_ | _] = H], Bits, More) ->
    complete(H, Bits, More);
complete([[_ | _] = H | T], Bits, More) ->
    complete(H, Bits, [T | More]);
complete([H | T], Bits, More) when is_integer(H); is_binary(H) ->
    [H | complete(T, Bits, More)];
complete([H | T], Bits, More) ->
    [H | complete(T, Bits + bit_size(H), More)];
complete(Bin, Bits, More) when is_binary(Bin) ->
    [Bin | complete([], Bits, More)];
complete(Bin, Bits, More) ->
    [Bin | complete([], Bits + bit_size(Bin), More)].

complete([], []) ->
    [];
complete([], [H | More]) ->
    complete(H, More);
complete([align | T], More) ->
    complete(T, More);
complete([[] | T], More) ->
    complete(T, More);
complete([[_ | _] = H], More) ->
    complete(H, More);
complete([[_ | _] = H | T], More) ->
    complete(H, [T | More]);
complete([H | T], More) when is_integer(H); is_binary(H) ->
    [H | complete(T, More)];
complete([H | T], More) ->
    [H | complete(T, bit_size(H), More)];
complete(Bin, More) when is_binary(Bin) ->
    [Bin | complete([], More)];
complete(Bin, More) ->
    [Bin | complete([], bit_size(Bin), More)].

decode_fragmented(SegSz0, Buf0, Unit) ->
    SegSz = SegSz0 * Unit * 16384,
    <<Res:SegSz/bitstring,Buf/bitstring>> = Buf0,
    decode_fragmented_1(Buf, Unit, Res).

decode_fragmented_1(<<0:1,N:7,Buf0/bitstring>>, Unit, Res) ->
    Sz = N * Unit,
    <<S:Sz/bitstring,Buf/bitstring>> = Buf0,
    {<<Res/bitstring,S/bitstring>>, Buf};
decode_fragmented_1(<<1:1,0:1,N:14,Buf0/bitstring>>, Unit, Res) ->
    Sz = N * Unit,
    <<S:Sz/bitstring,Buf/bitstring>> = Buf0,
    {<<Res/bitstring,S/bitstring>>, Buf};
decode_fragmented_1(<<1:1,1:1,SegSz0:6,Buf0/bitstring>>, Unit, Res0) ->
    SegSz = SegSz0 * Unit * 16384,
    <<Frag:SegSz/bitstring,Buf/bitstring>> = Buf0,
    Res = <<Res0/bitstring,Frag/bitstring>>,
    decode_fragmented_1(Buf, Unit, Res).

encode_fragmented(Bin, Unit) ->
    encode_fragmented_1(Bin, Unit, 4).

encode_fragmented_1(Bin, Unit, N) ->
    SegSz = Unit * N * 16384,
    case Bin of
        <<B:SegSz/bitstring,T/bitstring>> ->
            [<<3:2,N:6>>, B | encode_fragmented_1(T, Unit, N)];
        _ when N > 1 ->
            encode_fragmented_1(Bin, Unit, N - 1);
        _ ->
            case bit_size(Bin) div Unit of
                Len when Len < 128 ->
                    [Len, Bin];
                Len when Len < 16384 ->
                    [<<2:2,Len:14>>, Bin]
            end
    end.
