%% Generated by the Erlang ASN.1 PER (unaligned) compiler. Version: 5.0.17
%% Purpose: Encoding and decoding of the types in YEAR.

-module('YEAR').
-compile(nowarn_unused_vars).
-dialyzer(no_improper_lists).
-dialyzer(no_match).
-include("YEAR.hrl").
-asn1_info([{vsn,'5.0.17'},
            {module,'YEAR'},
            {options,[{i,"uper"},{outdir,"uper"},uper,{i,"."},{i,".."}]}]).

-export([encoding_rule/0,maps/0,bit_string_format/0,
         legacy_erlang_types/0]).
-export(['dialyzer-suppressions'/1]).
-export([
'enc_YEAR-ENCODING'/1,
'enc_ANY-YEAR-ENCODING'/1,
'enc_YEAR-MONTH-ENCODING'/1,
'enc_DATE-ENCODING'/1
]).

-export([
'dec_YEAR-ENCODING'/1,
'dec_ANY-YEAR-ENCODING'/1,
'dec_YEAR-MONTH-ENCODING'/1,
'dec_DATE-ENCODING'/1
]).

-export([info/0]).

-export([encode/2,decode/2]).

encoding_rule() -> uper.

maps() -> false.

bit_string_format() -> bitstring.

legacy_erlang_types() -> false.

encode(Type, Data) ->
try complete(encode_disp(Type, Data)) of
  Bytes ->
    {ok,Bytes}
  catch
    Class:Exception:Stk when Class =:= error; Class =:= exit ->
      case Exception of
        {error,{asn1,Reason}} ->
          {error,{asn1,{Reason,Stk}}};
        Reason ->
         {error,{asn1,{Reason,Stk}}}
      end
end.

decode(Type, Data) ->
try
   {Result,_Rest} = decode_disp(Type, Data),
   {ok,Result}
  catch
    Class:Exception:Stk when Class =:= error; Class =:= exit ->
      case Exception of
        {error,{asn1,Reason}} ->
          {error,{asn1,{Reason,Stk}}};
        Reason ->
         {error,{asn1,{Reason,Stk}}}
      end
end.

encode_disp('YEAR-ENCODING', Data) -> 'enc_YEAR-ENCODING'(Data);
encode_disp('ANY-YEAR-ENCODING', Data) -> 'enc_ANY-YEAR-ENCODING'(Data);
encode_disp('YEAR-MONTH-ENCODING', Data) -> 'enc_YEAR-MONTH-ENCODING'(Data);
encode_disp('DATE-ENCODING', Data) -> 'enc_DATE-ENCODING'(Data);
encode_disp(Type, _Data) -> exit({error,{asn1,{undefined_type,Type}}}).

decode_disp('YEAR-ENCODING', Data) -> 'dec_YEAR-ENCODING'(Data);
decode_disp('ANY-YEAR-ENCODING', Data) -> 'dec_ANY-YEAR-ENCODING'(Data);
decode_disp('YEAR-MONTH-ENCODING', Data) -> 'dec_YEAR-MONTH-ENCODING'(Data);
decode_disp('DATE-ENCODING', Data) -> 'dec_DATE-ENCODING'(Data);
decode_disp(Type, _Data) -> exit({error,{asn1,{undefined_type,Type}}}).

info() ->
   case ?MODULE:module_info(attributes) of
     Attributes when is_list(Attributes) ->
       case lists:keyfind(asn1_info, 1, Attributes) of
         {_,Info} when is_list(Info) ->
           Info;
         _ ->
           []
       end;
     _ ->
       []
   end.
'enc_YEAR-ENCODING'(Val) ->
{ChoiceTag,ChoiceVal} = Val,
if ChoiceTag =:= immediate ->
begin
ChoiceVal@sub = ChoiceVal - 2005,
if ChoiceVal@sub bsr 4 =:= 0 ->
<<0:2,ChoiceVal@sub:4>>;
true ->
exit({error,{asn1,{illegal_integer,ChoiceVal}}})
end
end;
ChoiceTag =:= 'near-future' ->
begin
ChoiceVal@sub = ChoiceVal - 2021,
if ChoiceVal@sub bsr 8 =:= 0 ->
[<<1:2,ChoiceVal@sub:8>>];
true ->
exit({error,{asn1,{illegal_integer,ChoiceVal}}})
end
end;
ChoiceTag =:= 'near-past' ->
begin
ChoiceVal@sub = ChoiceVal - 1749,
if ChoiceVal@sub bsr 8 =:= 0 ->
[<<2:2,ChoiceVal@sub:8>>];
true ->
exit({error,{asn1,{illegal_integer,ChoiceVal}}})
end
end;
ChoiceTag =:= remainder ->
[<<3:2>>|encode_unconstrained_number(ChoiceVal)]
end.


'dec_YEAR-ENCODING'(Bytes) ->
{Choice,Bytes1} = 
begin
<<V1@V0:2,V1@Buf1/bitstring>> = Bytes,
{V1@V0,V1@Buf1}
end,
case Choice of
0 ->
{Val,NewBytes} = begin
begin
<<V2@V0:4,V2@Buf1/bitstring>> = Bytes1,
V2@Add2 = V2@V0 + 2005,
{V2@Add2,V2@Buf1}
end
end,
{{immediate,Val},NewBytes};
1 ->
{Val,NewBytes} = begin
begin
<<V3@V0:8,V3@Buf1/bitstring>> = Bytes1,
V3@Add2 = V3@V0 + 2021,
{V3@Add2,V3@Buf1}
end
end,
{{'near-future',Val},NewBytes};
2 ->
{Val,NewBytes} = begin
begin
<<V4@V0:8,V4@Buf1/bitstring>> = Bytes1,
V4@Add2 = V4@V0 + 1749,
{V4@Add2,V4@Buf1}
end
end,
{{'near-past',Val},NewBytes};
3 ->
{Val,NewBytes} = begin
begin
{V5@V0,V5@Buf1} = case Bytes1 of
<<0:1,V5@V3:7,V5@Buf4/bitstring>> when V5@V3 =/= 0 ->
{V5@V3,V5@Buf4};
<<1:1,0:1,V5@V4:14,V5@Buf5/bitstring>> when V5@V4 =/= 0 ->
{V5@V4,V5@Buf5}
end,
<<V5@V6:V5@V0/signed-unit:8,V5@Buf7/bitstring>> = V5@Buf1,
{V5@V6,V5@Buf7}
end
end,
{{remainder,Val},NewBytes}
end.
'enc_ANY-YEAR-ENCODING'(Val) ->
encode_unconstrained_number(Val).


'dec_ANY-YEAR-ENCODING'(Bytes) ->
begin
{V1@V0,V1@Buf1} = case Bytes of
<<0:1,V1@V3:7,V1@Buf4/bitstring>> when V1@V3 =/= 0 ->
{V1@V3,V1@Buf4};
<<1:1,0:1,V1@V4:14,V1@Buf5/bitstring>> when V1@V4 =/= 0 ->
{V1@V4,V1@Buf5}
end,
<<V1@V6:V1@V0/signed-unit:8,V1@Buf7/bitstring>> = V1@Buf1,
{V1@V6,V1@Buf7}
end.

'enc_YEAR-MONTH-ENCODING'(Val) ->
[begin
%% attribute year(1) with type YEAR-ENCODING
Enc1@element = element(2, Val),
'enc_YEAR-ENCODING'(Enc1@element)
end|begin
%% attribute month(2) with type INTEGER
Enc2@element = element(3, Val),
Enc2@element@sub = Enc2@element - 1,
if 0 =< Enc2@element@sub, Enc2@element@sub < 12 ->
<<Enc2@element@sub:4>>;
true ->
exit({error,{asn1,{illegal_integer,Enc2@element}}})
end
end].


'dec_YEAR-MONTH-ENCODING'(Bytes) ->

%% attribute year(1) with type YEAR-ENCODING
{Term1,Bytes1} = 'dec_YEAR-ENCODING'(Bytes),

%% attribute month(2) with type INTEGER
{Term2,Bytes2} = begin
<<V1@V0:4,V1@Buf1/bitstring>> = Bytes1,
V1@Add2 = V1@V0 + 1,
{V1@Add2,V1@Buf1}
end,
Res1 = {'YEAR-MONTH-ENCODING',Term1,Term2},
{Res1,Bytes2}.

'enc_DATE-ENCODING'(Val) ->
[begin
%% attribute year(1) with type YEAR-ENCODING
Enc1@element = element(2, Val),
'enc_YEAR-ENCODING'(Enc1@element)
end,
begin
%% attribute month(2) with type INTEGER
Enc2@element = element(3, Val),
Enc2@element@sub = Enc2@element - 1,
if 0 =< Enc2@element@sub, Enc2@element@sub < 12 ->
<<Enc2@element@sub:4>>;
true ->
exit({error,{asn1,{illegal_integer,Enc2@element}}})
end
end|begin
%% attribute day(3) with type INTEGER
Enc4@element = element(4, Val),
Enc4@element@sub = Enc4@element - 1,
if 0 =< Enc4@element@sub, Enc4@element@sub < 31 ->
<<Enc4@element@sub:5>>;
true ->
exit({error,{asn1,{illegal_integer,Enc4@element}}})
end
end].


'dec_DATE-ENCODING'(Bytes) ->

%% attribute year(1) with type YEAR-ENCODING
{Term1,Bytes1} = 'dec_YEAR-ENCODING'(Bytes),

%% attribute month(2) with type INTEGER
{Term2,Bytes2} = begin
<<V1@V0:4,V1@Buf1/bitstring>> = Bytes1,
V1@Add2 = V1@V0 + 1,
{V1@Add2,V1@Buf1}
end,

%% attribute day(3) with type INTEGER
{Term3,Bytes3} = begin
<<V2@V0:5,V2@Buf1/bitstring>> = Bytes2,
V2@Add2 = V2@V0 + 1,
{V2@Add2,V2@Buf1}
end,
Res1 = {'DATE-ENCODING',Term1,Term2,Term3},
{Res1,Bytes3}.


%%%
%%% Run-time functions.
%%%

'dialyzer-suppressions'(Arg) ->
    complete(element(1, Arg)),
    ok.

complete(InList) when is_list(InList) ->
    case list_to_bitstring(InList) of
        <<>> ->
            <<0>>;
        Res ->
            Sz = bit_size(Res),
            case Sz band 7 of
                0 ->
                    Res;
                Bits ->
                    <<Res:Sz/bitstring,0:(8 - Bits)>>
            end
    end;
complete(Bin) when is_binary(Bin) ->
    case Bin of
        <<>> ->
            <<0>>;
        _ ->
            Bin
    end;
complete(InList) when is_bitstring(InList) ->
    Sz = bit_size(InList),
    PadLen = 8 - Sz band 7,
    <<InList:Sz/bitstring,0:PadLen>>.

encode_unconstrained_number(Val) when not is_integer(Val) ->
    exit({error, {asn1, {illegal_integer, Val}}});
encode_unconstrained_number(Val) when Val >= 0 ->
    if
        Val < 128 ->
            [1, Val];
        Val < 256 ->
            [<<2,0>>, Val];
        true ->
            case binary:encode_unsigned(Val) of
                <<0:1,_/bitstring>> = Bin ->
                    case byte_size(Bin) of
                        Sz when Sz < 128 ->
                            [Sz, Bin];
                        Sz when Sz < 16384 ->
                            [<<2:2,Sz:14>>, Bin]
                    end;
                <<1:1,_/bitstring>> = Bin ->
                    case byte_size(Bin) + 1 of
                        Sz when Sz < 128 ->
                            [Sz, 0, Bin];
                        Sz when Sz < 16384 ->
                            [<<2:2,Sz:14,0:8>>, Bin]
                    end
            end
    end;
encode_unconstrained_number(Val) ->
    Oct = enint(Val, []),
    Len = length(Oct),
    if
        Len < 128 ->
            [Len | Oct];
        Len < 16384 ->
            [<<2:2,Len:14>> | Oct]
    end.

enint(- 1, [B1 | T]) when B1 > 127 ->
    [B1 | T];
enint(N, Acc) ->
    enint(N bsr 8, [N band 255 | Acc]).
